### ISSUE TITLE
优化推送通知，目前通知还是太多了。想下面的通知我根本无需要，如果可以的话都做成配置项吧

### ISSUE THREAD

**Issue by gclm** [6dylan6/jdpro#10]
![image](https://user-images.githubusercontent.com/27618687/153528395-7e1ed298-78fc-4e11-bc35-7281eb2caaa1.png)
![image](https://user-images.githubusercontent.com/27618687/153528452-a676da18-6dc1-4198-a7b9-717a78583913.png)

**Comment by gclm** [comment]
正常来说我们需要的通知基本上就下面两类
- 资产通知（里面已经有常见脚本的信息了）
- ck过期通知

**Comment by 6dylan6** [comment]
OK，配置个控制开关

**Comment by 6dylan6** [comment]
使用下面变量。不需通知的标题加入进来就行
 NOTIFY_SKIP_LIST
如果通知标题在此变量里面存在(&隔开),则用屏蔽不发送通知.(PS: Ningjia 作者写的功能，继承过来.)	
例 :  export NOTIFY_SKIP_LIST="临期京豆换喜豆&京东资产统计"

**Comment by gclm** [comment]
拦截无效
![image](https://user-images.githubusercontent.com/27618687/153739190-16c7fbf1-1c80-4179-ae50-9a9447f44070.png)
![image](https://user-images.githubusercontent.com/27618687/153739204-863e0a6c-ba1d-4410-aeef-e632ef43aa60.png)

**Comment by 6dylan6** [comment]
在config.sh 里 export  NOTIFY_SKIP_LIST=""  尝试下

**Comment by gclm** [comment]
> 在config.sh 里 export NOTIFY_SKIP_LIST="" 尝试下

还是不行，醉了。

**Comment by 6dylan6** [comment]
我这边测试可以正常拦截，你的通知文件是我库里的么，sendNotify

**Comment by gclm** [comment]
![image](https://user-images.githubusercontent.com/27618687/154180611-69f26b80-f61b-4e8c-aa93-ddeacf2f0709.png)
![image](https://user-images.githubusercontent.com/27618687/154180662-4e7f33a6-86d4-4f62-a8b0-8c7774d900e1.png)

是的
> 我这边测试可以正常拦截，你的通知文件是我库里的么，sendNotify

**Comment by 6dylan6** [comment]
![image](https://user-images.githubusercontent.com/86815944/154388652-f77932bf-04d6-40ef-b27c-0aa17c7851b0.png)
不是哈，大小不一致

**Comment by 6dylan6** [comment]
你拷贝一份我的到/ql/deps，是这里的覆盖了。

**Comment by gclm** [comment]
> 你拷贝一份我的到/ql/deps，是这里的覆盖了。

好的
