### ISSUE TITLE
WSKEY格式错误

### ISSUE THREAD

**Issue by jerrie610** [6dylan6/jdpro#100]
## 开始执行... 2023-09-21 19:52:28

xxxxxxxxxxxx

--------------------

5700端口检查通过
使用 id 键值
WSKEY格式错误
--------------------

执行完成
--------------------

## 执行结束... 2023-09-21 19:52:29 耗时 1 秒

**Comment by 6dylan6** [comment]
@jerrie610 很清楚了啊，格式检查看看
