### ISSUE TITLE
老版本转换可以但是限制ip,新版本却显示错误(老版本能转换成功),就直接结束,大神可以看下是啥问题吗

### ISSUE THREAD

**Issue by ni11gg** [6dylan6/jdpro#101]
<img width="982" alt="image" src="https://github.com/6dylan6/jdpro/assets/22385605/f81d36bb-246f-4a7d-9ade-9ba77ac1b7f0">
<img width="889" alt="image" src="https://github.com/6dylan6/jdpro/assets/22385605/50f8aa84-4e54-4d20-a2c0-5acd7e1f2f3f">
大神看下是哪里出了问题

**Comment by ni11gg** [comment]
而且它会禁用jd_wskey变量,老版本转换不成功不会禁用这个的·····要重新打开,挺麻烦···

**Comment by 6dylan6** [comment]
@ni11gg 失效了

**Comment by ni11gg** [comment]
但是老版本转换的时候是没有失效的.
<img width="409" alt="image" src="https://github.com/6dylan6/jdpro/assets/22385605/f2030a62-de08-4f5d-8bf5-41f26ffa5b04">

**Comment by 6dylan6** [comment]
@ni11gg 新的我也不清楚，老版本也增加了代理，用老的试试吧
