### ISSUE TITLE
拉库显示成功，但是一个脚本都没有

### ISSUE THREAD

**Issue by jsnj9095** [6dylan6/jdpro#103]
拉库空白，显示成功，但是一个脚本也没拉到，更换代理也一样

**Comment by 6dylan6** [comment]
@jsnj9095 第一次拉吗，不要用代理试试

**Comment by jsnj9095** [comment]
第一次拉，没用代理也一样

**Comment by jsnj9095** [comment]
## 开始执行... 2023-09-28 14:04:54

开始更新仓库：/ql/repo/6dylan6_jdpro

Fetching origin

更新/ql/repo/6dylan6_jdpro成功...


## 执行结束... 2023-09-28 14:04:58  耗时 4 秒

**Comment by 6dylan6** [comment]
@jsnj9095 那你到容器/ql/repo删掉6dylan6_jdpro 在重新拉

**Comment by heyzqq** [comment]
我也是，忽然发现脚本全没了

**Comment by heyzqq** [comment]
删除了重新拉应该可以，我直接升级面板了，重新拉是可以的！
