### ISSUE TITLE
提现 个税

### ISSUE THREAD

**Issue by xu373297464** [6dylan6/jdpro#104]
宿迁兆盈商服科技有限公司 都是这个公司提示的提现
看网上有说被这家公司收了个税的 我们运行的脚本提现 会收取个税么

**Comment by 6dylan6** [comment]
@xu373297464 收税和这公司没关系啊，zf收的啊，正常的，提那点的税忽略不计

**Comment by mS0gxokXEsg5ysJ7J79kzWiqO1fHgFA6ZR8eEls** [comment]
几毛钱收啥税？ >800才收

**Comment by xu373297464** [comment]
累计800么 感觉一年搞下来差不多了
