### ISSUE TITLE
为啥好多脚本显示cookie失效，我刚登陆拿出来的cookie

### ISSUE THREAD

**Issue by zsw-test** [6dylan6/jdpro#106]

**Comment by 6dylan6** [comment]
@zsw-test 可能你ck抓的不对，格式pt_key=xxx;pt_pin=xxx;

**Comment by zsw-test** [comment]
格式是对的，种豆得豆我跑起来了，每日抽豆还有一些其他的脚本都失效了。

**Comment by zsw-test** [comment]
> @zsw-test 可能你ck抓的不对，格式pt_key=xxx;pt_pin=xxx;

格式是对的，种豆得豆我跑起来了，每日抽豆还有一些其他的脚本都失效了。

**Comment by 6dylan6** [comment]
@zsw-test 那不会，，你截图看看报的啥错，不是ck失效

**Comment by zsw-test** [comment]
![image](https://github.com/6dylan6/jdpro/assets/39336897/70bafc08-4638-4867-9003-5bfa4069ad28)
![image](https://github.com/6dylan6/jdpro/assets/39336897/9074a354-a696-4eb6-b4bd-ab935b73a3e2)

**Comment by zsw-test** [comment]
> @zsw-test 那不会，，你截图看看报的啥错，不是ck失效
种豆得豆：
![image](https://github.com/6dylan6/jdpro/assets/39336897/7e09dd31-c52f-4447-9124-d5ec8a269d4b)
每日抽豆：
![image](https://github.com/6dylan6/jdpro/assets/39336897/f8210097-f92f-42e9-b1f0-7f28ec19cdd0)

**Comment by 6dylan6** [comment]
@zsw-test 为什么你的账号名都有双引号pt_pin不对吧，正常是没有双引号

**Comment by zsw-test** [comment]
> @zsw-test 为什么你的账号名都有双引号pt_pin不对吧，正常是没有双引号
这里不要引号是吧
![image](https://github.com/6dylan6/jdpro/assets/39336897/35881571-2baa-4d41-8864-306027f889d5)

**Comment by zsw-test** [comment]
> > @zsw-test 为什么你的账号名都有双引号pt_pin不对吧，正常是没有双引号
> > 这里不要引号是吧
> > ![image](https://user-images.githubusercontent.com/39336897/273551440-35881571-2baa-4d41-8864-306027f889d5.png)

好像是的，我拉了一些其他的脚本KingRan，gys619，有的支持双引号，hhhh

**Comment by 6dylan6** [comment]
@zsw-test 不用引号，你ck不要暴露出来啊，赶紧作废吧

**Comment by zsw-test** [comment]
> @zsw-test 不用引号，你ck不要暴露出来啊，赶紧作废吧

欧克欧克，谢谢提醒
