### ISSUE TITLE
超级无线店铺签到

### ISSUE THREAD

**Issue by Jerry-zx** [6dylan6/jdpro#107]
签到类型3（ cjhy sevenDay ）全部是活动不存在，但是手动进去连接，又是生效的，麻烦看看？
![image](https://github.com/6dylan6/jdpro/assets/84613314/e544904c-8f3e-475b-a8dd-5c5fc6766aa5)

**Comment by 6dylan6** [comment]
@Jerry-zx 你是最新的吗

**Comment by Jerry-zx** [comment]
@6dylan6 是的啊，拉的最新的脚本，还是这样~

**Comment by Jerry-zx** [comment]
> @Jerry-zx 你是最新的吗

大佬，我发现1月的还是这样呢，给你几个店铺id看看噢，bd2a2bfe40ed4fb3801b74aca4f6f8dc,74b00d26ea5b4303bfc91d5ca7e7f9f7

**Comment by 6dylan6** [comment]
@Jerry-zx 什么类型的

**Comment by Jerry-zx** [comment]
> @Jerry-zx 什么类型的
CJHY_SEVENDAY，签到类型3

**Comment by 6dylan6** [comment]
@Jerry-zx 已修复

**Comment by Jerry-zx** [comment]
> @Jerry-zx 已修复

好的，谢谢大佬
