### ISSUE TITLE
 初始化农场数据异常, 请登录京东 app查看农场0元水果功能是否正常,农场初始化数据: {"demotionExp":{"label":"base","hasSetCrowd":false,"bucket":0,"buriedStr":"tsabtest|base64|ZG9uZ2RvbmdmYXJtXzIyMDI2fGJhc2U|tsabtest","running":false,"unionSwitch":0,"expId":"dongdongfarm_22026"},"code":"6","bizCode":null,"todayGotWaterGoalTask":{"canPop":false},"statisticsTimes":null,"enableSign":false,"sysTime":1697011041454,"minSupportAPPVersion":"8.5.4","message":null}

### ISSUE THREAD

**Issue by zhangwenwu** [6dylan6/jdpro#108]
初始化农场数据异常, 请登录京东 app查看农场0元水果功能是否正常,农场初始化数据: {"demotionExp":{"label":"base","hasSetCrowd":false,"bucket":0,"buriedStr":"tsabtest|base64|ZG9uZ2RvbmdmYXJtXzIyMDI2fGJhc2U|tsabtest","running":false,"unionSwitch":0,"expId":"dongdongfarm_22026"},"code":"6","bizCode":null,"todayGotWaterGoalTask":{"canPop":false},"statisticsTimes":null,"enableSign":false,"sysTime":1697011041454,"minSupportAPPVersion":"8.5.4","message":null}

刚安装更新的2.11.3面板 ，重新拉的库， app上正常浇水助力，好几个号都是这样，但是也有号是正常的，这是京东那边的问题还是啥情况~~~

**Comment by 6dylan6** [comment]
@zhangwenwu 本地跑的吗

**Comment by zhangwenwu** [comment]
> @zhangwenwu 本地跑的吗

阿里云上跑的- -不知道是不是这个原因

**Comment by 6dylan6** [comment]
@zhangwenwu 是了，现在不能用云跑，跑不动

**Comment by zhangwenwu** [comment]
好吧，那我本地整个


> @zhangwenwu 是了，现在不能用云跑，跑不动

**Comment by szc-sun** [comment]
ip问题，我现在是30块买个网心云刷成linux服务器跑脚本

**Comment by msccreater** [comment]
解决了没有,本地termux跑的,突然开始出现这个问题

**Comment by Tomy-C** [comment]
> @zhangwenwu 本地跑的吗

本地docker跑也会
