### ISSUE TITLE
怎么今天拉不了库了 而且所有的库都没了

### ISSUE THREAD

**Issue by inatcaidan** [6dylan6/jdpro#110]
怎么今天拉不了库了 而且所有的库都没了

**Comment by 6dylan6** [comment]
@inatcaidan 什么意思，网络有问题吧

**Comment by inatcaidan** [comment]
老大 能加你个qq或者微信吗？我真不知道怎么回事 凌晨突然运行 说把所有的脚本都删除了 然后我拉 显示运行成功 可就一个脚本都没了 我的微信1400044 qq也这个

**Comment by 6dylan6** [comment]
@inatcaidan 进容器把repo目录下的清空在重拉。你老版本青龙吧

**Comment by inatcaidan** [comment]
我是老版本的 我试试先 谢谢老大

**Comment by 6dylan6** [comment]
@inatcaidan 要么换新版青龙，没有这bug
