### ISSUE TITLE
wskey转换脚本异常

### ISSUE THREAD

**Issue by mijjjj** [6dylan6/jdpro#111]
今天起来所有wskey转换都失败了，是不是脚本异常了
![image](https://github.com/6dylan6/jdpro/assets/37797122/3ada59de-5e0f-4203-a2b3-885d7cdc8f0e)

**Comment by 6dylan6** [comment]
@mijjjj 更新了吗

**Comment by mijjjj** [comment]
好吧，国内git又挂了，不好意思
