### ISSUE TITLE
拉库代理更换

### ISSUE THREAD

**Issue by 6dylan6** [6dylan6/jdpro#112]
js.nbplay.site到期不可用，换js.jdpro.site

**Comment by ghost** [comment]
这个也失效了

**Comment by 6dylan6** [comment]
@1444316761 那是你失效了，找别的吧

**Comment by ysf37** [comment]
@1444316761 请问你有找到别的代理吗。这几天用js.jdpro.site拉不下来，之前还可以

**Comment by 6dylan6** [comment]
@ysf37 运行问题修复再拉试试

**Comment by ysf37** [comment]
@6dylan6 
![1698741157857](https://github.com/6dylan6/jdpro/assets/19886505/547ef683-1e13-4dbd-981a-12da91142b27)
还是不行，一直卡这，不知道是不是网络有问题，回家再试试
