### ISSUE TITLE
订阅管理无法拉取，在命令行用ping命令测试是有网的

### ISSUE THREAD

**Issue by ShareCat** [6dylan6/jdpro#114]
## 开始执行... 2023-10-13 11:18:08

开始拉取仓库 6dylan6_jdpro_main 到 /ql/data/repo/6dylan6_jdpro_main

Cloning into '/ql/data/repo/6dylan6_jdpro_main'...

fatal: unable to access 'https://js.nbplay.site/https://github.com/6dylan6/jdpro.git/': Could not resolve host: js.nbplay.site

拉取 6dylan6_jdpro_main 失败，请检查网络...

## 执行结束... 2023-10-13 11:18:09  耗时 1 秒

**Comment by 6dylan6** [comment]
@ShareCat ？issue置顶没有看吗，换代理啊

**Comment by ShareCat** [comment]
可以了，谢谢
