### ISSUE TITLE
telegram发送通知消息失败！！

### ISSUE THREAD

**Issue by shaufo** [6dylan6/jdpro#115]
京东农场 单个帐号可领取的有通知，但是每天任务最后的报表，没有通知，查看日志显示telegram发送通知消息失败！！
![1](https://github.com/6dylan6/jdpro/assets/63514384/4c942bcb-6e5a-4d09-bf2f-59c0f19be353)
![2](https://github.com/6dylan6/jdpro/assets/63514384/a68aba45-0224-4394-b171-ec38c2dfa7cd)

**Comment by mS0gxokXEsg5ysJ7J79kzWiqO1fHgFA6ZR8eEls** [comment]
用PushPlus啊，稳得1P 😝
