### ISSUE TITLE
请问关于提现任务，能不能轮换助理？

### ISSUE THREAD

**Issue by winsphinx** [6dylan6/jdpro#118]
就是 2 3 4 5 给1助力，1 3 4 5 给2助力，等等，目前是只给1号助力，后面的都只有一次机会。  
这个哪里能修改或设置？

**Comment by 6dylan6** [comment]
@winsphinx 每个只有1次机会，345怎么还给2呢

**Comment by winsphinx** [comment]
只能助力一次啊，没手工玩过，真不知道。 😄
