### ISSUE TITLE
大佬 青龙命令拉库 拉不下来怎么办

### ISSUE THREAD

**Issue by linzhaokang-rgb** [6dylan6/jdpro#12]
大佬 青龙命令拉库 拉不下来怎么办

**Comment by linzhaokang-rgb** [comment]
青龙版本v2.15.10

**Comment by linzhaokang-rgb** [comment]
README.md 里面有个参考点开是404

**Comment by 6dylan6** [comment]
@linzhaokang-rgb 第一次拉吗

**Comment by linzhaokang-rgb** [comment]
之前可以拉下来，今天想更新下来着结果拉不下来了0.0



---- 回复的原邮件 ----
| 发件人 | ***@***.***> |
| 日期 | 2023年06月01日 11:41 |
| 收件人 | ***@***.***> |
| 抄送至 | ***@***.***>***@***.***> |
| 主题 | Re: [6dylan6/jdpro] 大佬 青龙命令拉库 拉不下来怎么办 (Issue #12) |

@linzhaokang-rgb 第一次拉吗

**Comment by 6dylan6** [comment]
@linzhaokang-rgb 运行拉库失败修复

**Comment by linzhaokang-rgb** [comment]
把之前得任务都删除啦   运行拉库失败修复 怎么运行大佬

**Comment by 6dylan6** [comment]
@linzhaokang-rgb 那就进容器到/ql/data/repo/下，删除6dy目录在重新拉

**Comment by linzhaokang-rgb** [comment]
好了谢谢大佬 拉库成功了删除后
