### ISSUE TITLE
上下tg佬

### ISSUE THREAD

**Issue by shufflewzc** [6dylan6/jdpro#120]
tg要炸了。。

**Comment by 6dylan6** [comment]
@shufflewzc 没事我梯子先炸

**Comment by shufflewzc** [comment]
加个v shufflewzc



发自我的iPhone


------------------ 原始邮件 ------------------
发件人: 6dylan6 ***@***.***&gt;
发送时间: 2023年10月27日 16:06
收件人: 6dylan6/jdpro ***@***.***&gt;
抄送: Faker ***@***.***&gt;, Mention ***@***.***&gt;
主题: Re: [6dylan6/jdpro] 上下tg佬 (Issue #120)





 
@shufflewzc 没事我梯子先炸
