### ISSUE TITLE
如何关闭拉库,即新增任务和删除任务的通知?

### ISSUE THREAD

**Issue by howdareyo** [6dylan6/jdpro#122]
拉库的通知走的是青龙面板的通道
![图片](https://user-images.githubusercontent.com/91058390/161544574-8f3cc079-46af-495e-a67c-401edb630448.png)
其他脚本的通知走的是
![图片](https://user-images.githubusercontent.com/91058390/161544840-1e2365df-c036-46b6-9ac6-effbd29dde5c.png)
青龙的面板的通知我只是用来通知登录的,每次都被拉库的消息吓一跳
已经配置了禁用通知
![图片](https://user-images.githubusercontent.com/91058390/161545470-ce4ac57c-7efa-4477-88eb-edd88aa4b569.png)
但是无效,依旧通知
![图片](https://user-images.githubusercontent.com/91058390/161545557-b0633c4f-67d1-4a13-bc35-3ca023f9d08e.png)
是我个人的设置问题还是说本身如此?

**Comment by 6dylan6** [comment]
在config.sh里有配置通知吗？

**Comment by howdareyo** [comment]
> 在config.sh里有配置通知吗？

配置了,推送的是那些资产统计东东萌宠之类的消息,是正常推送的
![图片](https://user-images.githubusercontent.com/91058390/161548530-090a9b66-d3c4-4443-b6ea-c7e88cd20e69.png)


但添加脚本删除脚本的通知走的是青龙面板的
![图片](https://user-images.githubusercontent.com/91058390/161548666-6b422b0e-d3a9-44d0-9d57-4a3062a609ad.png)

**Comment by 6dylan6** [comment]
我测试可以屏蔽的
![image](https://user-images.githubusercontent.com/86815944/161551305-cabbcd36-1aff-4e79-972f-d1cfe59ea6fe.png)
你屏蔽变量要写到config里，不要写到环境变量

**Comment by howdareyo** [comment]
> 我测试可以屏蔽的 ![image](https://user-images.githubusercontent.com/86815944/161551305-cabbcd36-1aff-4e79-972f-d1cfe59ea6fe.png) 你屏蔽变量要写到config里，不要写到环境变量

是这样么
![图片](https://user-images.githubusercontent.com/91058390/161553606-6172abd3-d514-416b-8358-e20cf16f1e89.png)
但还是收到
![图片](https://user-images.githubusercontent.com/91058390/161553716-2efc8b7d-74d5-4e42-a999-2290d110c889.png)
我的日志貌似和你不一样
![图片](https://user-images.githubusercontent.com/91058390/161553922-d0d7a05b-cd5e-4552-b5b4-cca26933919b.png)
没有加载sendnotify

**Comment by 6dylan6** [comment]
那你通知文件应该不是我库里的。检查下。deps下面是青龙自带的，会覆盖库里的sendnotify
