### ISSUE TITLE
东东农场助力不全-手动执行好像又可以了，继续测试看看。

### ISSUE THREAD

**Issue by dicksonkoo** [6dylan6/jdpro#123]
日志中有5个助力码，东东农场执行时只能获取到4个。

**Comment by 6dylan6** [comment]
@dicksonkoo 看搜集农场互助码日志有没有收集到

**Comment by dicksonkoo** [comment]
搜集农场互助码日志中是收集到了的。。我再运行两天看看。谢谢回复。。

**Comment by 6dylan6** [comment]
@dicksonkoo 那你更新到最新，前两天的版本是有这个问题

**Comment by dicksonkoo** [comment]
今天还是遇到这个问题，今早00:15定时运行的“搜集农场互助码”，任务日志中显示获取到了农场和新农场的互助码，但是在00:15生成的“ShareCode/Fruit.log”和.ShareCode/Fruit_new.log"中，互助码是空的。。昨天已经删掉了“搜集农场互助码”这个脚本重新同步的，目前该脚本的版本是“update 20231028”。
今早9点37分，我又手动执行了一次“搜集农场互助码”，这次在“ShareCode/Fruit.log”和.ShareCode/Fruit_new.log"中就有互助码了。。昨天也是这个情况，定时获取不到，手动可以获取。请问下一步应该从哪个角度排查？

**Comment by 6dylan6** [comment]
@dicksonkoo 我也这样，在排查

**Comment by itnew1** [comment]
同样问题
