### ISSUE TITLE
农场任务突然基本全挂了，提示初始化农场数据异常，仅剩一个号正常运行

### ISSUE THREAD

**Issue by crazyhonor** [6dylan6/jdpro#125]
提示异常的账号看了下是可以正常进入的，凌晨第一次运行还是正常的，也正常互助过的。会不会是和新版农场有关系呢？

**Comment by 6dylan6** [comment]
@crazyhonor 云服务？

**Comment by crazyhonor** [comment]
nas部署的，青龙面板




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "6dylan6/jdpro"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2023年11月1日(星期三) 下午5:17
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [6dylan6/jdpro] 农场任务突然基本全挂了，提示初始化农场数据异常，仅剩一个号正常运行 (Issue #125)





 
@crazyhonor 云服务？

**Comment by crazyhonor** [comment]
nas部署的，青龙面板

**Comment by 6dylan6** [comment]
@crazyhonor 家宽不会啊，我这正常

**Comment by Tomy-C** [comment]
我也是这个问题 有的号可以 有的号不行

**Comment by zouxiaochun2023** [comment]
我这也是同样的问题，用手机可以，不论新版还是旧版都没问题。但青龙面板跑任务时，就会提示【数据异常】请确认此账号是否开通农场。

**Comment by zouxiaochun2023** [comment]
手动执行一下，又可以了。

**Comment by guhao0803** [comment]
更新青龙面板（使用的话），然后重新拉库，记得设置代理，确保拉库成功，之后重新执行就行了

**Comment by crazyhonor** [comment]
青龙面板直接重新安装、重新拉库后能用了，就是我有个疑问，重新拉库后发现有新农场的任务了，可是我重新部署之前却没有更新这些任务，这是为啥呢？总不至于每次都得重新部署才能接收到这些新任务吧




------------------&nbsp;原始邮件&nbsp;------------------
发件人: ***@***.***&gt;; 
发送时间: 2023年11月3日(星期五) 中午11:28
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; ***@***.***&gt;; 
主题: Re: [6dylan6/jdpro] 农场任务突然基本全挂了，提示初始化农场数据异常，仅剩一个号正常运行 (Issue #125)





 
更新青龙面板（使用的话），然后重新拉库，记得设置代理，确保拉库成功，之后重新执行就行了

**Comment by guhao0803** [comment]
> 青龙面板直接重新安装、重新拉库后能用了，就是我有疑问，重新拉库后发现有新农场的任务了，但是我之前重新安装却没有更新这些任务，这是啥呢？不至于每次都得重新部署才能接收到这些新任务吧
> [……](#)
> ------------------&nbsp;原始邮件&nbsp;------------------ 发件人: ***@***.***&gt;; 发送时间: 2023年11月3日(星期五) 中午11:28 收件人: ***@***.***&gt;; 抄送: ***@***.***&gt;; ***@***.***&gt;; 主题: Re: [6dylan6/jdpro] 农场任务突然基本全挂了，提示初始化农场数据异常，仅剩一个号正常运行 (Issue #125) 更新青龙面板（使用的话），然后重新拉库，记得设置代理，确保拉库成功，之后重新执行就行了 — Reply to this email directly, view it on GitHub, or unsubscribe. You are receiving this because you were mentioned.Message ID: ***@***.***&gt;
之前拉库没有新农场肯定是拉库失败了

**Comment by crazyhonor** [comment]
好吧，不过我之前确实没有设置代理，这次拉库有设代理




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "6dylan6/jdpro"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2023年11月3日(星期五) 中午11:35
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [6dylan6/jdpro] 农场任务突然基本全挂了，提示初始化农场数据异常，仅剩一个号正常运行 (Issue #125)





  
青龙面板直接重新安装、重新拉库后能用了，就是我有疑问，重新拉库后发现有新农场的任务了，但是我之前重新安装却没有更新这些任务，这是啥呢？不至于每次都得重新部署才能接收到这些新任务吧
 ……
 ------------------&nbsp;原始邮件&nbsp;------------------ 发件人: @.&gt;; 发送时间: 2023年11月3日(星期五) 中午11:28 收件人: @.&gt;; 抄送: @.&gt;; @.&gt;; 主题: Re: [6dylan6/jdpro] 农场任务突然基本全挂了，提示初始化农场数据异常，仅剩一个号正常运行 (Issue #125) 更新青龙面板（使用的话），然后重新拉库，记得设置代理，确保拉库成功，之后重新执行就行了 — Reply to this email directly, view it on GitHub, or unsubscribe. You are receiving this because you were mentioned.Message ID: @.***&gt;
 之前拉库没有新农场肯定是拉库失败了
