### ISSUE TITLE
如何指定任务发送消息通知

### ISSUE THREAD

**Issue by zouxiaochun2023** [6dylan6/jdpro#126]
目前使用钉钉机器人，有的任务比如东东农场会发消息通知，其他任务则不会，怎样让指定任务发送消息通知？

**Comment by 6dylan6** [comment]
@984207399 本来就没多少有通知，通知太多不烦死啦

**Comment by zouxiaochun2023** [comment]
@6dylan6 我以为是有配置，哪里没配置好，这个通知是脚本内置的，没有变量能够控制，需要在脚本里面改是吧

**Comment by 6dylan6** [comment]
@984207399 有通知的可以控制关闭，没有通知压根没有通知功能
