### ISSUE TITLE
东东农场任务报错

### ISSUE THREAD

**Issue by yanpengfei-git** [6dylan6/jdpro#127]
试了两个服务，一个是搭建在腾讯云的，一个是本地软路由的docker，执行任务都报这个错误，已经尝试多次拉库，重启服务还不行，配置文件中也添加了RepoFileExtensions="js py sh ts" ，依然不行

<img width="982" alt="image" src="https://github.com/6dylan6/jdpro/assets/37141737/8f85e36c-d756-418e-b9b3-597eaf9933f8">

**Comment by 6dylan6** [comment]
@yanpengfei-git 订阅配置不对，少拉了文件

**Comment by yanpengfei-git** [comment]
> @yanpengfei-git 订阅配置不对，少拉了文件

嗯应该是少填了依赖配置
