### ISSUE TITLE
东东农场助力问题

### ISSUE THREAD

**Issue by penhuowa** [6dylan6/jdpro#127]
我有个车头，打开京东app发现没有助力，检查日志说我未提供sharecode，但是我检查了jd_sharecode.sh的日志发现互助码获取成功，为什么会是这种情况，是我设置的问题吗？需要一些特殊变量？求大佬回复一下。谢谢。

**Comment by 6dylan6** [comment]
看下配置文件里，task_before.sh有没有内容

**Comment by penhuowa** [comment]
这里应该填什么内容，我忘了这件事了，哎

**Comment by penhuowa** [comment]
> 看下配置文件里，task_before.sh有没有内容

这里应该填什么内容，我忘了这件事了，哎

**Comment by 6dylan6** [comment]
运行获取互助任务会自动拷贝过去的。你那不知道啥情况，获取互助码运行有没有报错？
https://github.com/6dylan6/jdpro/blob/main/docker/task_before.sh

**Comment by penhuowa** [comment]
> 运行获取互助任务会自动拷贝过去的。你那不知道啥情况，获取互助码运行有没有报错？
> 
> https://github.com/6dylan6/jdpro/blob/main/docker/task_before.sh

脚本正常获取

**Comment by penhuowa** [comment]
> 运行获取互助任务会自动拷贝过去的。你那不知道啥情况，获取互助码运行有没有报错？
> 
> https://github.com/6dylan6/jdpro/blob/main/docker/task_before.sh

谢谢大佬恢复，四个青龙，只有两个是这种情况，可能我哪一步出了问题吧
