### ISSUE TITLE
wskey过期频繁问题

### ISSUE THREAD

**Issue by J2zl** [6dylan6/jdpro#129]
感觉最近的wskey过期很快阿，兄弟们有没有解决办法

**Comment by xiaobuboy** [comment]
应该是被京东发现了，我用cookie也是很快就掉

**Comment by WYC-2020** [comment]
其实可以在每个任务开始之前 就 加一次 更新key 这样是不是会好一些

**Comment by WYC-2020** [comment]
或者说任务检测到过期 就自动更新key
