### ISSUE TITLE
农场保留水滴值设置无效

### ISSUE THREAD

**Issue by mingchen3398** [6dylan6/jdpro#131]
之前retainWater是100(默认),每天都执行我也不怎么去看,但最近发现剩余的水滴值会小于100
![image](https://github.com/6dylan6/jdpro/assets/32698103/94abeb1d-8d33-47e2-bd57-da174c9798c0)

![image](https://github.com/6dylan6/jdpro/assets/32698103/f50e8ca1-2728-406e-b3d2-9af62a2d3e07)

**Comment by 6dylan6** [comment]
@mingchen3398 更新修复
