### ISSUE TITLE
豆子被换成喜豆 被偷

### ISSUE THREAD

**Issue by mikuandlen** [6dylan6/jdpro#131]
刚刚被偷的,这个库不安全了吗
![Screenshot_2022-04-10-22-00-22-419_com jd pingou](https://user-images.githubusercontent.com/37246484/162623466-cb35dcec-66f8-4350-8997-30216240265e.jpg)

**Comment by 6dylan6** [comment]
目前没有中招，建议：
1、快改密码或作废ck，https://github.com/6dylan6/jdpro/blob/main/backUp/killck.js
2、检查有没有用其他库，其他来历不明的js，手机apk，还有电脑exe程序，这些都有可能
3、关闭免密支付

**Comment by penhuowa** [comment]
瑟瑟发抖

**Comment by mikuandlen** [comment]
> 

感谢!已经把所有js都删除了!

**Comment by 6dylan6** [comment]
据了解，这波被偷的都是用了小组件app，请使用过的赶紧改密码吧

**Comment by penhuowa** [comment]
群里几百个ck，目前没有任何问题，只拉了这一个库，登陆方式是rabbit，青龙拉的官方。

**Comment by Kevin-1273** [comment]
小组件app是啥我的也被偷了

**Comment by mikuandlen** [comment]
> 据了解，这波被偷的都是用了小组件app，请使用过的赶紧改密码吧

请问小组件是什么呀？

**Comment by mikuandlen** [comment]
> 据了解，这波被偷的都是用了小组件app，请使用过的赶紧改密码吧

大佬，我去查了一下小组件是什么，我没有使用过小组件app，可能是别的原因

**Comment by 6dylan6** [comment]
小组件手机APP统称，有获取ck的，有展示京豆曲线的，有青龙app的一些辅助程序。反正手机app和电脑exe不用就对了，还有不明来历的加密js谨慎使用，只能保证库里文件安全，其他的咱也管不着。。别用了其他的东西来说是我库的问题。。

**Comment by 6dylan6** [comment]
还有青龙暴露在公网的，密码要复杂啊，可开二次验证，如果老巢被端了也芭比扣了！
还有其他非jd的js，单独开个容器跑，比如前几天快手破解版，遇到有后门的也会偷同在一窝的jd。。

茹毛需谨慎，被偷回到解放前。
