### ISSUE TITLE
Require stack

### ISSUE THREAD

**Issue by SpinesZws** [6dylan6/jdpro#132]
库拉去成功了，定时任务也自动添加，但所有任务执行时都出现这个错误，请问哪位大神这是什么情况？

🔔天天领红包, 开始!

====================共1个京东账号Cookie=================
===========脚本执行时间：2023/11/03 17:55:54============
>>>>>>>>>>>>6Dy提醒您：有问题先更新不行在反馈>>>>>>>>>>>>>

当前版本：V1.0.0
TG频道：https://t.me/dylan_jdpro

❌ 天天领红包, 失败! 原因: Error: Cannot find module 'psl'
Require stack:
- /ql/data/scripts/node_modules/tough-cookie/lib/pubsuffix-psl.js
- /ql/data/scripts/node_modules/tough-cookie/lib/cookie.js
- /ql/data/scripts/6dylan6_jdpro_main/jd_ttlhb.js!

🔔天天领红包, 结束! 🕛 0.686 秒

**Comment by 6dylan6** [comment]
@SpinesZws 你环境有问题
