### ISSUE TITLE
一运行转6dylan6_jdpro/jd_wskey.py 就退出登录

### ISSUE THREAD

**Issue by 344108150** [6dylan6/jdpro#133]
今天早上发现一运行这个文件就退出登录了，而且如果开了两步验证的话，此脚本就运行报错，提示让检查青龙面板 ，另外我的青龙改端口号了 对外的端口号改成9999了 docker 里的映射端口号还是5700，麻烦请问一下大佬 这是这么原因！

**Comment by 6dylan6** [comment]
端口号没改成功，重启失效
两步验证不行的，wskey获取不到权限。

**Comment by 344108150** [comment]
我之前一直都没问题的 呢，但是上次我升级了一下青龙版本 更新到最新版本了 就出这个问题了。。。我现在好像OK了 没啥问题了 唯一的问题就是跑一遍 这个脚本，我自己要登陆面板的话 就需要重新登录。。。

**Comment by 6dylan6** [comment]
这不太清楚呀，新版青龙可能不能同时登陆了

**Comment by 344108150** [comment]
好的 谢谢
