### ISSUE TITLE
初始化农场数据异常，这是为啥啊

### ISSUE THREAD

**Issue by yuhui0928** [6dylan6/jdpro#134]
## 开始执行... 2023-11-04 09:12:18

🔔东东农场-任务, 开始!
开始获取配置文件

====================共1个京东账号Cookie=================
===========脚本执行时间：2023/11/04 09:12:20============
>>>>>>>>>>>>6Dy提醒您：有问题先更新不行在反馈>>>>>>>>>>>>>

当前版本：2023/10/26 fix
问题建议：https://t.me/dylan_jdpro

环境变量：
export DY_PROXY='api_url' 可使用代理api
export NO_WATER='true' 完全不浇水，浇水任务不做了
export FRUIT_PIN='pin1&pin2' 不浇水的pin，多个&分隔，使用pin控制就不要使用NO_WATER
export DO_TEN_WATER_AGAIN='true' 攒水滴只交10次水，默认不攒水滴
epxort FRUIT_DELAY='1000',设置等待时间(毫秒)，默认请求5次接口等待5秒（5000）

------------------【京东账号1】jd_7158faa8693ef-------------------

初始化农场数据异常, 请登录京东 app查看农场0元水果功能是否正常,农场初始化数据: {"demotionExp":{"label":"base","hasSetCrowd":false,"bucket":0,"buriedStr":"tsabtest|base64|ZG9uZ2RvbmdmYXJtXzIyMDI2fGJhc2U|tsabtest","running":false,"unionSwitch":0,"expId":"dongdongfarm_22026"},"code":"6","bizCode":null,"todayGotWaterGoalTask":{"canPop":false},"statisticsTimes":null,"enableSign":false,"sysTime":1699060342092,"minSupportAPPVersion":"8.5.4","message":null}

==============📣系统通知📣==============
东东农场-任务
【京东账号1🆔】jd_7158faa8693ef
【数据异常】请手动登录app查看此账号农场是否正常

CHRONOCAT 服务的 CHRONOCAT_URL 或 CHRONOCAT_QQ 未设置!!
取消推送

## 执行结束...   耗时 8 秒

**Comment by 6dylan6** [comment]
@yuhui0928 更新最新再试试

**Comment by yuhui0928** [comment]
还是一样
## 开始执行... 2023-11-04 09:19:47


🔔东东农场-任务, 开始!
开始获取配置文件


====================共1个京东账号Cookie=================
===========脚本执行时间：2023/11/04 09:19:48============
>>>>>>>>>>>>6Dy提醒您：有问题先更新不行在反馈>>>>>>>>>>>>>


当前版本：2023/11/04 fix保留100水滴
TG反馈：https://t.me/dylan_jdpro


环境变量：
export DY_PROXY='api_url' 可使用代理api
export NO_WATER='true' 完全不浇水，浇水任务不做了
export FRUIT_PIN='pin1&pin2' 不浇水的pin，多个&分隔，使用pin控制就不要使用NO_WATER
export DO_TEN_WATER_AGAIN='true' 攒水滴只交10次水，默认不攒水滴
epxort FRUIT_DELAY='1000',设置等待时间(毫秒)，默认请求5次接口等待5秒（5000）


------------------【京东账号1】jd_7158faa8693ef-------------------

初始化农场数据异常, 请登录京东 app查看农场0元水果功能是否正常,农场初始化数据: {"demotionExp":{"label":"base","hasSetCrowd":false,"bucket":0,"buriedStr":"tsabtest|base64|ZG9uZ2RvbmdmYXJtXzIyMDI2fGJhc2U|tsabtest","running":false,"unionSwitch":0,"expId":"dongdongfarm_22026"},"code":"6","bizCode":null,"todayGotWaterGoalTask":{"canPop":false},"statisticsTimes":null,"enableSign":false,"sysTime":1699060790472,"minSupportAPPVersion":"8.5.4","message":null}


==============📣系统通知📣==============
东东农场-任务
【京东账号1🆔】jd_7158faa8693ef
【数据异常】请手动登录app查看此账号农场是否正常


CHRONOCAT 服务的 CHRONOCAT_URL 或 CHRONOCAT_QQ 未设置!!
取消推送

## 执行结束...   耗时 7 秒

**Comment by 6dylan6** [comment]
@yuhui0928 那就确实不行，你手动进看看，云服务器不能跑

**Comment by yuhui0928** [comment]
难道要在自己电脑上跑嘛

**Comment by 6dylan6** [comment]
@yuhui0928 是，官方限制的

**Comment by 6dylan6** [comment]
@yuhui0928 本地网络就行

**Comment by yuhui0928** [comment]
好的吧
