### ISSUE TITLE
大佬  有更简单的小白教程吗

### ISSUE THREAD

**Issue by gujiwuqing** [6dylan6/jdpro#134]
大佬 有更简单的小白教程吗？因为有注意一般这些都需要cookie 不知道这个应该在哪弄 在哪设置

**Comment by 6dylan6** [comment]
青龙搭好了吗，只是不知道怎么获取cookie？

**Comment by Fliangui** [comment]
这个最简单了  搭好青龙 拉库就行了  把cookie放进环境变量,变量名字JD_COOKIE, pt_pin=*****;pt_key=******;格式.别的啥ninja什么都不用 自用足够了.

**Comment by Fliangui** [comment]
cookie获取 百度一下 这个百度上很多 也很简单 具体一句话说出来又不太容易

**Comment by Fliangui** [comment]
就是在环境变量里填写,一条一个 ,跟我图片里这样. 注意 有分号 ;

**Comment by gujiwuqing** [comment]
> 青龙搭好了吗，只是不知道怎么获取cookie？

是的

**Comment by gujiwuqing** [comment]
> 环境变量里JD_COOKIE，一条一个

好的 我看看

**Comment by gujiwuqing** [comment]
> 就是在环境变量里填写,一条一个 ,跟我图片里这样. 注意 有分号 ;

好的 大佬 我看看

**Comment by gujiwuqing** [comment]
<img width="1406" alt="image" src="https://user-images.githubusercontent.com/44566835/162928330-04c304b4-0c0e-46ce-b375-23d2feeba660.png">
<img width="1353" alt="image" src="https://user-images.githubusercontent.com/44566835/162928370-d258be13-56ae-4fee-b179-15cbf354d723.png">
大佬们 是这样子嘛
