### ISSUE TITLE
CK失效后自动运行wskey任务的情况

### ISSUE THREAD

**Issue by Fliangui** [6dylan6/jdpro#135]
用了@ccwav大大里那个ck失效通知后拉起指定任务的环境变量. 确实可以在CK失效后自动运行wskey任务,就是发现多个ck失效后  wskey运行的有点频繁,例如我库了有10个ck和wskey.有6个ck失效了  就会一起运行6个wskey任务,后台日志看着wskey运行记录很多次 ,这个频繁wskey检测对账号没有啥影响吧.那能不能是哪个ck失效了 指定wskey就运行检测和转换指定的ck呢?现在wskey转换的ck有效期太短了.有时候半天就失效了.
![222](https://user-images.githubusercontent.com/62930445/162899960-919e369f-ce4e-4d10-bcfb-be4e24590085.png)
![3333](https://user-images.githubusercontent.com/62930445/162899964-fd6d43eb-eee9-4f27-a12b-fd209a02a595.png)

**Comment by Fliangui** [comment]
有没有简单方便的ninja面板 来手机验证码提取ck然后自动替换环境变量里的ck,我看到网上有别人发这类的图片,就是不知道源码在那 怎么部署,

**Comment by 6dylan6** [comment]
不会同时失效吧，你意思是转换时候6个同时开始转换吗

**Comment by Fliangui** [comment]
> 不会同时失效吧，你的英文是转换的时候6个同时开始转换吗

是的,会同时运行多个wskey任务.这个我去Zy143L大大的问题集了 看了他们讨论 有这个问题,还有网友给了解决办法 ,但是我不太懂,嘿嘿 .大佬帮忙看看呗.

**Comment by Fliangui** [comment]
> 我看下，基本没用到wskey，所以没碰到。

恩,谢谢大佬,我这自己虚拟机装的青龙,只拉了你的这个库,没装别的乱七八糟的脚本,用wskey也放心和方便,几个朋友在我这挂着了,要不总要验证码去提出cookie也麻烦,嘿嘿

**Comment by Fliangui** [comment]
> > 用的环境变量NOTIFY_CKTASK = 6dylan6_jdpro/jd_wskey.py 调用的wskey自动执行 !
> 在源码里没看到这个环境变量啊

、通知支持一对一推送和显示备注，详细用法参考[@ccwav](https://github.com/ccwav/QLScript2),,嘿嘿 我就是在这里找到的  目前ccwav大佬把QLScript2 这个库删除了  ,看不到了

**Comment by 6dylan6** [comment]
> > 用的环境变量NOTIFY_CKTASK = 6dylan6_jdpro/jd_wskey.py 调用的wskey自动执行 ![111](https://user-images.githubusercontent.com/62930445/162906963-a17e7088-b9b1-4eb9-8673-548807413d1a.png)
> 
> 在源码里没看到这个环境变量啊

有的,sendnotify里，作用是捕获通知关键字来执行你定义的脚本NOTIFY_CKTASK

**Comment by 6dylan6** [comment]
> > > > 用的环境变量NOTIFY_CKTASK = 6dylan6_jdpro/jd_wskey.py 调用的wskey自动执行 ![111](https://user-images.githubusercontent.com/62930445/162906963-a17e7088-b9b1-4eb9-8673-548807413d1a.png)
> > > 
> > > 
> > > 在源码里没看到这个环境变量啊
> > 
> > 
> > 有的,sendnotify里，作用是捕获通知关键字来执行你定义的脚本NOTIFY_CKTASK
> 
> 对对对 我找到了 在sendNotify.js文件里 但是我发现我本地没有这个文件 但我就是用的首页的那个拉库地址啊 是我哪里弄的不对吗？

你是不是没有获取互助码的任务，这个会防止sendnoty被青龙自带的覆盖

**Comment by 344108150** [comment]
> > > > > 用的环境变量NOTIFY_CKTASK = 6dylan6_jdpro/jd_wskey.py 调用的wskey自动执行 ![111](https://user-images.githubusercontent.com/62930445/162906963-a17e7088-b9b1-4eb9-8673-548807413d1a.png)
> > > > 
> > > > 
> > > > 在源码里没看到这个环境变量啊
> > > 
> > > 
> > > 有的,sendnotify里，作用是捕获通知关键字来执行你定义的脚本NOTIFY_CKTASK
> > 
> > 
> > 对对对 我找到了 在sendNotify.js文件里 但是我发现我本地没有这个文件 但我就是用的首页的那个拉库地址啊 是我哪里弄的不对吗？
> 
> 你是不是没有获取互助码的任务，这个会防止sendnoty被青龙自带的覆盖

![image](https://user-images.githubusercontent.com/90685197/162920155-8b3922da-afa4-47bb-900b-13fab16e767d.png)
这个任务吗？有啊

**Comment by 6dylan6** [comment]
什么版本青龙，这个会拷贝库里的sendnoti文件的

**Comment by 344108150** [comment]
> 什么版本青龙，这个会拷贝库里的sendnoti文件的

V2.12.1   但是我没找到sendNotify.js 这个脚本

**Comment by 6dylan6** [comment]
> > 什么版本青龙，这个会拷贝库里的sendnoti文件的
> 
> V2.12.1 但是我没找到sendNotify.js 这个脚本

那会在这个目录的/ql/data/scripts/6dylan6_jdpro/sendNotify.js

**Comment by Fliangui** [comment]
> > 什么版本青龙，这个会拷贝库里的sendnoti文件的
> 
> V2.12.1 但是我没找到sendNotify.js 这个脚本

我不小心升级到2.12.0的青龙后  ,青龙总是覆盖sendnotify.js文件,备注和通知总是不对 .我就把ql/deps文件夹里的sendnotify文件替换成了.

**Comment by Fliangui** [comment]
你看看ql/deps文件里有没有这个文件

**Comment by 344108150** [comment]
> > > 什么版本青龙，这个会拷贝库里的sendnoti文件的
> > 
> > 
> > V2.12.1 但是我没找到sendNotify.js 这个脚本
> 
> 那会在这个目录的/ql/data/scripts/6dylan6_jdpro/sendNotify.js

恩恩 这个目录里面有 面板里的定时任务里不会出现是吧

**Comment by Fliangui** [comment]
> > > > 什么版本青龙，这个会拷贝库里的sendnoti文件的
> > > 
> > > 
> > > V2.12.1 但是我没找到sendNotify.js 这个脚本
> > 
> > 
> > 那会在这个目录的/ql/data/scripts/6dylan6_jdpro/sendNotify.js
> 
> 恩恩 这个目录里面有 面板里的定时任务里不会出现是吧

这个就是通知的时候会调用到它,而不需要进行定时任务来执行它

**Comment by 344108150** [comment]
> > > 你看看ql/deps文件里有没有这个文件,容器外是ql/deps 容器内是ql/data/deps 文件夹
> > 
> > 
> > ![image](https://user-images.githubusercontent.com/90685197/162923005-fdac720c-491b-4082-ac02-d3ad4c221bf9.png) 我容器外没有这个文件夹 那就说明没问题咯。。。
> 
> 只要那会在这个目录的/ql/data/scripts/6dylan6_jdpro/sendNotify.js这个有就行 如果外边有 就替换或者删除了

好的 谢谢 我自己去调试一下 看看是不是用的这个文件

**Comment by Fliangui** [comment]
其实我也不太懂,哈哈 .还是多搞搞试试看.

**Comment by 344108150** [comment]
> > > 什么版本青龙，这个会拷贝库里的sendnoti文件的
> > 
> > 
> > V2.12.1 但是我没找到sendNotify.js 这个脚本
> 
> 那会在这个目录的/ql/data/scripts/6dylan6_jdpro/sendNotify.js

老大 我拉的 sendNotify.js 和库里的 文件不一样 我的总共才930行 ，这是什么原因啊
![image](https://user-images.githubusercontent.com/90685197/162929097-82129e39-1502-4fab-b821-f6c645721a8d.png)

**Comment by Fliangui** [comment]
> > > > 什么版本青龙，这个会拷贝库里的sendnoti文件的
> > > 
> > > 
> > > V2.12.1 但是我没找到sendNotify.js 这个脚本
> > 
> > 
> > 那会在这个目录的/ql/data/scripts/6dylan6_jdpro/sendNotify.js
> 
> 老大 我拉的 sendNotify.js 和库里的 文件不一样 我的总共才930行 ，这是什么原因啊 ![image](https://user-images.githubusercontent.com/90685197/162929097-82129e39-1502-4fab-b821-f6c645721a8d.png)

参考我上边说的那个  把ql/data/deps 文件夹里的删除  把你看到的的sendnotify都删除了 重新拉一次

**Comment by Fliangui** [comment]
再不行 就把/ql/data/scripts/6dylan6_jdpro/sendNotify.js文件复制到ql/data/deps里 再重启docker.这个文件应该有120kb  两千多行的

**Comment by Fliangui** [comment]
![image](https://user-images.githubusercontent.com/62930445/162931589-eb3c7288-d076-4264-9085-69ea8ba8f730.png)

**Comment by 344108150** [comment]
> 我一开始也是烦恼这个总被青龙的sendnotify文件替换,后来慢慢找到了解决办法 .新版本的青龙就是这样,每次重启都会替换覆盖sendnotify文件.你把源文件先替换了就行了

好嘞  谢了

**Comment by 344108150** [comment]
> 我一开始也是烦恼这个总被青龙的sendnotify文件替换,后来慢慢找到了解决办法 .新版本的青龙就是这样,每次重启都会替换覆盖sendnotify文件.你把源文件先替换了就行了

最后打扰一下 请叫一下  data 里面 scripts deps 以及 repo 这几个文件夹 分别起什么作用啊  我目前看到的  scripts 和deps 里的都只有930行 只有 repo 里面的是2000多行的 ，。。。

**Comment by 6dylan6** [comment]
> > 我一开始也是烦恼这个总被青龙的sendnotify文件替换,后来慢慢找到了解决办法 .新版本的青龙就是这样,每次重启都会替换覆盖sendnotify文件.你把源文件先替换了就行了
> 
> 最后打扰一下 请叫一下 data 里面 scripts deps 以及 repo 这几个文件夹 分别起什么作用啊 我目前看到的 scripts 和deps 里的都只有930行 只有 repo 里面的是2000多行的 ，。。。

scripts就是添加的运行任务需要的文件的目录，所以确保这个目录的sendnotify对就行
deps是放些依赖文件，青龙默认放了自带的通知文件，只要ql repo拉库就会做一次拷贝到scripts，所以把这替换了或删掉可以解决的原因！
repo就是库的保存目录，scripts是从这拷贝所需脚本

**Comment by 344108150** [comment]
> > > 我一开始也是烦恼这个总被青龙的sendnotify文件替换,后来慢慢找到了解决办法 .新版本的青龙就是这样,每次重启都会替换覆盖sendnotify文件.你把源文件先替换了就行了
> > 
> > 
> > 最后打扰一下 请叫一下 data 里面 scripts deps 以及 repo 这几个文件夹 分别起什么作用啊 我目前看到的 scripts 和deps 里的都只有930行 只有 repo 里面的是2000多行的 ，。。。
> 
> scripts就是添加的运行任务需要的文件的目录，所以确保这个目录的sendnotify对就行 deps是放些依赖文件，青龙默认放了自带的通知文件，只要ql repo拉库就会做一次拷贝到scripts，所以把这替换了或删掉可以解决的原因！ repo就是库的保存目录，scripts是从这拷贝所需脚本

谢谢 谢谢 明白了

**Comment by Fliangui** [comment]
我的这个问题也临时解决了.我把[https://github.com/Zy143L/wskey/issues/91](url)这里的添加到sendnotify.js中了.目前测试可以用,ck失效了会拉起wskey.py一次,特意把多个ck修改成失效的,测试也是短时间内只运行了一次wskey.py任务.
![6666](https://user-images.githubusercontent.com/62930445/162962363-bed99b02-fd78-4394-8d21-d2c384f30421.png)
