### ISSUE TITLE
提个有关cookie的建议

### ISSUE THREAD

**Issue by deadnessking** [6dylan6/jdpro#136]
每次更新库都会把jdCookie.js里填的cookie清空，能不能把读取cookie数据改成一个环境变量或者另行生成一个更新的时候不会变的设置文件，这样会更方便。

**Comment by 344108150** [comment]
cookie 本身就可以设置环境变量啊

**Comment by deadnessking** [comment]
> cookie 本身就可以设置环境变量啊

好吧，研究了一下还真已经有了，是我孤陋寡闻

**Comment by Jack800109** [comment]
问一下大佬，怎么弄呢
