### ISSUE TITLE
jdck 这个库咋没了

### ISSUE THREAD

**Issue by lamking** [6dylan6/jdpro#137]

**Comment by 6dylan6** [comment]
我昨天测试不可用了，你还能用？

**Comment by lamking** [comment]
有些账号可以 有些不行  我也不知道为啥

**Comment by lamking** [comment]
顺便问问 今天我全部账号都掉了 ...你们有遇到么

**Comment by 6dylan6** [comment]
有，都掉一波，重新登录吧

**Comment by gujiwuqing** [comment]
> 我昨天测试不可用了，你还能用？
大佬 这个脚本是一天yi一运行吗
<img width="1344" alt="image" src="https://user-images.githubusercontent.com/44566835/162968047-28f12039-3dad-4db0-8d2e-0fcfa1f02fab.png">

**Comment by 6dylan6** [comment]
> > 我昨天测试不可用了，你还能用？
> > 大佬 这个脚本是一天yi一运行吗
> 
> <img alt="image" width="1344" src="https://user-images.githubusercontent.com/44566835/162968047-28f12039-3dad-4db0-8d2e-0fcfa1f02fab.png">

8-23点每隔四小时运行一次

**Comment by gujiwuqing** [comment]
> > > 我昨天测试不可用了，你还能用？
> > > 大佬 这个脚本是一天yi一运行吗
> > 
> > 
> > <img alt="image" width="1344" src="https://user-images.githubusercontent.com/44566835/162968047-28f12039-3dad-4db0-8d2e-0fcfa1f02fab.png">
> 
> 8-23点每隔四小时运行一次

有注意看 大佬 你好像又更新了 缩短了运行的次数是吗

**Comment by 6dylan6** [comment]
> > > > 我昨天测试不可用了，你还能用？
> > > > 大佬 这个脚本是一天yi一运行吗
> > > 
> > > 
> > > <img alt="image" width="1344" src="https://user-images.githubusercontent.com/44566835/162968047-28f12039-3dad-4db0-8d2e-0fcfa1f02fab.png">
> > 
> > 
> > 8-23点每隔四小时运行一次
> 
> 有注意看 大佬 你好像又更新了 缩短了运行的次数是吗

嗯，调整为2小时执行一次

**Comment by lamking** [comment]
> 有，都掉一波，重新登录吧

大佬 可以把jdck的源码放出来吗 想学习一下实现原理

**Comment by 6dylan6** [comment]
> > 有，都掉一波，重新登录吧
> 
> 大佬 可以把jdck的源码放出来吗 想学习一下实现原理

开了

**Comment by lamking** [comment]
> > > 有，都掉一波，重新登录吧
> > 
> > 
> > 大佬 可以把jdck的源码放出来吗 想学习一下实现原理
> 
> 开了

ok 感谢
