### ISSUE TITLE
京东狂欢城  末尾的cookie基本没豆子

### ISSUE THREAD

**Issue by XinBaoCode** [6dylan6/jdpro#138]
京东狂欢城 第一个cookie得到豆子多，之后的cookie逐渐减少，为什么哈，该怎么解决呢？

**Comment by 6dylan6** [comment]
并发

**Comment by Fliangui** [comment]
1、涉及兑换或需要抢的可以配置任务并发，就是全部一起跑。

并发配置方法：

在任务后面加conc JD_COOKIE

如 task XXXXX.js conc JD_COOKIE

**Comment by XinBaoCode** [comment]
感谢！



---原始邮件---
发件人: ***@***.***&gt;
发送时间: 2022年4月13日(周三) 晚上7:08
收件人: ***@***.***&gt;;
抄送: ***@***.******@***.***&gt;;
主题: Re: [6dylan6/jdpro] 京东狂欢城  末尾的cookie基本没豆子 (Issue #138)




 
1、涉及兑换或需要抢的可以配置任务并发，就是全部一起跑。
 
并发配置方法：
 
在任务后面加conc JD_COOKIE
 
如 task XXXXX.js conc JD_COOKIE
