### ISSUE TITLE
11月4日版本的老版农场，设置了攒水滴模式，基本的10次浇水也不浇了

### ISSUE THREAD

**Issue by hnustcom** [6dylan6/jdpro#140]
![360截图16560316819196](https://github.com/6dylan6/jdpro/assets/22142500/f53805df-affc-4eae-845a-a0009fa2fe1a)

11月4日版本更新的老版农场，设置开启了攒水滴模式，基本的10次浇水也不浇了

**Comment by 6dylan6** [comment]
@hnustcom 更新修复
