### ISSUE TITLE
能否加个价格保护脚本

### ISSUE THREAD

**Issue by lunati-wei** [6dylan6/jdpro#141]
老大，有没有价格保护脚本，一天运行1/2次就可以吧，多谢多谢

**Comment by 6dylan6** [comment]
有的啊，拉库

**Comment by lunati-wei** [comment]
ql repo https://github.com/6dylan6/jdpro.git "jd_|jx_|jddj_" "backUp" "^jd[^_]|USER|JD|function|sendNotify"

**Comment by lunati-wei** [comment]
ql repo https://github.com/6dylan6/jdpro.git "jd_|jx_|jddj_" "backUp" "^jd[^_]|USER|JD|function|sendNotify"
我拉的上面的库，大佬，价格保护是哪个文件呢？

**Comment by 6dylan6** [comment]
在任务搜京东保价，jd_price.js。

**Comment by lunati-wei** [comment]
多谢，找到啦

看了下日志，有的成功，有的失败，这是什么原因？

🔔京东保价, 开始!

====================共1个京东账号Cookie=================

============脚本执行时间：2022/4/15 14:13:36=============

>>>>>>>>>>>>>>6Dylan6 提示：任务正常运行中>>>>>>>>>>>>>>>


******开始【京东账号1】wvg*********

保价失败：没有可保价的订单

==============📣系统通知📣==============
京东保价
【京东账号1】kdl


🔔京东保价, 结束! 🕛 38.886 秒


🔔京东保价, 开始!

====================共1个京东账号Cookie=================

============脚本执行时间：2022/4/15 14:13:36=============

>>>>>>>>>>>>>>6Dylan6 提示：任务正常运行中>>>>>>>>>>>>>>>


******开始【京东账号1】kdl*********


**❌ 京东保价, 失败! 原因: TypeError: Cannot read property 'getToken' of undefined!**


🔔京东保价, 结束! 🕛 12.104 秒

**Comment by lunati-wei** [comment]
我看了下您的说明，我也设置成并发啦，不知道哪里有问题，多谢

**Comment by 6dylan6** [comment]
检查账号ck正常吗。看看历史日志是每次都这个ck失败吗

**Comment by lunati-wei** [comment]
ck是正常的，我把那个并发改成顺序，可以跑过，就是顺序有点乱，先这样吧，能用就行

**Comment by gdracula** [comment]
> TypeError: Cannot read property 'getToken' of undefined!

您好，我也碰到了 TypeError: Cannot read property 'getToken' of undefined! 的问题（之前刚装好jsdom依赖），请问怎么改并发啊？
