### ISSUE TITLE
互助码获取脚本最新版青龙无效

### ISSUE THREAD

**Issue by lichen780** [6dylan6/jdpro#143]
![819ceb56e50b0ef6fe2a660c6ae68d9e](https://github.com/6dylan6/jdpro/assets/39560327/6feec236-9212-48bf-8d1b-acdb21d3d6ec)
最新版青龙的日志 最后都有多加了一些文字 jd_sharecode_任务ID，需要怎么修改脚本适配？

**Comment by 6dylan6** [comment]
@lichen780 我测试可以啊。你什么版本青龙

**Comment by lichen780** [comment]
> @lichen780我测试可以啊。青龙你什么版本

2.16.3

**Comment by 6dylan6** [comment]
@lichen780 你搜集不到？

**Comment by lichen780** [comment]
> @lichen780您库存不到？

获取不到互助码，  日志里有互助码

**Comment by 6dylan6** [comment]
@lichen780 农场助力运行的日志截图，开头部分

**Comment by lichen780** [comment]
> @lichen780 农场助力运行的日志截图，开头部分

![image](https://github.com/6dylan6/jdpro/assets/39560327/9336b52e-de86-468b-98c6-569374c955d4)

**Comment by 6dylan6** [comment]
@lichen780 已修复，更新

**Comment by lichen780** [comment]
自建的集合的一个库如何修改适配脚本，是只修改方框内的吗
![image](https://github.com/6dylan6/jdpro/assets/39560327/67a29b40-796a-4d3a-8004-6551aa1ab0c4)

**Comment by 6dylan6** [comment]
@lichen780 应该行

**Comment by lichen780** [comment]
> @lichen780 应该行

修改这四个地方还是无效
