### ISSUE TITLE
新旧东东农场某个账号初始化农场数据异常

### ISSUE THREAD

**Issue by Y-Moriarty** [6dylan6/jdpro#144]
请问下，我这边挂了几个账号，其中一两个账号初始化农场数据异常，但其他的账号又能正常运行是什么问题？是黑号了吗？

新农场任务
## 开始执行... 2023-11-07 06:15:00

任务随机延迟 1 秒，配置文件参数 RandomDelay 置空可取消延迟 

🔔新农场任务, 开始!
开始获取配置文件

====================共7个京东账号Cookie=================
===========脚本执行时间：2023/11/07 06:15:04============
>>>>>>>>>>>>6Dy提醒您：有问题先更新不行在反馈>>>>>>>>>>>>>

当前版本：2023/11/05 fix
问题建议：https://t.me/dylan_jdpro

环境变量：
export DY_PROXY='api_url' 可使用代理API
export FRUIT_ID='UID' 未种植可设置作物UID来种

------------------【京东账号1】jd_7bc7641f59a0e-------------------

初始化农场数据异常, 请登录京东app查看农场功能是否正常,农场初始化数据: {"code":0,"data":{"bizCode":-1001,"bizMsg":"活动太火爆了， 请稍后再试~","result":{"bable":"https://pro.m.jd.com/mall/active/3iXU1kvcZaGz6Xf9L3cJ9aCS6ShN/index.html?has_native=0&jwebprog=0&hybrid_err_view=1&ad_od=1&babelChannel=ttt42","desc":"去逛逛"},"success":false},"msg":"调用成功"}

------------------------------------------------------------------------------------------------------------------------------------------------

二、东东农场

当前版本：2023/11/04 fix保留100水滴
TG反馈：https://t.me/dylan_jdpro

环境变量：
export DY_PROXY='api_url' 可使用代理api
export NO_WATER='true' 完全不浇水，浇水任务不做了
export FRUIT_PIN='pin1&pin2' 不浇水的pin，多个&分隔，使用pin控制就不要使用NO_WATER
export DO_TEN_WATER_AGAIN='true' 攒水滴只交10次水，默认不攒水滴
epxort FRUIT_DELAY='1000',设置等待时间(毫秒)，默认请求5次接口等待5秒（5000）

------------------【京东账号1】jd_7bc7641f59a0e-------------------

初始化农场数据异常, 请登录京东 app查看农场0元水果功能是否正常,农场初始化数据: {"demotionExp":{"label":"base","hasSetCrowd":false,"bucket":0,"buriedStr":"tsabtest|base64|ZG9uZ2RvbmdmYXJtXzIyMDI2fGJhc2U|tsabtest","running":false,"unionSwitch":0,"expId":"dongdongfarm_22026"},"code":"6","bizCode":null,"todayGotWaterGoalTask":{"canPop":false},"statisticsTimes":null,"enableSign":false,"sysTime":1699318040602,"minSupportAPPVersion":"8.5.4","message":null}

**Comment by 6dylan6** [comment]
@Y-Moriarty 手动进app看看正常吗

**Comment by Y-Moriarty** [comment]
> @Y-Moriarty 手动进app看看正常吗

我进app手动浇水做任务都正常
![1](https://github.com/6dylan6/jdpro/assets/71491039/9523ff70-e98a-4653-988a-64766834d74e)

**Comment by hackgsl** [comment]
初始化农场数据异常, 请登录京东 app查看农场0元水果功能是否正常,农场初始化数据: {"demotionExp":{"label":"base","hasSetCrowd":false,"bucket":0,"buriedStr":"tsabtest|base64|ZG9uZ1RvbmdmYXJtXzIyMDI2fGJhc2U|tsabtest","running":false,"unionSwitch":0,"expId":"dongdongfarm_22026"},"code":"6","bizCode":null,"todayGotWaterGoalTask":{"canPop":false},"statisticsTimes":null,"enableSign":false,"sysTime":1699537131534,"minSupportAPPVersion":"8.5.4","message":null}

我的也是一样，备份出来后换到别的虚拟机上就没事。在公司电脑上重做的虚拟机就是不管用，个别账号一直报这个错。

**Comment by Y-Moriarty** [comment]
难受了 只能一直重抓ck

**Comment by yu6zhou** [comment]
@6dylan6 遇到同样的问题，5个号有2号异常，是领太多的原因？
