### ISSUE TITLE
黑号的ck就不失效了?能否从脚本上找找原因应付三天失效？

### ISSUE THREAD

**Issue by xfchu1988** [6dylan6/jdpro#145]
我的号最近观察到两个黑号（综合分19分）ck就不失效，一个号本来三天就失效，最近被黑了，已经6天不失效了，当然还有新号一直没有失效。其他两个老号不知什么原因一直没有失效过。说明跑某些脚本ck不一定就会失效，但是跑不了，比如黑号了，ck就不会三天失效。看能否给大佬们提供一个思路对方ck三天就失效的问题

**Comment by raincoast** [comment]
我看我黑号就只有农场黑了没跑，一周了都不掉，剩下跑农场没黑的3天一掉

**Comment by 6dylan6** [comment]
@raincoast 那再试试都不跑农场

**Comment by raincoast** [comment]
> @raincoast 那再试试都不跑农场
嗯嗯，我试试

**Comment by xfchu1988** [comment]
老农场不跑，或者老农场黑了，确实ck三天不失效了，是不是这个脚本哪点触发到京东的安全规则了呢？

**Comment by 6dylan6** [comment]
@xfchu1988 你在看几天，我跑着农场也有不过期

**Comment by xfchu1988** [comment]
@6dylan6 是的，个别号，比如说新注册的号，跑所有脚本都不过期。我再观察几天，设定多些老号不跑老农场试试

**Comment by J2zl** [comment]
不跑新农场的话就没事 我感觉是新农场的问题

**Comment by 6dylan6** [comment]
@J2zl 那还是不跑新农场了，没啥好东西

**Comment by J2zl** [comment]
> @J2zl 那还是不跑新农场了，没啥好东西

我已经禁用掉了 新农场我刚跑出来 居然还是指定商品的优惠券

**Comment by xiaobuboy** [comment]
我现在不跑新农场，跑的老农场，结果2填就被强退了
