### ISSUE TITLE
这是那个“头文字JJJ”的报错请问如何解决

### ISSUE THREAD

**Issue by Ye-Guxuan** [6dylan6/jdpro#146]
![e62f9a7c3c2c117c75b0622ca24d342](https://github.com/6dylan6/jdpro/assets/102740701/aad51c3a-67b2-44ff-bc9a-95f03ad78344)

**Comment by 6dylan6** [comment]
@Ye-Guxuan 你这图搞错吧了

**Comment by Ye-Guxuan** [comment]
> @Ye-Guxuan 你这图搞错吧了

刚才搞错了

**Comment by 6dylan6** [comment]
@Ye-Guxuan ip限制了，等一会在运行

**Comment by tpc188** [comment]
这个活动是不是结束了？
