### ISSUE TITLE
领现金运行不了

### ISSUE THREAD

**Issue by Pollo3470** [6dylan6/jdpro#146]
目测是多了一个获取pandatoken的步骤导致的
![6534C674-A147-4060-966B-3AEB7FC43453](https://user-images.githubusercontent.com/90445326/163692411-cba40897-02f8-40d8-b3e0-a37897712a44.jpeg)

**Comment by 6dylan6** [comment]
有TG的去https://t.me/pang_da_bot获取token，然后export PandaToken='你获取的token'

**Comment by Pollo3470** [comment]
现在填了token，但还是报错
![EEE827F9-35EE-436F-B756-46CAB1BDFAEA](https://user-images.githubusercontent.com/90445326/164296554-4f307061-9b02-4bb8-bc51-7dfbc8d4c8d4.jpeg)

**Comment by Pollo3470** [comment]
应该是版本问题，我这边换最新版后正常了，感谢解答
