### ISSUE TITLE
重复脚本无法正常使用

### ISSUE THREAD

**Issue by JMFANS** [6dylan6/jdpro#148]
![Screenshot_2022-04-19-09-30-43-844-edit_com android chrome](https://user-images.githubusercontent.com/43535104/163902551-df593016-8a9d-4286-874f-9b02b76ecaf0.jpg)
已添加变量

**Comment by 6dylan6** [comment]
正常呀，哪里有问题？

**Comment by JMFANS** [comment]
好像查不出来重复的，不知道为什么

**Comment by 6dylan6** [comment]
同名才算重复，有同名的吗

**Comment by JMFANS** [comment]
无语了，重启一下docker就好了😂

**Comment by JMFANS** [comment]
![Screenshot_2022-04-20-01-43-54-690-edit_com android chrome](https://user-images.githubusercontent.com/43535104/164064176-1822ca19-40a4-430f-9dcf-44bdb9ef05bb.jpg)
![IMG_20220420_014414](https://user-images.githubusercontent.com/43535104/164064193-55938907-dbb2-49d0-8df0-75e9f6e3772d.jpg)
问题重复出现，青龙2.12.1

**Comment by 6dylan6** [comment]
> ![Screenshot_2022-04-20-01-43-54-690-edit_com android chrome](https://user-images.githubusercontent.com/43535104/164064176-1822ca19-40a4-430f-9dcf-44bdb9ef05bb.jpg) ![IMG_20220420_014414](https://user-images.githubusercontent.com/43535104/164064193-55938907-dbb2-49d0-8df0-75e9f6e3772d.jpg) 问题重复出现，青龙2.12.1

用2.11.3版本吧。12不太稳

**Comment by 6dylan6** [comment]
不过我测试正常在2.12，你重复的都是6dylan6_jdpro的吗？不会添加两条的呀

**Comment by JMFANS** [comment]
好吧
