### ISSUE TITLE
11.10-11.18 钜惠云集 好礼相送	开卡本设置了邀请码  export opencard1110_code='邀请码'，并发运行还是助力脚本自带助力码

### ISSUE THREAD

**Issue by lsq211** [6dylan6/jdpro#148]
![image](https://github.com/6dylan6/jdpro/assets/135681573/069ff0be-0900-4d11-b6f6-bfb4ff1cf277)

![image](https://github.com/6dylan6/jdpro/assets/135681573/157a0670-5f07-4c26-9cdd-6237bd30a15b)

**Comment by 6dylan6** [comment]
@lsq211 刚修复，你更新，bug了
