### ISSUE TITLE
无法拉库 本地脚本也一个都不在了

### ISSUE THREAD

**Issue by J2zl** [6dylan6/jdpro#149]

**Comment by J2zl** [comment]
<img width="554" alt="image" src="https://github.com/6dylan6/jdpro/assets/23160330/39664afb-c5bf-48df-8a73-131ec8672d0e">

**Comment by J2zl** [comment]
<img width="1709" alt="image" src="https://github.com/6dylan6/jdpro/assets/23160330/e37ca135-600c-4eba-ba4d-17bc879db6a1">

**Comment by 6dylan6** [comment]
@J2zl 老版本青龙bug，repo目录下删掉才拉，或者直接用新版吧

**Comment by J2zl** [comment]
> @J2zl 老版本青龙bug，repo目录下删掉才拉，或者直接用新版吧
已经换新版了
