### ISSUE TITLE
cookie添加问题

### ISSUE THREAD

**Issue by sainting4** [6dylan6/jdpro#15]
cookie添加到哪个文件里面？

**Comment by 6dylan6** [comment]
青龙环境变量里添加ck

**Comment by sainting4** [comment]
还是不太理解怎么添加

**Comment by 6dylan6** [comment]
![image](https://user-images.githubusercontent.com/86815944/153791497-72c5fbec-5c39-49a5-958f-6df504dba884.png)
环境变量-新建变量
