### ISSUE TITLE
东东农场有互助码但未使用

### ISSUE THREAD

**Issue by xhbsa** [6dylan6/jdpro#152]
获取到有互助码但是脚本没有使用![Screenshot_2022-04-20-11-49-43-474_com.android.browser.png](https://user-images.githubusercontent.com/100942064/164146797-140f3009-a520-4752-84ec-28927a62998a.png)

**Comment by 6dylan6** [comment]
检查下config.sh里配置，报错了都
看下获取互助码日志，有没有获取到互助码

**Comment by xhbsa** [comment]
> 检查下config.sh里配置，报错了都
> 看下获取互助码日志，有没有获取到互助码

互助码获取到了但是脚本没有使用

**Comment by xhbsa** [comment]
> 检查下config.sh里配置，报错了都
> 看下获取互助码日志，有没有获取到互助码

可以了谢谢大佬
