### ISSUE TITLE
京东购物微信小程序里面的超级省天天领红包能做脚本么？

### ISSUE THREAD

**Issue by tpc188** [6dylan6/jdpro#153]
京东购物微信小程序，天天领红包任务可以考虑做个脚本！

**Comment by 6dylan6** [comment]
@tpc188 有的，天天来赚钱

**Comment by tpc188** [comment]
@6dylan6 找到了，但是发现有个问题，运行任务领取奖励提示活动太火爆了，是否是等待间隔时间太短？
![微信截图_20231117200545](https://github.com/6dylan6/jdpro/assets/90594523/894bc52a-c944-4021-9e69-9c542a11fc34)
