### ISSUE TITLE
使用代理API export DY_PROXY='url'的问题

### ISSUE THREAD

**Issue by tpc188** [6dylan6/jdpro#154]
使用代理API export DY_PROXY='url'时，能否屏蔽某个脚本不使用代理？需要怎么设置？谢谢

**Comment by 6dylan6** [comment]
@tpc188 设置白名单模式啊，看readme

**Comment by tpc188** [comment]
@6dylan6 设置白名单了没有生效，是不是只针对**代理池**才有效？**代理API无效**？

**Comment by 6dylan6** [comment]
@tpc188 代理池和api都有各自的白名单，不要设置错
