### ISSUE TITLE
依赖安装缺少的依赖和安装源错误问题？

### ISSUE THREAD

**Issue by wifisky-feilian** [6dylan6/jdpro#156]
问题1：依赖安装里面没有requests
----------------------------------------------

京东试用成功通知
## 开始执行... 2023-11-20 20:18:47

Traceback (most recent call last):
  File "/ql/data/scripts/6dylan6_jdpro/jd_try_notify.py", line 6, in <module>
    import requests
ModuleNotFoundError: No module named 'requests'

## 执行结束... 2023-11-20 20:18:48  耗时 1 秒　　　

问题2：依赖安装出现两个错误，其中之一是添加了requests，另一个是依赖安装的默认jieba
-----------------------------------------------------------------------------------------------------

Collecting jieba
  ERROR: HTTP error 403 while getting https://pypi.tuna.tsinghua.edu.cn/packages/c6/cb/18eeb235f833b726522d7ebed54f2278ce28ba9438e3135ab0278d9792a2/jieba-0.42.1.tar.gz#sha256=055ca12f62674fafed09427f176506079bc135638a14e23e25be909131928db2 (from https://pypi.tuna.tsinghua.edu.cn/simple/jieba/)
ERROR: Could not install requirement jieba from https://pypi.tuna.tsinghua.edu.cn/packages/c6/cb/18eeb235f833b726522d7ebed54f2278ce28ba9438e3135ab0278d9792a2/jieba-0.42.1.tar.gz#sha256=055ca12f62674fafed09427f176506079bc135638a14e23e25be909131928db2 because of HTTP error 403 Client Error: Forbidden for url: https://pypi.tuna.tsinghua.edu.cn/packages/c6/cb/18eeb235f833b726522d7ebed54f2278ce28ba9438e3135ab0278d9792a2/jieba-0.42.1.tar.gz for URL https://pypi.tuna.tsinghua.edu.cn/packages/c6/cb/18eeb235f833b726522d7ebed54f2278ce28ba9438e3135ab0278d9792a2/jieba-0.42.1.tar.gz#sha256=055ca12f62674fafed09427f176506079bc135638a14e23e25be909131928db2 (from https://pypi.tuna.tsinghua.edu.cn/simple/jieba/)

[notice] A new release of pip is available: 23.0.1 -> 23.3.1
[notice] To update, run: pip install --upgrade pip
Looking in indexes: https://pypi.tuna.tsinghua.edu.cn/simple/
Collecting requests
  ERROR: HTTP error 403 while getting https://pypi.tuna.tsinghua.edu.cn/packages/70/8e/0e2d847013cb52cd35b38c009bb167a1a26b2ce6cd6965bf26b47bc0bf44/requests-2.31.0-py3-none-any.whl#sha256=58cd2187c01e70e6e26505bca751777aa9f2ee0b7f4300988b709f44e013003f (from https://pypi.tuna.tsinghua.edu.cn/simple/requests/) (requires-python:>=3.7)
ERROR: Could not install requirement requests from https://pypi.tuna.tsinghua.edu.cn/packages/70/8e/0e2d847013cb52cd35b38c009bb167a1a26b2ce6cd6965bf26b47bc0bf44/requests-2.31.0-py3-none-any.whl#sha256=58cd2187c01e70e6e26505bca751777aa9f2ee0b7f4300988b709f44e013003f because of HTTP error 403 Client Error: Forbidden for url: https://pypi.tuna.tsinghua.edu.cn/packages/70/8e/0e2d847013cb52cd35b38c009bb167a1a26b2ce6cd6965bf26b47bc0bf44/requests-2.31.0-py3-none-any.whl for URL https://pypi.tuna.tsinghua.edu.cn/packages/70/8e/0e2d847013cb52cd35b38c009bb167a1a26b2ce6cd6965bf26b47bc0bf44/requests-2.31.0-py3-none-any.whl#sha256=58cd2187c01e70e6e26505bca751777aa9f2ee0b7f4300988b709f44e013003f (from https://pypi.tuna.tsinghua.edu.cn/simple/requests/) (requires-python:>=3.7)

[notice] A new release of pip is available: 23.0.1 -> 23.3.1
[notice] To update, run: pip install --upgrade pip

所需依赖安装完成，请检查有没有报错，可尝试再次运行

## 执行结束... 2023-11-20 20:18:23  耗时 140 秒　

请大神对“依赖安装”脚本更新下需要的依赖和更新源修正？

**Comment by 6dylan6** [comment]
@wifisky-feilian 你在依赖管理手动安装试试吧
