### ISSUE TITLE
京东赚赚的助力码是怎么获取的？

### ISSUE THREAD

**Issue by hushaoyu** [6dylan6/jdpro#159]
京东赚赚执行日志里面提示没有获取到助力码，从获取助力码任务的日志中看，是没有京东赚赚的助力码获取日志的，京东赚赚助力码是需要额外获取吗？

**Comment by 6dylan6** [comment]
不用管，压根活动就没有助力环节了，以前有。

**Comment by hushaoyu** [comment]
> 不用管，压根活动就没有助力环节了，以前有。

好的，thanks。
