### ISSUE TITLE
【BUG】目前的脚本：多个账号，某一个账号cookie失效，它后面的账号就不执行任务了

### ISSUE THREAD

**Issue by wifisky-feilian** [6dylan6/jdpro#160]
目前的脚本：多个账号，某一个账号cookie失效，它后面的账号就不执行任务了。

以前的脚本会自动跳过cookie失效的账号，继续执行下个cookie正常的账号任务。

麻烦大神修复一下（新农场、农场、抽奖等脚本可以复现这些问题，应该是整体影响，其它脚本没有去看）。

**Comment by 6dylan6** [comment]
@wifisky-feilian 青龙自带的通知文件问题，拷贝库里的到deps下在拉库

**Comment by popeshaka** [comment]
> @wifisky-feilian 青龙自带的通知文件问题，拷贝库里的到deps下在拉库
@6dylan6 用了你的通知文件，看了下两个通知文件是一样的……还是存在某个cookie要通知，然后下面的cookie就不运行了，主要集中在两个农场的脚本

**Comment by 6dylan6** [comment]
@popeshaka 那就还不是我的send文件。放到deps下没有

**Comment by popeshaka** [comment]
@6dylan6 


> @popeshaka 那就还不是我的send文件。放到deps下没有

大哥真的有问题啊，不光是cookie失效不继续运行下一个了，实际上是某个号的农场好了，他就直接发通知了，下一个cookie就不继续运行了。已经严格按照你说的，把你的通知文件放到你说的几个位置了
