### ISSUE TITLE
每天都更新库，导致设置的临期京豆换喜豆，每次都要进文件修改，有没有其它办法？

### ISSUE THREAD

**Issue by lunati-wei** [6dylan6/jdpro#160]
库每天都更新，我设置了临期京豆换喜豆 6dylan6_jdpro_jd_exchangejxbeans.js   let exjxbeans = true;
但我每次更新完，就变成了这个let exjxbeans = false;
大佬 有没有办法不更新 我修改的这个文件？或者在命令行里面可以传参吗？好苦闷，每天都得进行来修改下
多谢

**Comment by 6dylan6** [comment]
哈哈。你真行，在config.sh配置文件里写入变量就行了，其他类型
export exjxbeans=true

**Comment by lunati-wei** [comment]
哈哈，不会编程啊，瞎弄，多谢

**Comment by lunati-wei** [comment]
我把这句话，加到config.sh里面，其它不用做啥了吗？config.sh怎么运行呢，哈哈

**Comment by 6dylan6** [comment]
> 我把这句话，加到config.sh里面，其它不用做啥了吗？config.sh怎么运行呢，哈哈

其他不用做了，这里就是控制环境变量的，运行任务会从这里读取配置的。

**Comment by lunati-wei** [comment]
多谢，大佬，耐心，细致，本人脾气应该也很不错，点赞
