### ISSUE TITLE
建议带图评价优化

### ISSUE THREAD

**Issue by daixuyang** [6dylan6/jdpro#162]
希望带图评价的内容可以自己定义或优化一下，里面有一条评价有点不合适，经常拿不满京东豆
![qq_pic_merged_1701149938244](https://github.com/6dylan6/jdpro/assets/25521419/fb3e83f9-dc57-488d-9455-5ea09a0bc946)

**Comment by 6dylan6** [comment]
@daixuyang 你看下是不是没有晒图？

**Comment by daixuyang** [comment]
> @daixuyang你看下是不是没有晒图？

有晒图的
![Screenshot_2023-11-29-11-56-24-710_com jingdong a](https://github.com/6dylan6/jdpro/assets/25521419/f56c2ac3-8034-4b86-9084-04de0edacc91)

**Comment by 6dylan6** [comment]
@daixuyang 那是少了哪部分的豆没拿到呢

**Comment by daixuyang** [comment]
> @daixuyang 那是少了哪部分的豆没拿到呢

我觉得是带图评价，商家要审核，然后我买的东西，价格其实不算便宜，商家觉得评价刷的太明显，然后就不给豆。经常这句评价，反的豆拿不满呢

**Comment by PHCSJC** [comment]
@6dylan6 请问大佬，我的这个带图评价，提示没有待评价是怎么回事呢？其实有很多没评价的
![111](https://github.com/6dylan6/jdpro/assets/22064544/2b7b24f8-bbbf-443e-9538-16a2165e1e5b)

**Comment by 6dylan6** [comment]
@PHCSJC 方便的话私我有问题的ck测试

**Comment by PHCSJC** [comment]
@6dylan6 可以的，怎么私信你？
