### ISSUE TITLE
豆子7天统计 | jd_beans_7days.py运行报错

### ISSUE THREAD

**Issue by yzliufujin** [6dylan6/jdpro#163]
报错日志如下：
'base'
int() argument must be a string, a bytes-like object or a real number, not 'NoneType'
'NoneType' object is not subscriptable
![QQ截图20231130142702](https://github.com/6dylan6/jdpro/assets/61458128/a7ab335f-2134-43e4-ada4-e610e8c50863)

**Comment by 6dylan6** [comment]
@yzliufujin 什么版本青龙

**Comment by yzliufujin** [comment]
版本：正式版 v2.15.15

更新时间：2023-05-28 20:06:15

 

发件人: ***@***.*** ***@***.***> 代表 6dylan6
发送时间: 2023年11月30日, 星期四 15:09
收件人: 6dylan6/jdpro ***@***.***>
抄送: yzliufujin ***@***.***>; Mention ***@***.***>
主题: Re: [6dylan6/jdpro] 豆子7天统计 | jd_beans_7days.py运行报错 (Issue #163)

 

@yzliufujin <https://github.com/yzliufujin>  什么版本青龙
