### ISSUE TITLE
每次更新后 6dylan6_jdpro_main/sendNotify.js 这个文件自动恢复

### ISSUE THREAD

**Issue by hackgsl** [6dylan6/jdpro#164]
复制 https://github.com/6dylan6/jdpro/blob/main/sendNotify.js 替换到6dylan6_jdpro_main/sendNotify.js后，每次拉库后6dylan6_jdpro_main/sendNotify.js都被替换成下面这个1171行的，导致不会自动禁用过期CK

/*
 * @Author: lxk0301 https://gitee.com/lxk0301
 * @Date: 2020-08-19 16:12:40
 * @Last Modified by: whyour
 * @Last Modified time: 2021-5-1 15:00:54
 * sendNotify 推送通知功能
 * @param text 通知头
 * @param desp 通知体
 * @param params 某些推送通知方式点击弹窗可跳转, 例：{ url: 'https://abc.com' }
 * @param author 作者仓库等信息  例：`本通知 By：https://github.com/whyour/qinglong`
 */

**Comment by 6dylan6** [comment]
@hackgsl 青龙会覆盖，拷贝这文件到deps目录下

**Comment by hackgsl** [comment]
> @hackgsl 青龙会覆盖，拷贝这文件到deps目录下

嗯，翻了好多issues，刚刚解决了。
