### ISSUE TITLE
可否把pushdeer的通知加进去

### ISSUE THREAD

**Issue by qqsir-dev** [6dylan6/jdpro#164]
我自己也可以加，但是忘了自动拉取就给覆盖了，白整了....

**Comment by 6dylan6** [comment]
早，你把你测试可行的代码贴给我，我来加进去

**Comment by qqsir-dev** [comment]
好的，我回去整理一下给你，谢谢

**Comment by qqsir-dev** [comment]
// =========PushDeer通知设置区域，我加在了31行======================
//此处填你申请的PushDeer KEY.
//(环境变量名 DEER_KEY)
let PUSHDEER_KEY = '';


//=====PushDeerNotify函数，我加在了1956行，server酱函数后面==========
function PushDeerNotify(text, desp, time = 2100) {
  return new Promise((resolve) => {
    if (PUSHDEER_KEY) {
      // PushDeer 建议对消息内容进行 urlencode
      desp = encodeURI(desp);
      const options = {
        url: `https://api2.pushdeer.com/message/push`,
        body: `pushkey=${PUSHDEER_KEY}&text=${text}&desp=${desp}&type=markdown`,
        headers: {
          'Content-Type': 'application/x-www-form-urlencoded',
        },
        timeout,
      };
      setTimeout(() => {
        $.post(options, (err, resp, data) => {
          try {
            if (err) {
              console.log('发送通知调用API失败！！\n');
              console.log(err);
            } else {
              data = JSON.parse(data);
              // 通过返回的result的长度来判断是否成功
              if (
                data.content.result.length !== undefined &&
                data.content.result.length > 0
              ) {
                console.log('PushDeer发送通知消息成功🎉\n');
              } else {
                console.log(
                  `PushDeer发送通知消息异常\n${JSON.stringify(data)}`,
                );
              }
            }
          } catch (e) {
            $.logErr(e, resp);
          } finally {
            resolve(data);
          }
        });
      }, time);
    } else {
      resolve();
    }
  });
}


//==============210-240行加入===========================
//=======reset变量中加入======
PUSHDEER_KEY = '';

//========变量开关加入========
var Use_PushDeerNotify = true;


//============638行加入===============================
if (process.env.DEER_KEY && Use_PushDeerNotify) {
                PUSHDEER_KEY = process.env.DEER_KEY;
            }

//===========同样分别加入那6套环境变量赋值=================

if (process.env.DEER_KEY2 && Use_PushDeerNotify) {
                PUSHDEER_KEY = process.env.DEER_KEY2;
            }

if (process.env.DEER_KEY3 && Use_PushDeerNotify) {
                PUSHDEER_KEY = process.env.DEER_KEY3;
            }

if (process.env.DEER_KEY4 && Use_PushDeerNotify) {
                PUSHDEER_KEY = process.env.DEER_KEY4;
            }

if (process.env.DEER_KEY5 && Use_PushDeerNotify) {
                PUSHDEER_KEY = process.env.DEER_KEY5;
            }

if (process.env.DEER_KEY6 && Use_PushDeerNotify) {
                PUSHDEER_KEY = process.env.DEER_KEY6;
            }

if (process.env.DEER_KEY7 && Use_PushDeerNotify) {
                PUSHDEER_KEY = process.env.DEER_KEY7;
            }


//=========1516行 加入，加入后因该是7种通知了===============
await PushDeerNotify(text, desp);

我记得这样就行了。

**Comment by 6dylan6** [comment]
可以发通知，只是内容不换行，你那边的会换行吗？

**Comment by qqsir-dev** [comment]
不会，我也问了pushdeer的作者怎么格式化内容，不过还没有回复

**Comment by qqsir-dev** [comment]
不过看官方给的API接口来看好像没有办法，不知道手工加HTML或者CSS能不能管用，就是连格式带信息都写到text字段中，回头试试，能发通知就行，只是阅读上不是特别好看

**Comment by 6dylan6** [comment]
> 不过看官方给的API接口来看好像没有办法，不知道手工加HTML或者CSS能不能管用，就是连格式带信息都写到text字段中，回头试试，能发通知就行，只是阅读上不是特别好看

解决了，可以换行了

**Comment by qqsir-dev** [comment]
> 

厉害呀！！！佩服！!!!

**Comment by qqsir-dev** [comment]
怎么自动更新后并没有更新sendNotify.js文件啊

**Comment by 6dylan6** [comment]
检查deps里面的通知文件。他会覆盖

**Comment by qqsir-dev** [comment]
都给我整晕了，都不知道谁覆盖谁了。。。。
问个问题，比如我和我媳妇的pushdeer，通知怎么区分发送到各自的设备上

**Comment by 6dylan6** [comment]
pushdeer不支持这种方式，使用WxPusher一对一推送

**Comment by qqsir-dev** [comment]
哦，这样啊，好的谢谢了
