### ISSUE TITLE
wskey脚本异常

### ISSUE THREAD

**Issue by mijjjj** [6dylan6/jdpro#165]
现在跑wskey更新ck的脚本所有账号都提示ip风险，然后就是QYWX_KEY服务启动
content账号: pt_pin=mtjjjjj; WsKey疑似失效, 已禁用Cookie
https://qyapi.weixin.qq.com/cgi-bin/webhook/send?key=4283c15a-46e3-4687-944a-a0efadd9b291
{'errcode': 0, 'errmsg': 'ok'}
暂停10秒
用代理或者换新的wskey都不行，但是app运行正常

**Comment by 6dylan6** [comment]
@mijjjj 更新试试
