### ISSUE TITLE
异地登录

### ISSUE THREAD

**Issue by hushaoyu** [6dylan6/jdpro#166]
消息通知里面时不时有异地登录通知，这个是什么操作，是正常的吗？
![lADPJxRxRSB9wZbNBP7NAk4_590_1278](https://user-images.githubusercontent.com/25758091/165207917-4a184536-2f70-47a0-a88e-a8a1392fcb3d.jpg)

**Comment by 6dylan6** [comment]
青龙被扫了，你这是没登录成功，很正常，确保密码复杂破不了你密码，开启二次验证多层保护，改青龙端口减少被扫几率。

**Comment by hushaoyu** [comment]
好的，感谢，已启用二次验证。
