### ISSUE TITLE
jd_AutoEval今天更新的自动评价有问题，评价是乱来的。

### ISSUE THREAD

**Issue by shaufo** [6dylan6/jdpro#166]
![微信截图_20231204114817](https://github.com/6dylan6/jdpro/assets/63514384/70da92b2-0a87-4389-9772-4c23b61c38f6)
![微信截图_20231204114844](https://github.com/6dylan6/jdpro/assets/63514384/cf8ccc07-b8af-45c2-a659-c53b7c86afdd)
![微信截图_20231204114935](https://github.com/6dylan6/jdpro/assets/63514384/115c5fc0-f548-494f-8bad-6d2b48e05186)
![微信截图_20231204115009](https://github.com/6dylan6/jdpro/assets/63514384/4a90353a-46da-40fc-8dcd-563d9cc5ba77)

**Comment by 6dylan6** [comment]
@shaufo 图对不对

**Comment by AFUL1991** [comment]
> @shaufo 图对不对

我也发现了，
图貌似都对，但是评价内容混乱了。
貌似是错位了一个。
我这儿连续四个评价，其中最后三个错位了，貌似是前面多了一个文字评价，所以后面几个都错位了。
具体来说是：
买的书，评价成肘子了；前面的肘子评价成鼠标了；前面两个鼠标，两个评价都对。就是后面多了一个鼠标评价给肘子了。

哈哈哈哈，不过京东貌似没审核，京豆一样给我了。

**Comment by 6dylan6** [comment]
@AFUL1991 bug了 ，已修复

**Comment by shaufo** [comment]
有的对，有的对一半，两张图对一张，有的都不对，京东不显示

![image](https://github.com/6dylan6/jdpro/assets/63514384/05a4206c-0e86-44db-847e-9adf654becd9)![image](https://github.com/6dylan6/jdpro/assets/63514384/52c608f3-4948-4428-a8b7-f2ed6471d2ce)

**Comment by AFUL1991** [comment]
> 有的对，有的对一半，两张图对一张，有的都不对，京东不显示
> 
> ![image](https://private-user-images.githubusercontent.com/63514384/287594171-05a4206c-0e86-44db-847e-9adf654becd9.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTEiLCJleHAiOjE3MDE2NjYzOTcsIm5iZiI6MTcwMTY2NjA5NywicGF0aCI6Ii82MzUxNDM4NC8yODc1OTQxNzEtMDVhNDIwNmMtMGU4Ni00NGRiLTg0N2UtOWFkZjY1NGJlY2Q5LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFJV05KWUFYNENTVkVINTNBJTJGMjAyMzEyMDQlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjMxMjA0VDA1MDEzN1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWNkZDY2OTdhODYxYjA0MmU1MWRlNjU1MWM1YjdhYmUwMjkwYzdjN2NlMDJkZGQ5NjgwNGM0OTMwNjQ2OTgwNTEmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.hZuccjaPd27NVrB3HykTaX7eSXadzPUROpTvjNigt28)![image](https://private-user-images.githubusercontent.com/63514384/287594247-52c608f3-4948-4428-a8b7-f2ed6471d2ce.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTEiLCJleHAiOjE3MDE2NjYzOTcsIm5iZiI6MTcwMTY2NjA5NywicGF0aCI6Ii82MzUxNDM4NC8yODc1OTQyNDctNTJjNjA4ZjMtNDk0OC00NDI4LWE4YjctZjJlZDY0NzFkMmNlLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFJV05KWUFYNENTVkVINTNBJTJGMjAyMzEyMDQlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjMxMjA0VDA1MDEzN1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWEwODljNDU0ODhkYWE3OThmOTE4Mzc2MGI4YzFkNWJiNGVhZjRjY2Q4ZmUzNWU5ZDRmNjg2Njc5YjFiNzkwNDkmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.nHlr6Xer0zOZN4ndaXxLKFhEsS8yfAzI5oEh61FKdH0)

哈哈哈哈，我也发现了，有的图不显示，可能确实是错了。哈哈哈哈，挺好玩的。

**Comment by AFUL1991** [comment]
> @AFUL1991 bug了 ，已修复

明天我再试试，哈哈哈哈，挺好玩的。
