### ISSUE TITLE
大佬，带图评价晒单要怎么设置么？为啥我的不运行？

### ISSUE THREAD

**Issue by xsbs124** [6dylan6/jdpro#167]
![微信截图_20231204232740](https://github.com/6dylan6/jdpro/assets/119865155/23b4e13e-0cb8-4597-b9e5-0a0e2ea2ebab)
是要怎么设置么？？？

**Comment by daixuyang** [comment]
下面写了，环境变量中要添加ONEVAL变量才会执行

**Comment by xsbs124** [comment]
> 下面写了，环境变量中要添加ONEVAL变量才会执行

能详细说一下吗？辛苦了！

**Comment by hcliu987** [comment]
单独的那个，我用着不需要设置这些
