### ISSUE TITLE
怎么才能不被自动覆盖sendNotify.js

### ISSUE THREAD

**Issue by qqsir-dev** [6dylan6/jdpro#167]
为什么老是被一个900多行的同名文件自动覆盖？怎么才能不被覆盖

**Comment by qqsir-dev** [comment]
有这个任务，设置哪里能不影响任务还不让它覆盖

**Comment by 6dylan6** [comment]
你拷贝一份到deps目录下面覆盖青龙自带的就行

**Comment by 6dylan6** [comment]
配置文件里task_before.sh里面有没有内容

**Comment by 6dylan6** [comment]
什么版本的青龙

**Comment by 6dylan6** [comment]
12的是/ql/data/deps路径

**Comment by qqsir-dev** [comment]
嗯，路径我知道，以前版本不一样的，我覆盖一下试试

**Comment by qqsir-dev** [comment]
deps下用了你的，拉库后，deps没变，你目录下的又变成900多行了，哈哈哈，啥情况啊

**Comment by 6dylan6** [comment]
没理由呀。deps目录是/ql/data/deps吗

**Comment by qqsir-dev** [comment]
正常了，感谢
