### ISSUE TITLE
新农场助力脚本 【助力结果】: 活动太火爆了， 请稍后再试~，助力结果为火爆时候，能加一个判断吗？助力火爆3c次，跳下一个号

### ISSUE THREAD

**Issue by lsq211** [6dylan6/jdpro#168]
![image](https://github.com/6dylan6/jdpro/assets/135681573/8b5040fd-2086-45cd-af29-6ef573afee7a)

**Comment by 6dylan6** [comment]
@lsq211 已修

**Comment by lsq211** [comment]
@6dylan6  老农场也有是这个问题，如下图
![image](https://github.com/6dylan6/jdpro/assets/135681573/941d42dd-4e5a-454c-bf52-0853f596bbde)
