### ISSUE TITLE
拉库错误

### ISSUE THREAD

**Issue by tyx776** [6dylan6/jdpro#169]
## 开始执行... 2023-12-07 20:50:45

开始克隆仓库 https://github.com/6dylan6/jdpro.git 到 /ql/data/repo/6dylan6_jdpro_main

Cloning into '/ql/data/repo/6dylan6_jdpro_main'...

error: 5435 bytes of body are still expected

fetch-pack: unexpected disconnect while reading sideband packet
fatal: early EOF
fatal: fetch-pack: invalid index-pack output

更新/ql/data/repo/6dylan6_jdpro_main失败，请检查网络...

## 执行结束... 2023-12-07 20:53:24  耗时 159 秒

今天发现的，提示也不是网络连接问题，像是服务器拒绝。球问

**Comment by 6dylan6** [comment]
@tyx776 运行 拉库|更新问题修复 在试试

**Comment by tyx776** [comment]
> @tyx776 运行 拉库|更新问题修复 在试试

运行了，还是不行

开始克隆仓库 https://github.com/6dylan6/jdpro.git 到 /ql/data/repo/6dylan6_jdpro_main


Cloning into '/ql/data/repo/6dylan6_jdpro_main'...

error: RPC failed; curl 92 HTTP/2 stream 0 was not closed cleanly: CANCEL (err 8)
error: 2662 bytes of body are still expected

fetch-pack: unexpected disconnect while reading sideband packet
fatal: early EOF
fatal: fetch-pack: invalid index-pack output


更新/ql/data/repo/6dylan6_jdpro_main失败，请检查网络...

**Comment by 6dylan6** [comment]
@tyx776 那检查网络吧
