### ISSUE TITLE
拉库报403

### ISSUE THREAD

**Issue by enjoylifes** [6dylan6/jdpro#17]
配置一直没动过，这周就更新不了代码了
<img width="518" alt="image" src="https://github.com/6dylan6/jdpro/assets/34472895/3589d432-617d-4e21-a58c-3cdc1815f932">

<img width="512" alt="image" src="https://github.com/6dylan6/jdpro/assets/34472895/aff010a3-b174-4e4b-9f8f-bca0da9242cc">

**Comment by 6dylan6** [comment]
@enjoylifes ghproxy.com 代理不能用了，换代理

**Comment by enjoylifes** [comment]
> @enjoylifes ghproxy.com 代理不能用了，换代理

更换为js.nbplay.site 可以了，谢谢
