### ISSUE TITLE
pt_pin是中文出错

### ISSUE THREAD

**Issue by qqsir-dev** [6dylan6/jdpro#170]
爆出很多错误，这种又什么办法能解决吗？谢谢

"Invalid character in header content [\"cookie\"]"
京东赚赚API请求失败，请检查网路重试
"Invalid character in header content [\"cookie\"]"
cash API请求失败，请检查网路重试
"Invalid character in header content [\"cookie\"]"
GetJxBean请求失败，请检查网路重试
"Invalid character in header content [\"cookie\"]"
汪汪乐园 API请求失败，请检查网路重试

❗️京东资产统计, 错误!
TypeError: Cannot read properties of undefined (reading 'body')
    at /ql/data/scripts/6dylan6_jdpro/jd_bean_change.js:1778:43
    at /ql/data/scripts/6dylan6_jdpro/jd_bean_change.js:3079:6
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
"Invalid character in header content [\"cookie\"]"
getJingBeanBalanceDetail API请求失败，请检查网路重试
"Invalid character in header content [\"cookie\"]"
jdCash API请求失败，请检查网路重试
"Invalid character in header content [\"cookie\"]"
GetPigPetInfo API请求失败，请检查网路重试
"Invalid character in header content [\"cookie\"]"
JxmcGetRequest API请求失败，请检查网路重试
请求失败
"Invalid character in header content [\"cookie\"]"
GetJxBeanDetailData请求失败，请检查网路重试

东东农场: API查询请求失败 ‼️‼️
"Invalid character in header content [\"cookie\"]"
function_id:taskInitForFarm

❗️京东资产统计, 错误!

东东农场: API查询请求失败 ‼️‼️
"Invalid character in header content [\"cookie\"]"
东东农场API查询失败,等待10秒后再次尝试...
未知情况：undefined
未知情况，跳出
"Invalid character in header content [\"cookie\"]"
queryexpirejingdou API请求失败，请检查网路重试
"Invalid character in header content [\"cookie\"]"
redPacket API请求失败，请检查网路重试

❗️京东资产统计, 错误!
TypeError: Cannot read properties of undefined (reading 'match')
    at /ql/data/scripts/6dylan6_jdpro/jd_bean_change.js:1617:40
    at /ql/data/scripts/6dylan6_jdpro/jd_bean_change.js:3027:6
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
东东农场API查询失败,有空重启路由器换个IP吧.

东东萌宠: API查询请求失败 ‼️‼️
"Invalid character in header content [\"cookie\"]"

❗️京东资产统计, 错误!

东东萌宠: API查询请求失败 ‼️‼️
"Invalid character in header content [\"cookie\"]"

❗️京东资产统计, 错误!

东东萌宠: API查询请求失败 ‼️‼️
"Invalid character in header content [\"cookie\"]"

❗️京东资产统计, 错误!

东东萌宠: API查询请求失败 ‼️‼️
"Invalid character in header content [\"cookie\"]"

**Comment by 6dylan6** [comment]
不会有中文的啊。中文也会转成字母串

**Comment by qqsir-dev** [comment]
是的，拷贝出来自动成中文了，只能用原cookie里显示的那串，问题解决了，谢谢。
