### ISSUE TITLE
1206 脚本都提示登录过期，新鲜的Cookie

### ISSUE THREAD

**Issue by buddingworld** [6dylan6/jdpro#170]
刚登录的，各项操作都可以，但脚本都提示Cookie失效

==============📣系统通知📣==============
东东农场-任务
【提示】cookie已失效
京东账号1 jd_40518d83daaaa
请重新登录获取
https://bean.m.jd.com/bean/signIndex.action
push+发送一对一通知消息完成。

CHRONOCAT 服务的 CHRONOCAT_URL 或 CHRONOCAT_QQ 未设置!!
取消推送

**Comment by 6dylan6** [comment]
@buddingworld 开头有没有提示ck格式问题

**Comment by buddingworld** [comment]
没有，cookie的格式都是一直在用的

pt_key=app_openAAJxx; pt_pin=jd_40518d83dxxxx;

**Comment by buddingworld** [comment]
带上Cookie访问这个的话 都是正常的

https://bean.m.jd.com/beanDetail/index.action?resourceValue=bean

-----------------------------
ps 后续调整了下，把提示过期的cookie顺序调到后面去，居然就可以了，而且脚本遇到第一个过期的直接就停止运行了，也不继续尝试后面的cookie，很神奇

**Comment by buddingworld** [comment]
.

**Comment by buddingworld** [comment]
.
