### ISSUE TITLE
自动评价最多只能跑20个账号，评价也有BUG

### ISSUE THREAD

**Issue by hyue418** [6dylan6/jdpro#171]
自动评价最多只能跑20个账号，多了不会跑，而且没有变量可以改
另外最后2个账号会翻到第2、3页去评价，结果评价了0条，这里貌似有BUG
![WX20231208-165822](https://github.com/6dylan6/jdpro/assets/73208700/e843872e-384d-48d2-aa28-b7ff59bd94f7)

**Comment by 6dylan6** [comment]
@hyue418 私我有问题的ck修复

**Comment by hyue418** [comment]
> @hyue418 私我有问题的ck修复

大佬，怎么私你呢，有邮箱吗

**Comment by hyue418** [comment]
> @hyue418 私我有问题的ck修复

已私TG

**Comment by 6dylan6** [comment]
@hyue418 已修复
