### ISSUE TITLE
好多个脚本提示，这个错误：syntaxerror: Invalid or unexpected token

### ISSUE THREAD

**Issue by popeshaka** [6dylan6/jdpro#175]
如题，没看到缺啥依赖啊
![QQ图片20231212210212](https://github.com/6dylan6/jdpro/assets/45911047/b1f55e44-0537-4536-a9ee-eebd3ea2b8b6)

**Comment by 6dylan6** [comment]
@popeshaka python依赖删了ds，不要乱装

**Comment by popeshaka** [comment]
> @popeshaka python依赖删了ds，不要乱装

确实解决了，但其他脚本还是报错
![Screenshot_2023-12-12-21-41-35-083_com UCMobile](https://github.com/6dylan6/jdpro/assets/45911047/8adc1802-cb44-4552-9755-b224c29cdab4)
![Screenshot_2023-12-12-21-45-13-740_com UCMobile-edit](https://github.com/6dylan6/jdpro/assets/45911047/2cc6510c-2930-4813-b810-de9ee418e10f)
