### ISSUE TITLE
这种报错是什么原因呢

### ISSUE THREAD

**Issue by ROOOCCCK** [6dylan6/jdpro#176]
![1cebd7b5ce4c131e4debf47c22c8db8](https://user-images.githubusercontent.com/79370772/166101102-e04c83cf-0344-483e-a670-54511609f4d6.png)
![ed0885ecb5e4725116d89c47eaa51e1](https://user-images.githubusercontent.com/79370772/166101108-f351869c-83ba-4470-a56f-d53529a7fff3.png)

**Comment by 6dylan6** [comment]
第一个是CK_WxPusherUid.json里面格式不对，检查下。
第二个是今天这样吗？

**Comment by ROOOCCCK** [comment]
> 第一个是CK_WxPusherUid.json里面格式不对，检查下。 第二个是今天这样吗？

搞半天还是WX的锅，现在正常了，刚想留多几个空位置填，没想到出这种错=-=，打扰啦大佬
