### ISSUE TITLE
昨天更新的jd_farm_help.js有问题。

### ISSUE THREAD

**Issue by shaufo** [6dylan6/jdpro#177]
24个号做助力，前面5个是固定顺序，之前都能助力满。但是昨天更新后，现在按顺序排，每个帐号都助力4个。

![002](https://github.com/6dylan6/jdpro/assets/63514384/a2b2114f-f910-475d-a82d-6039fc0b1e68)
![001](https://github.com/6dylan6/jdpro/assets/63514384/75b1e66c-71fd-4121-8877-80502e378561)

**Comment by 6dylan6** [comment]
@shaufo 看看日志呀，为什么第5个就不助力了。

**Comment by shaufo** [comment]
![003](https://github.com/6dylan6/jdpro/assets/63514384/ffa23dbb-cedf-4ecd-b354-e991ebec66d9)
麻烦帮忙看看，是什么原因。

**Comment by shaufo** [comment]
![003](https://github.com/6dylan6/jdpro/assets/63514384/e7557c02-e305-4675-99fd-198859caef6f)
助力已满，难道京东改了吗？之前10个才满，现在4个就满了？

**Comment by 6dylan6** [comment]
@shaufo 好像是，今天砍了
