### ISSUE TITLE
开卡是否会加购

### ISSUE THREAD

**Issue by Pollo3470** [6dylan6/jdpro#178]
想问一下大佬，我昨天开启了开卡，今天购物车加了一堆东西，是开卡导致的吗？

**Comment by 6dylan6** [comment]
是的，开卡会做加购任务

**Comment by FairyWorld** [comment]
> 是的，开卡会做加购任务

开卡会自动付费吗

**Comment by 6dylan6** [comment]
> > 是的，开卡会做加购任务
> 
> 开卡会自动付费吗

不会
