### ISSUE TITLE
已解决

### ISSUE THREAD

**Issue by ugpii** [6dylan6/jdpro#179]
ccwav 那个好用，把库里的替换成那个吧

已经解决了。

**Comment by 6dylan6** [comment]
@ugpii 本来就是的啊，有什么区别吗

**Comment by ugpii** [comment]
咦，奇怪，我拉的怎么是/*
 * @Author: lxk0301 https://gitee.com/lxk0301
 * @Date: 2020-08-19 16:12:40

**Comment by ugpii** [comment]
> ccwav 那个好用，把库里的替换成那个吧
