### ISSUE TITLE
汪汪乐园养joy

### ISSUE THREAD

**Issue by cangbai12** [6dylan6/jdpro#18]
![ZA](https://user-images.githubusercontent.com/80878255/153739404-a2201ad0-40f0-4810-b4c0-766d3118d160.png)
如图，一直限流严重，有没有啥办法整一下嘞

**Comment by 6dylan6** [comment]
api请求失败是黑了，停些日子吧，这个挺容易黑的，我也黑了

**Comment by cangbai12** [comment]
原来如此
