### ISSUE TITLE
农场互助咋填互助码啊

### ISSUE THREAD

**Issue by lsq211** [6dylan6/jdpro#18]
let shareCodes = [ // 这个列表填入你要助力的好友的shareCode
    ''
]
这里设置助力码，运行脚本还是显示无助力码

**Comment by 6dylan6** [comment]
@lsq211 运行获取互助码

**Comment by lsq211** [comment]
好的，谢谢。请问我怎么清除农场日志生成的互助码，要删除农场的日志吗？
