### ISSUE TITLE
wskey转换不支持代理么了

### ISSUE THREAD

**Issue by mijjjj** [6dylan6/jdpro#180]
我刚才看了脚本wskey兑换ck的脚本好像变成了py的，也没看到支持代理，后续有支持么？

**Comment by 6dylan6** [comment]
@mijjjj 有两个呢，另一个支持

**Comment by mijjjj** [comment]
![image](https://github.com/6dylan6/jdpro/assets/37797122/a0ce2195-881f-4b59-a11a-74976b91c25f)
为啥我就显示一个

**Comment by mijjjj** [comment]
有更新脚本了

**Comment by 6dylan6** [comment]
@mijjjj 不是两个吗？本地转换也是啊
