### ISSUE TITLE
https://js.6dygit.workers.dev/https://github.com/6dylan6/jdpro.git 404

### ISSUE THREAD

**Issue by insoxin** [6dylan6/jdpro#180]

**Comment by insoxin** [comment]
报404了

**Comment by 6dylan6** [comment]
https://js.6dygit.workers.dev/前面这个是代理啊。不能浏览器直接那么访问的。拉库正常能啦的

**Comment by insoxin** [comment]
> https://js.6dygit.workers.dev/ 前面这个是代理啊。不能浏览器直接那么访问的。拉库正常能啦的

## 开始执行... 2022-05-08 16:27:59

开始更新仓库：/ql/repo/6dylan6_jdpro

Fetching origin
HEAD is now at a4577b2 update

更新/ql/repo/6dylan6_jdpro失败，重新下载全新仓库...

开始克隆仓库 https://js.6dygit.workers.dev/https://github.com/6dylan6/jdpro.git 到 /ql/repo/6dylan6_jdpro


更新/ql/repo/6dylan6_jdpro失败，请检查网络...


## 执行结束... 2022-05-08 16:28:15  耗时 16 秒

**Comment by insoxin** [comment]
我看最新成功5月6日

**Comment by insoxin** [comment]
7号八号不行了

**Comment by 6dylan6** [comment]
你青龙啥版本。没有配置代理吧

**Comment by insoxin** [comment]
没配置, 之前一直可以的

**Comment by 6dylan6** [comment]
从新拉，检查下机器网络正常不

**Comment by insoxin** [comment]
> 从新拉，检查下机器网络正常不

正常,,,试了curl 网络正常

**Comment by 6dylan6** [comment]
那去掉代理地址在拉试试

**Comment by insoxin** [comment]
另外,我看有开卡脚本,加密了, 我都解密了,能推上来吗,如果这些是你写的,我就不推了

**Comment by 6dylan6** [comment]
牛呀，部分搬运的，可以先推个看看

**Comment by insoxin** [comment]
https://www.itdog.cn/tcping/workers.dev

找到原因了,被dns污染了

**Comment by 6dylan6** [comment]
是的。全挂啦。代理暂不能用了
