### ISSUE TITLE
金融签到失败了

### ISSUE THREAD

**Issue by hackgsl** [6dylan6/jdpro#181]
===========脚本执行时间：2023/12/19 10:39:19============
>>>>>>>>>>>>6Dy提醒您：有问题先更新不行在反馈>>>>>>>>>>>>>

只跑前10，多了也是黑ip！！！

请求失败，换个时间再试试！！！

## 执行结束...   耗时 13 秒

**Comment by 6dylan6** [comment]
@hackgsl 哪里机，我  这正常啊

**Comment by hackgsl** [comment]
> @hackgsl 哪里机，我 这正常啊

广东联通，整个日志就这样，只有一个请求失败，没其他错误信息

金融签到

## 开始执行... 2023-12-17 08:25:01

任务随机延迟 89 秒，配置文件参数 RandomDelay 置空可取消延迟 

🔔金融签到, 开始!
加载sendNotify，当前版本: 20230712

====================共22个京东账号Cookie=================
===========脚本执行时间：2023/12/17 08:26:41============
>>>>>>>>>>>>6Dy提醒您：有问题先更新不行在反馈>>>>>>>>>>>>>

只跑前10，多了也是黑ip！！！

请求失败，换个时间再试试！！！

## 执行结束...   耗时 103 秒

**Comment by hackgsl** [comment]
> @hackgsl 哪里机，我 这正常啊

啥都没变化，今天突然就好了。
==============================

## 开始执行... 2023-12-27 08:25:01

任务随机延迟 14 秒，配置文件参数 RandomDelay 置空可取消延迟 
🔔金融签到, 开始!
加载sendNotify，当前版本: 20230712
====================共23个京东账号Cookie=================
===========脚本执行时间：2023/12/27 08:25:26============
>>>>>>>>>>>>6Dy提醒您：有问题先更新不行在反馈>>>>>>>>>>>>>
只跑前10，多了也是黑ip！！！
***********开始【京东账号1】********

签到成功！

**Comment by hackgsl** [comment]
> @hackgsl 哪里机，我 这正常啊

昨天才说好了，今天又不行了，没日志不知道什么原因
