### ISSUE TITLE
东东农场这助力水滴是黑了吗

### ISSUE THREAD

**Issue by ysf37** [6dylan6/jdpro#182]
![1703385726071](https://github.com/6dylan6/jdpro/assets/19886505/a5bca17f-39fe-4b8d-9d90-426231c9ecb8)

**Comment by 6dylan6** [comment]
@ysf37 不进去app看看吗，改了

**Comment by ysf37** [comment]
@6dylan6 看到了，这改得要一个多月才能搞个12无门槛了
