### ISSUE TITLE
已经按照说明进行了拉库，然后怎么使用，京东帐号配置到哪里？

### ISSUE THREAD

**Issue by jldhrj** [6dylan6/jdpro#184]
已经按照说明进行了拉库，然后怎么使用，京东帐号配置到哪里？

**Comment by jldhrj** [comment]
![image](https://user-images.githubusercontent.com/39984569/167363649-0f5346e6-f519-406d-a50c-1cd85f80a7e8.png)

**Comment by 6dylan6** [comment]
![image](https://user-images.githubusercontent.com/86815944/167363774-1137fcd6-c210-413e-80b9-cd6797507736.png)
环境变量里添加，一个行一号

**Comment by jldhrj** [comment]
![image](https://user-images.githubusercontent.com/39984569/167365353-32028f14-cabf-4990-8f00-0088cf613aff.png)
不好意思是直接添加帐号密码，还是把登录后整段cookie放进来。谢谢。

**Comment by 6dylan6** [comment]
pt_key=xxxx;pt_pin=xxxx;
这样的，不用整个放。
从m.jd.com网站抓

**Comment by jldhrj** [comment]
找到了，谢谢您。

**Comment by jldhrj** [comment]
> 

是的刚刚入坑，还没运行成功。已经配置环境变量的jd_ck帐号了，不知道下一步怎么跑哈哈哈
