### ISSUE TITLE
git clone可以，ql repo拉库就失败

### ISSUE THREAD

**Issue by iawes** [6dylan6/jdpro#185]
root@6d5d69f57f69:/ql/repo $ git clone https://js.jdpro.site/https://github.com/6dylan6/jdpro.git
Cloning into 'jdpro'...
remote: Enumerating objects: 2020, done.
remote: Counting objects: 100% (2020/2020), done.
remote: Compressing objects: 100% (1267/1267), done.
remote: Total 2020 (delta 766), reused 1868 (delta 750), pack-reused 0
Receiving objects: 100% (2020/2020), 32.62 MiB | 4.62 MiB/s, done.
Resolving deltas: 100% (766/766), done.
root@6d5d69f57f69:/ql/repo $  ql repo https://js.jdpro.site/https://github.com/6dylan6/jdpro.git "jd_|jx_|jddj_" "backUp" "^jd[^_]|USER|JD|function|sendNotify"
fatal: No such remote 'origin'
fatal: .git/index: index file smaller than expected
fatal: .git/index: index file smaller than expected
fatal: .git/index: index file smaller than expected
fatal: .git/index: index file smaller than expected
## 开始执行... 2023-12-27 15:48:31

开始更新仓库：/ql/repo/6dylan6_jdpro

更新/ql/repo/6dylan6_jdpro失败，请检查网络...

**Comment by 6dylan6** [comment]
@iawes 删除重新拉试试
