### ISSUE TITLE
希望这个能有大佬做一个脚本：我的-京东财富-天天领10京豆

### ISSUE THREAD

**Issue by justyeh** [6dylan6/jdpro#186]

**Comment by 6dylan6** [comment]
@justyeh 哪地方，我没找到

**Comment by justyeh** [comment]
@6dylan6 抱歉没有关注github通知，下面是路径
![1](https://github.com/6dylan6/jdpro/assets/15848818/50525f82-ab33-4998-9a41-e21823dd4095)
![2](https://github.com/6dylan6/jdpro/assets/15848818/916a4f8d-39b6-46ba-a877-e2a942e0014b)
![3](https://github.com/6dylan6/jdpro/assets/15848818/5e035675-bda2-4039-958f-d2c07ab746c8)
