### ISSUE TITLE
请问怎么才能关闭水滴换京豆，只浇水呢？

### ISSUE THREAD

**Issue by xiaoyutx94** [6dylan6/jdpro#187]
![image](https://github.com/6dylan6/jdpro/assets/5671609/523ff07f-e319-4cde-8209-047ad357bb4a)

我看脚本写的默认是浇水，但是日志输出了这个，而且也确实水滴兑换为京豆了。

**Comment by 6dylan6** [comment]
@snailg 你检查设置的变量，肯定有水滴换豆的变量

**Comment by xiaoyutx94** [comment]
> @snailg 你检查设置的变量，肯定有水滴换豆的变量

谢谢大佬的提醒，我之前拉过别的config.sh，里面有浇水的变量与大佬的变量一致导致的，一直没想起来。

**Comment by basten1899** [comment]
问下不换豆的变量是啥 我的也不行了 设置变量没反应

**Comment by 6dylan6** [comment]
@basten1899 jdFruitBeanCard 检查有没有设置这个环境变量

**Comment by basten1899** [comment]
这个早就设置了 日志还是显示"您设置的是水滴换豆功能,现在为您换豆"

**Comment by 6dylan6** [comment]
@basten1899 所以，你设置了当然会换了，你不要设置呀

**Comment by basten1899** [comment]
@6dylan6  我的意思是设置的false 怎么会换

**Comment by 6dylan6** [comment]
@basten1899 fasle也不行，设置空''或者删除这个变量。不是识别false的

**Comment by basten1899** [comment]
@6dylan6 一开始是没这个变量的 就是不行 后来找老版本的脚本找到这个变量  设置空也还是没用

**Comment by 6dylan6** [comment]
@basten1899 当前版本：20240709/23 这个版本吗？你用的

**Comment by basten1899** [comment]
重新建个docker 又正常了  估计哪个其他变量覆盖影响了

**Comment by 6dylan6** [comment]
@basten1899 那可能变量重复配置多个了

**Comment by basten1899** [comment]
@6dylan6 我翻查了一下 是不是还有FRUIT_BEAN_CARD这个环境变量影响,老的脚本是有的  是不是没删干净

**Comment by 6dylan6** [comment]
@basten1899 哦哦，上面说错了，就是FRUIT_BEAN_CARD这个变量
