### ISSUE TITLE
签到日历不能自动签到

### ISSUE THREAD

**Issue by zhaoxuhong** [6dylan6/jdpro#188]
签到日历没法自动签到，需要手动签可以解决吗
![Screenshot_2022-05-10-13-43-17-537_com jingdong app mall](https://user-images.githubusercontent.com/82372144/167556784-9238c088-9b8a-4c77-a064-426314920509.jpg)

**Comment by 6dylan6** [comment]
自动签的呀。我一直就没断签过的

**Comment by zhaoxuhong** [comment]
> 自动签的呀。我一直断签过的。
是M京东签到这个脚本吗
