### ISSUE TITLE
大牌0101积分换实物

### ISSUE THREAD

**Issue by deepblue5566** [6dylan6/jdpro#189]
你好，运行【大牌0101】，积分换了实物后，访问【实物请手动填地址】的网址显示-当前环境不支持活动-，请问这个应该去哪里填写地址？

**Comment by 6dylan6** [comment]
@deepblue5566 跳转到jd打开，或发到客服聊天界面打开

**Comment by deepblue5566** [comment]
@6dylan6 
好的，谢谢。  发到客服聊天界面打开可以了。
不过还想问下跳转是怎么跳呢？我复制链接后打开京东没有反映，没有跳转到活动界面。
