### ISSUE TITLE
店铺签到jd_dpsign.js添加token后显示结果：失效token

### ISSUE THREAD

**Issue by AidenHuo** [6dylan6/jdpro#19]
尝试设置了变量DPSTOKEN，值为activityid。
结果为：
===
活动已失效

1个失效token，变量已移除
===

如果不使用变量，只有一个店铺，也报同样的问题：
===
店铺->1:9113a1d98a1f4445baf477407a145e70
活动已失效

1个失效token，变量已移除
===

注解里边写的“优先使用变量token，没有则使用内置token”，将内置token取消注释后，依旧是上边这一个店铺，且失效。
这个应该如何解决。

另外，现在店铺签到里边都会先选择“我已阅读并知晓”，然后点击按钮“知道了，继续签到”。是不是这类的签到还没支持上？

感谢。

**Comment by 6dylan6** [comment]
@AidenHuo 这是普通店铺签到不是无线的，就是进店铺右侧的签到
