### ISSUE TITLE
批量取关脚本失败后死循环，无法自动跳出，只能手动停止

### ISSUE THREAD

**Issue by quanjindeng** [6dylan6/jdpro#19]
## 开始执行... 2022-02-13 13:44:09

🔔批量取关店铺和商品, 开始!

====================共4个京东账号Cookie=========

==================脚本执行- 北京时间(UTC+8)：2022/2/13 下午1:44:11=====================

X1a0He留：运行前请看好脚本内的注释，日志已经很清楚了，有问题带着日志来问

****开始【京东账号1】*** *****

=====京东账号1 *** 内部变量=====
$.unsubscribeGoodsNum: 0
$.unsubscribeShopsNum: 0
$.goodsTotalNum: 0
$.shopsTotalNum: 0
$.commIdList: 
$.shopIdList: 
$.failTimes: 0
================
正在获取已关注的商品...
当前已关注商品：36个
正在取消收藏商品...
成功取消收藏商品：20个

正在获取已关注的店铺...
当前已关注店铺：221个
正在执行批量取消关注店铺...
已成功取消关注店铺：20个

正在获取已关注的商品...
当前已关注商品：16个
正在取消收藏商品...
成功取消收藏商品：36个

正在获取已关注的商品...
当前已关注商品：0个
不执行取消收藏商品

正在获取已关注的店铺...
当前已关注店铺：201个
正在执行批量取消关注店铺...
已成功取消关注店铺：40个

正在获取已关注的店铺...
当前已关注店铺：181个
正在执行批量取消关注店铺...
已成功取消关注店铺：60个

正在获取已关注的店铺...
当前已关注店铺：161个
正在执行批量取消关注店铺...
已成功取消关注店铺：80个

正在获取已关注的店铺...
当前已关注店铺：141个
正在执行批量取消关注店铺...
已成功取消关注店铺：100个

正在获取已关注的店铺...
当前已关注店铺：121个
正在执行批量取消关注店铺...
已成功取消关注店铺：120个

正在获取已关注的店铺...
当前已关注店铺：101个
正在执行批量取消关注店铺...
已成功取消关注店铺：140个

正在获取已关注的店铺...
当前已关注店铺：81个
正在执行批量取消关注店铺...
已成功取消关注店铺：160个

正在获取已关注的店铺...
当前已关注店铺：61个
正在执行批量取消关注店铺...
已成功取消关注店铺：180个

正在获取已关注的店铺...
当前已关注店铺：41个
正在执行批量取消关注店铺...
已成功取消关注店铺：200个

正在获取已关注的店铺...
当前已关注店铺：21个
正在执行批量取消关注店铺...
已成功取消关注店铺：220个

正在获取已关注的店铺...
当前已关注店铺：1个
正在执行批量取消关注店铺...
已成功取消关注店铺：221个

正在获取已关注的店铺...
当前已关注店铺：0个
无店铺可取消关注

不执行取消收藏店铺

【京东账号1】***
【还剩关注店铺】0个
【还剩关注商品】0个

****开始【京东账号2】*** *****

=====京东账号2 ***内部变量=====
$.unsubscribeGoodsNum: 0
$.unsubscribeShopsNum: 0
$.goodsTotalNum: 0
$.shopsTotalNum: 0
$.commIdList: 
$.shopIdList: 
$.failTimes: 0
================
正在获取已关注的商品...
当前已关注商品：74个
正在取消收藏商品...
成功取消收藏商品：20个

正在获取已关注的店铺...
当前已关注店铺：220个
正在执行批量取消关注店铺...
已成功取消关注店铺：20个

正在获取已关注的商品...
当前已关注商品：54个
正在取消收藏商品...
成功取消收藏商品：40个

正在获取已关注的商品...
当前已关注商品：34个
正在取消收藏商品...
成功取消收藏商品：60个

正在获取已关注的商品...
当前已关注商品：14个
正在取消收藏商品...
成功取消收藏商品：74个

正在获取已关注的商品...
当前已关注商品：0个
不执行取消收藏商品

正在获取已关注的店铺...
当前已关注店铺：200个
正在执行批量取消关注店铺...
已成功取消关注店铺：40个

正在获取已关注的店铺...
当前已关注店铺：180个
正在执行批量取消关注店铺...
已成功取消关注店铺：60个

正在获取已关注的店铺...
当前已关注店铺：160个
正在执行批量取消关注店铺...
已成功取消关注店铺：80个

正在获取已关注的店铺...
当前已关注店铺：140个
正在执行批量取消关注店铺...
已成功取消关注店铺：100个

正在获取已关注的店铺...
当前已关注店铺：120个
正在执行批量取消关注店铺...
已成功取消关注店铺：120个

正在获取已关注的店铺...
当前已关注店铺：100个
正在执行批量取消关注店铺...
已成功取消关注店铺：140个

正在获取已关注的店铺...
当前已关注店铺：80个
正在执行批量取消关注店铺...
已成功取消关注店铺：160个

正在获取已关注的店铺...
当前已关注店铺：60个
正在执行批量取消关注店铺...
已成功取消关注店铺：180个

正在获取已关注的店铺...
当前已关注店铺：40个
正在执行批量取消关注店铺...
已成功取消关注店铺：200个

正在获取已关注的店铺...
当前已关注店铺：20个
正在执行批量取消关注店铺...
已成功取消关注店铺：220个

正在获取已关注的店铺...
当前已关注店铺：1个
正在执行批量取消关注店铺...
批量取消关注店铺失败，失败次数：1

正在获取已关注的店铺...
当前已关注店铺：1个
正在执行批量取消关注店铺...
批量取消关注店铺失败，失败次数：2

正在获取已关注的店铺...
当前已关注店铺：1个
正在执行批量取消关注店铺...
批量取消关注店铺失败，失败次数：3

失败次数到达设定值，触发防死循环机制，该帐号已跳过
正在获取已关注的店铺...
当前已关注店铺：1个
正在执行批量取消关注店铺...
批量取消关注店铺失败，失败次数：4

失败次数到达设定值，触发防死循环机制，该帐号已跳过
正在获取已关注的店铺...
当前已关注店铺：1个
正在执行批量取消关注店铺...
批量取消关注店铺失败，失败次数：5

失败次数到达设定值，触发防死循环机制，该帐号已跳过
正在获取已关注的店铺...
当前已关注店铺：1个
正在执行批量取消关注店铺...
批量取消关注店铺失败，失败次数：6

失败次数到达设定值，触发防死循环机制，该帐号已跳过
正在获取已关注的店铺...
当前已关注店铺：1个
正在执行批量取消关注店铺...
批量取消关注店铺失败，失败次数：7

失败次数到达设定值，触发防死循环机制，该帐号已跳过
正在获取已关注的店铺...
当前已关注店铺：1个
正在执行批量取消关注店铺...
批量取消关注店铺失败，失败次数：8

失败次数到达设定值，触发防死循环机制，该帐号已跳过
正在获取已关注的店铺...
当前已关注店铺：1个
正在执行批量取消关注店铺...
批量取消关注店铺失败，失败次数：9

失败次数到达设定值，触发防死循环机制，该帐号已跳过
正在获取已关注的店铺...
当前已关注店铺：1个
正在执行批量取消关注店铺...
批量取消关注店铺失败，失败次数：10

失败次数到达设定值，触发防死循环机制，该帐号已跳过
正在获取已关注的店铺...
当前已关注店铺：1个
正在执行批量取消关注店铺...
批量取消关注店铺失败，失败次数：11

失败次数到达设定值，触发防死循环机制，该帐号已跳过
正在获取已关注的店铺...
当前已关注店铺：1个
正在执行批量取消关注店铺...
批量取消关注店铺失败，失败次数：12

失败次数到达设定值，触发防死循环机制，该帐号已跳过
正在获取已关注的店铺...
当前已关注店铺：1个
正在执行批量取消关注店铺...
批量取消关注店铺失败，失败次数：13

失败次数到达设定值，触发防死循环机制，该帐号已跳过
正在获取已关注的店铺...
当前已关注店铺：1个
正在执行批量取消关注店铺...
批量取消关注店铺失败，失败次数：14

失败次数到达设定值，触发防死循环机制，该帐号已跳过
正在获取已关注的店铺...
当前已关注店铺：1个
正在执行批量取消关注店铺...
批量取消关注店铺失败，失败次数：15

失败次数到达设定值，触发防死循环机制，该帐号已跳过
正在获取已关注的店铺...
当前已关注店铺：1个
正在执行批量取消关注店铺...
批量取消关注店铺失败，失败次数：16

失败次数到达设定值，触发防死循环机制，该帐号已跳过
正在获取已关注的店铺...
当前已关注店铺：1个
正在执行批量取消关注店铺...
批量取消关注店铺失败，失败次数：17

失败次数到达设定值，触发防死循环机制，该帐号已跳过
正在获取已关注的店铺...
当前已关注店铺：1个
正在执行批量取消关注店铺...
批量取消关注店铺失败，失败次数：18

失败次数到达设定值，触发防死循环机制，该帐号已跳过
正在获取已关注的店铺...
当前已关注店铺：1个
正在执行批量取消关注店铺...
批量取消关注店铺失败，失败次数：19

失败次数到达设定值，触发防死循环机制，该帐号已跳过
正在获取已关注的店铺...
当前已关注店铺：1个
正在执行批量取消关注店铺...
批量取消关注店铺失败，失败次数：20

失败次数到达设定值，触发防死循环机制，该帐号已跳过
正在获取已关注的店铺...
当前已关注店铺：1个
正在执行批量取消关注店铺...
批量取消关注店铺失败，失败次数：21

失败次数到达设定值，触发防死循环机制，该帐号已跳过
正在获取已关注的店铺...
当前已关注店铺：1个
正在执行批量取消关注店铺...
批量取消关注店铺失败，失败次数：22

失败次数到达设定值，触发防死循环机制，该帐号已跳过
正在获取已关注的店铺...
当前已关注店铺：1个
正在执行批量取消关注店铺...
批量取消关注店铺失败，失败次数：23

失败次数到达设定值，触发防死循环机制，该帐号已跳过
正在获取已关注的店铺...
当前已关注店铺：1个
正在执行批量取消关注店铺...
批量取消关注店铺失败，失败次数：24

失败次数到达设定值，触发防死循环机制，该帐号已跳过
正在获取已关注的店铺...
当前已关注店铺：1个
正在执行批量取消关注店铺...
批量取消关注店铺失败，失败次数：25

失败次数到达设定值，触发防死循环机制，该帐号已跳过
正在获取已关注的店铺...
当前已关注店铺：1个
正在执行批量取消关注店铺...
批量取消关注店铺失败，失败次数：26

失败次数到达设定值，触发防死循环机制，该帐号已跳过
正在获取已关注的店铺...
当前已关注店铺：1个
正在执行批量取消关注店铺...
批量取消关注店铺失败，失败次数：27

失败次数到达设定值，触发防死循环机制，该帐号已跳过
正在获取已关注的店铺...
当前已关注店铺：1个
正在执行批量取消关注店铺...
批量取消关注店铺失败，失败次数：28

失败次数到达设定值，触发防死循环机制，该帐号已跳过
正在获取已关注的店铺...
当前已关注店铺：1个
正在执行批量取消关注店铺...
批量取消关注店铺失败，失败次数：29

失败次数到达设定值，触发防死循环机制，该帐号已跳过
正在获取已关注的店铺...
当前已关注店铺：1个
正在执行批量取消关注店铺...
批量取消关注店铺失败，失败次数：30

失败次数到达设定值，触发防死循环机制，该帐号已跳过
正在获取已关注的店铺...
当前已关注店铺：1个
正在执行批量取消关注店铺...
批量取消关注店铺失败，失败次数：31

失败次数到达设定值，触发防死循环机制，该帐号已跳过
正在获取已关注的店铺...
当前已关注店铺：1个
正在执行批量取消关注店铺...
批量取消关注店铺失败，失败次数：32

失败次数到达设定值，触发防死循环机制，该帐号已跳过
正在获取已关注的店铺...
当前已关注店铺：1个
正在执行批量取消关注店铺...
批量取消关注店铺失败，失败次数：33

失败次数到达设定值，触发防死循环机制，该帐号已跳过
正在获取已关注的店铺...
当前已关注店铺：1个
正在执行批量取消关注店铺...
批量取消关注店铺失败，失败次数：34

失败次数到达设定值，触发防死循环机制，该帐号已跳过
正在获取已关注的店铺...
当前已关注店铺：1个
正在执行批量取消关注店铺...
批量取消关注店铺失败，失败次数：35

失败次数到达设定值，触发防死循环机制，该帐号已跳过
正在获取已关注的店铺...
当前已关注店铺：1个
正在执行批量取消关注店铺...
批量取消关注店铺失败，失败次数：36

失败次数到达设定值，触发防死循环机制，该帐号已跳过
正在获取已关注的店铺...
当前已关注店铺：1个
正在执行批量取消关注店铺...
批量取消关注店铺失败，失败次数：37

失败次数到达设定值，触发防死循环机制，该帐号已跳过
正在获取已关注的店铺...
当前已关注店铺：1个
正在执行批量取消关注店铺...
批量取消关注店铺失败，失败次数：38

失败次数到达设定值，触发防死循环机制，该帐号已跳过
正在获取已关注的店铺...
当前已关注店铺：1个
正在执行批量取消关注店铺...
批量取消关注店铺失败，失败次数：39

失败次数到达设定值，触发防死循环机制，该帐号已跳过
正在获取已关注的店铺...
当前已关注店铺：1个
正在执行批量取消关注店铺...
批量取消关注店铺失败，失败次数：40

失败次数到达设定值，触发防死循环机制，该帐号已跳过
正在获取已关注的店铺...
当前已关注店铺：1个
正在执行批量取消关注店铺...
批量取消关注店铺失败，失败次数：41

失败次数到达设定值，触发防死循环机制，该帐号已跳过
正在获取已关注的店铺...
当前已关注店铺：1个
正在执行批量取消关注店铺...
批量取消关注店铺失败，失败次数：42

失败次数到达设定值，触发防死循环机制，该帐号已跳过
正在获取已关注的店铺...
当前已关注店铺：1个
正在执行批量取消关注店铺...
批量取消关注店铺失败，失败次数：43

失败次数到达设定值，触发防死循环机制，该帐号已跳过
正在获取已关注的店铺...
当前已关注店铺：1个
正在执行批量取消关注店铺...
批量取消关注店铺失败，失败次数：44

失败次数到达设定值，触发防死循环机制，该帐号已跳过
正在获取已关注的店铺...
当前已关注店铺：1个
正在执行批量取消关注店铺...
批量取消关注店铺失败，失败次数：45

失败次数到达设定值，触发防死循环机制，该帐号已跳过
正在获取已关注的店铺...
当前已关注店铺：1个
正在执行批量取消关注店铺...
批量取消关注店铺失败，失败次数：46

失败次数到达设定值，触发防死循环机制，该帐号已跳过
正在获取已关注的店铺...
当前已关注店铺：1个
正在执行批量取消关注店铺...
批量取消关注店铺失败，失败次数：47

失败次数到达设定值，触发防死循环机制，该帐号已跳过
正在获取已关注的店铺...
当前已关注店铺：1个
正在执行批量取消关注店铺...
批量取消关注店铺失败，失败次数：48

失败次数到达设定值，触发防死循环机制，该帐号已跳过
正在获取已关注的店铺...
当前已关注店铺：1个
正在执行批量取消关注店铺...
批量取消关注店铺失败，失败次数：49

失败次数到达设定值，触发防死循环机制，该帐号已跳过
正在获取已关注的店铺...
当前已关注店铺：1个
正在执行批量取消关注店铺...
批量取消关注店铺失败，失败次数：50

失败次数到达设定值，触发防死循环机制，该帐号已跳过
正在获取已关注的店铺...
当前已关注店铺：1个
正在执行批量取消关注店铺...
批量取消关注店铺失败，失败次数：51

失败次数到达设定值，触发防死循环机制，该帐号已跳过
正在获取已关注的店铺...
当前已关注店铺：1个
正在执行批量取消关注店铺...
批量取消关注店铺失败，失败次数：52

失败次数到达设定值，触发防死循环机制，该帐号已跳过
正在获取已关注的店铺...
当前已关注店铺：1个
正在执行批量取消关注店铺...
批量取消关注店铺失败，失败次数：53

失败次数到达设定值，触发防死循环机制，该帐号已跳过
正在获取已关注的店铺...
当前已关注店铺：1个
正在执行批量取消关注店铺...
批量取消关注店铺失败，失败次数：54

失败次数到达设定值，触发防死循环机制，该帐号已跳过
正在获取已关注的店铺...
当前已关注店铺：1个
正在执行批量取消关注店铺...
批量取消关注店铺失败，失败次数：55

失败次数到达设定值，触发防死循环机制，该帐号已跳过
正在获取已关注的店铺...
当前已关注店铺：1个
正在执行批量取消关注店铺...
批量取消关注店铺失败，失败次数：56

失败次数到达设定值，触发防死循环机制，该帐号已跳过
正在获取已关注的店铺...
当前已关注店铺：1个
正在执行批量取消关注店铺...
批量取消关注店铺失败，失败次数：57

失败次数到达设定值，触发防死循环机制，该帐号已跳过
正在获取已关注的店铺...
当前已关注店铺：1个
正在执行批量取消关注店铺...
批量取消关注店铺失败，失败次数：58

失败次数到达设定值，触发防死循环机制，该帐号已跳过
正在获取已关注的店铺...
当前已关注店铺：1个
正在执行批量取消关注店铺...
批量取消关注店铺失败，失败次数：59

失败次数到达设定值，触发防死循环机制，该帐号已跳过
正在获取已关注的店铺...
当前已关注店铺：1个
正在执行批量取消关注店铺...
批量取消关注店铺失败，失败次数：60

失败次数到达设定值，触发防死循环机制，该帐号已跳过
正在获取已关注的店铺...
当前已关注店铺：1个
正在执行批量取消关注店铺...
批量取消关注店铺失败，失败次数：61

失败次数到达设定值，触发防死循环机制，该帐号已跳过
正在获取已关注的店铺...
当前已关注店铺：1个
正在执行批量取消关注店铺...
批量取消关注店铺失败，失败次数：62

失败次数到达设定值，触发防死循环机制，该帐号已跳过
正在获取已关注的店铺...
当前已关注店铺：1个
正在执行批量取消关注店铺...
批量取消关注店铺失败，失败次数：63

失败次数到达设定值，触发防死循环机制，该帐号已跳过
正在获取已关注的店铺...
当前已关注店铺：1个
正在执行批量取消关注店铺...
批量取消关注店铺失败，失败次数：64

失败次数到达设定值，触发防死循环机制，该帐号已跳过
正在获取已关注的店铺...
当前已关注店铺：1个
正在执行批量取消关注店铺...
批量取消关注店铺失败，失败次数：65

失败次数到达设定值，触发防死循环机制，该帐号已跳过
正在获取已关注的店铺...
当前已关注店铺：1个
正在执行批量取消关注店铺...
批量取消关注店铺失败，失败次数：66

失败次数到达设定值，触发防死循环机制，该帐号已跳过
正在获取已关注的店铺...
当前已关注店铺：1个
正在执行批量取消关注店铺...
批量取消关注店铺失败，失败次数：67

失败次数到达设定值，触发防死循环机制，该帐号已跳过
正在获取已关注的店铺...
当前已关注店铺：1个
正在执行批量取消关注店铺...
批量取消关注店铺失败，失败次数：68

失败次数到达设定值，触发防死循环机制，该帐号已跳过
正在获取已关注的店铺...
当前已关注店铺：1个
正在执行批量取消关注店铺...
批量取消关注店铺失败，失败次数：69

失败次数到达设定值，触发防死循环机制，该帐号已跳过
正在获取已关注的店铺...
当前已关注店铺：1个
正在执行批量取消关注店铺...
批量取消关注店铺失败，失败次数：70

失败次数到达设定值，触发防死循环机制，该帐号已跳过
正在获取已关注的店铺...
当前已关注店铺：1个
正在执行批量取消关注店铺...
批量取消关注店铺失败，失败次数：71

失败次数到达设定值，触发防死循环机制，该帐号已跳过
正在获取已关注的店铺...
当前已关注店铺：1个
正在执行批量取消关注店铺...
批量取消关注店铺失败，失败次数：72

失败次数到达设定值，触发防死循环机制，该帐号已跳过
正在获取已关注的店铺...
当前已关注店铺：1个
正在执行批量取消关注店铺...
批量取消关注店铺失败，失败次数：73

失败次数到达设定值，触发防死循环机制，该帐号已跳过
正在获取已关注的店铺...
当前已关注店铺：1个
正在执行批量取消关注店铺...

## 执行结束...  2022/2/13 13:46:36

**Comment by 6dylan6** [comment]
已更新，会自动停止
