### ISSUE TITLE
东东农场浇水失败

### ISSUE THREAD

**Issue by gg-shuige** [6dylan6/jdpro#190]
日志-东东农场
❗️东东农场, 错误!
TypeError: Cannot read properties of undefined (reading 'code')
    at turntableFarm (/ql/scripts/6dylan6_jdpro/jd_fruit.js:535:45)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
    at async doDailyTask (/ql/scripts/6dylan6_jdpro/jd_fruit.js:232:3)
    at async jdFruit (/ql/scripts/6dylan6_jdpro/jd_fruit.js:108:7)
    at async /ql/scripts/6dylan6_jdpro/jd_fruit.js:66:7
开始发送通知...
通知标题: 东东农场

**Comment by 6dylan6** [comment]
> > 你这黑号了吧，手动进app看看
> 
> 手动可以呢。七个账号全部都不行

是啥时不行的，一开始就不行吗

**Comment by gg-shuige** [comment]
> > > 你这黑号了吧，手动进app看看
> > 
> > 
> > 手动可以呢。七个账号全部都不行
> 
> 是啥时不行的，一开始就不行吗

不是，上周不行的。有些任务第一次运行没跑，第二次才全部跑完。

**Comment by 6dylan6** [comment]
> > > > 你这黑号了吧，手动进app看看
> > > 
> > > 
> > > 手动可以呢。七个账号全部都不行
> > 
> > 
> > 是啥时不行的，一开始就不行吗
> 
> 不是，上周不行的。有些任务第一次运行没跑，第二次才全部跑完。

那搞不明白了，留个qq我远程给你看看

**Comment by 6dylan6** [comment]
还有个可能，ip黑了。是不是等一段时间就又好了

**Comment by gg-shuige** [comment]
> 还有个可能，ip黑了。是不是等一段时间就又好了

应该不是，我用win10自带的hyper-v虚拟机搭的青龙，IP不固定的。qq2021222960

**Comment by 676077263** [comment]
你这是用的arm架构的，换成x86的就兼容了，近期偷豆豆那么多还敢用。
如遇被偷了加Q群：153791115【综合维权报警群】

**Comment by gg-shuige** [comment]
> 你这是用的arm架构的，换成x86的就兼容了，近期偷豆豆那么多还敢用。 如遇被偷了加Q群：153791115 【成都综合维权报警群】已有230+抱团，各种花样方案举报，处理问题快速

我已经用了几周都可以的，是最近才不行

**Comment by 676077263** [comment]
你换成x86就明白了，代码是在更新的，以前可以用不代表现在可以

**Comment by gg-shuige** [comment]
> 你换成x86就明白了，代码是在更新的，以前可以用不代表现在可以

我用uname -a 命令查了一下，发现是X86架构，64位的。我用的是hpyer-v虚拟机
