### ISSUE TITLE
金融签到失败

### ISSUE THREAD

**Issue by yongliang-chen** [6dylan6/jdpro#192]
最近一直提示请求失败，两个账号都不行，log如下

🔔金融签到, 开始!

====================共1个京东账号Cookie=================
===========脚本执行时间：2024/01/03 16:42:04============
>>>>>>>>>>>>6Dy提醒您：有问题先更新不行在反馈>>>>>>>>>>>>>

2023/12/31 Fix双签礼包
TG频道：https://t.me/dylan_jdpro

请求失败，换个时间再试试！！！

## 执行结束...   耗时 13 秒

**Comment by hackgsl** [comment]
一样的错误
🔔金融签到, 开始!
加载sendNotify，当前版本: 20230712

====================共23个京东账号Cookie=================
===========脚本执行时间：2024/01/17 08:26:38============
>>>>>>>>>>>>6Dy提醒您：有问题先更新不行在反馈>>>>>>>>>>>>>

2023/12/31 Fix双签礼包
TG频道：https://t.me/dylan_jdpro

请求失败，换个时间再试试！！！

## 执行结束...   耗时 100 秒
