### ISSUE TITLE
萌新求教，通知一直不成功

### ISSUE THREAD

**Issue by lemoneeee** [6dylan6/jdpro#196]
资产那个任务，执行完后通知一直保持，但是比如我登录青龙，新增任务，cookie失效这些通知都是正常的。
已经在6dylan6_jdpro.js里面添加了我的SCKEY，不过我在server酱里只找到SendKey，就用这个了
下面是正常的通知
![image](https://user-images.githubusercontent.com/69039017/168034820-85e5f79c-b7de-47f6-a9c6-9bbb9771752a.png)
下面是失败的通知
![image](https://user-images.githubusercontent.com/69039017/168034875-e1250212-5594-4384-97db-ea1a91a21f34.png)

**Comment by 6dylan6** [comment]
SCKEY写到青龙config配置文件里，那里面有，补上你的key就行

**Comment by lemoneeee** [comment]
> 

![image](https://user-images.githubusercontent.com/69039017/168063108-4f08f4d6-4bf5-4552-bd9f-8c1251031637.png)
这里ye也写了，是不是依赖没装好呢 大佬

**Comment by lemoneeee** [comment]
可能是个bug   pushplus推送正常但是还是会显示报错

**Comment by 6dylan6** [comment]
你是国内机吗，api失败一般网络问题，不是缺依赖

**Comment by lemoneeee** [comment]
> 
可能我公司屏蔽了什么ip  感谢大佬
