### ISSUE TITLE
农场助力问题

### ISSUE THREAD

**Issue by penhuowa** [6dylan6/jdpro#202]
之前没什么问题。今天看了一下农场无助力，sharecode日志打印正常，农场脚本显示：
日志-东东农场
## 开始执行... 2022-05-16 17:13:12

/ql/log/6dylan6_jdpro_jd_sharecode/2022-05-16-03-15-00.log: line 5: unexpected EOF while looking for matching ``'
/ql/log/6dylan6_jdpro_jd_sharecode/2022-05-16-03-15-00.log: line 618: syntax error: unexpected end of file

🔔东东农场, 开始!
开始获取配置文件

====================共38个京东账号Cookie=================

============脚本执行时间：2022/5/16 17:13:13=============

>>>>>>>>>>>>>>6Dylan6 提示：任务正常运行中>>>>>>>>>>>>>>>

共38个京东账号

您提供了0个账号的农场助力码

开始【京东账号1】晚风与轻舟

由于您第1个京东账号未提供shareCode,将采纳本脚本自带的助力码

我去shareode.sh看了一下，这个脚本怎么在青龙环境里显示的是红色的，几个注释都是红的，我怀疑是这个脚本的问题，但是它运行正常，重新手动添加脚本也是一样，希望大佬解答。

**Comment by 6dylan6** [comment]
获取互助码的任务是不是同时在这时间运行的？

**Comment by 6dylan6** [comment]
你找到3点的那个日志文件看看能不能打开？2022-05-16-03-15-00.log

**Comment by penhuowa** [comment]
能打开，定时全部是默认的之前正常，就是别人给我说他没助力我才发现这个问题。![image](https://user-images.githubusercontent.com/51197099/168577077-b194d09c-3863-4637-aa36-fb25981c7812.png)

**Comment by 6dylan6** [comment]
![image](https://user-images.githubusercontent.com/86815944/168584074-a6605fab-8230-4437-983d-5b97191e8db6.png)
你检查下config.sh文件里面。
