### ISSUE TITLE
ck过期检测，已重新更新ck但时间显示不正确

### ISSUE THREAD

**Issue by happy-bear-x** [6dylan6/jdpro#206]
如下
【登录信息】已服务33天(账号即将到期，请重登续期)

**Comment by 6dylan6** [comment]
青龙版本多少，环境变量里ck最后更新时间有刷新吗

**Comment by happy-bear-x** [comment]
> 青龙版本多少，环境变量里ck最后更新时间有刷新吗

[v2.12.1](https://t.me/jiao_long/289)，环境遍历里面更新时间已经更新了的。环境变量中的更新时间是5-16

**Comment by 6dylan6** [comment]
你是最新版的sendnotify通知文件吗，已经修复这个问题的

**Comment by happy-bear-x** [comment]
> 你是最新版的sendnotify通知文件吗，已经修复这个问题的

我是按你的说明文档的建议更新时间设置的拉库任务定时，没有文件单独排除。

**Comment by 6dylan6** [comment]
> 如下 【登录信息】已服务33天(账号即将到期，请重登续期)

这个通知啥时发的了

**Comment by happy-bear-x** [comment]
> > 如下 【登录信息】已服务33天(账号即将到期，请重登续期)
> 
> 这个通知啥时发的了

京东资产统计

2022-05-18 08:30:45

**Comment by happy-bear-x** [comment]
未再重现
