### ISSUE TITLE
618的有木有

### ISSUE THREAD

**Issue by ROOOCCCK** [6dylan6/jdpro#213]

**Comment by 6dylan6** [comment]
有，跑吧，不过估计凉的快

**Comment by ROOOCCCK** [comment]
可以整个自定义开关呗，我找的跑不起来

**Comment by 6dylan6** [comment]
有开关，默认不运行

**Comment by ROOOCCCK** [comment]
是19那个吗

**Comment by ROOOCCCK** [comment]
找到了，还是老哥稳

**Comment by Davy103** [comment]
老哥，开关在哪里，求指点

**Comment by 112473228** [comment]
## 开始执行... 2022-05-28 23:43:05


默认不运行,设置变量export DY_19E="true"来运行


## 执行结束... 2022-05-28 23:43:05 耗时 0 秒
