### ISSUE TITLE
东东农场领水滴漏任务

### ISSUE THREAD

**Issue by yongliang-chen** [6dylan6/jdpro#218]
1、签到7天有个惊喜礼包，没有自动领
2、助力有奖任务，没有自动领

**Comment by 6dylan6** [comment]
@yongliang-chen 开始今日签到
【第7天签到】获得10g💧

开始领取惊喜礼包

等待2秒......

【惊喜礼包】获得24g💧

正常，你再试试吧，助力的跑第二次才领
