### ISSUE TITLE
部分脚本报错:URIError: URI malformed!

### ISSUE THREAD

**Issue by zgca** [6dylan6/jdpro#22]
大佬咨询下， 部分脚本运行直接`URIError: URI malformed!`， 这个报错咋解决？

**Comment by 6dylan6** [comment]
截图看下，还没有碰到这样错误

**Comment by zgca** [comment]
<img width="931" alt="image" src="https://user-images.githubusercontent.com/26037384/153810441-12a36c52-2fbf-4b9b-83b2-f8bb063327da.png">

**Comment by 6dylan6** [comment]
感觉你的ck问题啊。你换个账号试试呢

**Comment by zgca** [comment]
重新获取ck恢复了， 感谢大佬！
