### ISSUE TITLE
新农场转盘报错

### ISSUE THREAD

**Issue by EloimEssaimEmmm** [6dylan6/jdpro#227]
![image](https://github.com/6dylan6/jdpro/assets/49706708/472aca41-6670-4cd8-9a75-93a1e7686187)

**Comment by 6dylan6** [comment]
@EloimEssaimEmmm 正常，在执行一次就行了

**Comment by EloimEssaimEmmm** [comment]
> @EloimEssaimEmmm正常，在执行一次就行了

不好用的，每次执行都报这个错

**Comment by 6dylan6** [comment]
@EloimEssaimEmmm 以修
