### ISSUE TITLE
签到领现金，连接Panda失败，请重试

### ISSUE THREAD

**Issue by hushaoyu** [6dylan6/jdpro#231]
请问这个是什么问题，连接Panda只做了一次任务，后面就提示连接服务失败了。
![c177cd4a9c4c53d1ceb706b2be9b9e6](https://user-images.githubusercontent.com/25758091/170644079-4b89bf21-6edc-4db5-84eb-021a6c2467c2.png)

**Comment by 6dylan6** [comment]
连接接口不稳，问题不大。一天运行两次任务都能完成

**Comment by hushaoyu** [comment]
> 连接接口不稳，问题不大。一天运行两次任务都能完成

另外问个问题，我有个号，现金目前已经有8元了，但是发现点击兑换按钮没反应，2元的兑换额度还没有使用过的，有遇到过吗。

**Comment by 6dylan6** [comment]
抢完了。赶早试试

**Comment by hushaoyu** [comment]
> 抢完了。赶早试试

ok，谢谢。
