### ISSUE TITLE
大佬，在一个新的VPS搭建了个青龙，程序很异常，帮忙看下

### ISSUE THREAD

**Issue by lunati-wei** [6dylan6/jdpro#232]
用的青龙版本是：V2.12.2
跑依赖，完全没反应，而且里面的程序都执行不了，跑一下就直接结束 

## 开始执行... 2022-05-27 15:42:48

安装脚本所需依赖，首次拉库运行一次即可，有更新在运行

开始安装............

## 执行结束... 2022-05-27 15:42:52 耗时 4 秒

例如：种豆得豆
>>>>>>>>>>>>>>6Dylan6 提示：任务正常运行中>>>>>>>>>>>>>>>

您的种豆互助码选择的是用&隔开

共1个京东账号

您提供了0个账号的种豆得豆助力码

## 执行结束... 2022-05-27 15:48:13 耗时 7 秒

这是什么原因呢？

**Comment by 6dylan6** [comment]
没见过。新安装的？

**Comment by lunati-wei** [comment]
> 

是的，新安装的，这个怎么搞啊。。。

**Comment by 6dylan6** [comment]
全都这样吗，磁盘满了没有

**Comment by lunati-wei** [comment]
我又重新安了遍，现在好像好一些，不过跑依赖有下列错误：
## 开始执行... 2022-05-27 16:46:49

安装脚本所需依赖，首次拉库运行一次即可，有更新在运行

开始安装............

Recreating /usr/local/pnpm-global/5/node_modules
Lockfile is up-to-date, resolution step is skipped
Progress: resolved 1, reused 0, downloaded 0, added 0
Packages: +193
++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++
Progress: resolved 193, reused 0, downloaded 0, added 0
Progress: resolved 193, reused 0, downloaded 1, added 0
Progress: resolved 193, reused 0, downloaded 9, added 0
Packages are hard linked from the content-addressable store to the virtual store.
  Content-addressable store is at: /root/.pnpm-store/v3
  Virtual store is at:             node_modules/.pnpm
Progress: resolved 193, reused 0, downloaded 24, added 7
Progress: resolved 193, reused 0, downloaded 41, added 34
Progress: resolved 193, reused 0, downloaded 49, added 41
Progress: resolved 193, reused 0, downloaded 66, added 63
Progress: resolved 193, reused 0, downloaded 73, added 71
Progress: resolved 193, reused 0, downloaded 85, added 83
Progress: resolved 193, reused 0, downloaded 97, added 93
Progress: resolved 193, reused 0, downloaded 105, added 99
Progress: resolved 193, reused 0, downloaded 120, added 116
Progress: resolved 193, reused 0, downloaded 135, added 130
Progress: resolved 193, reused 0, downloaded 157, added 157
Progress: resolved 193, reused 0, downloaded 164, added 160
Progress: resolved 193, reused 0, downloaded 187, added 187
Progress: resolved 193, reused 0, downloaded 192, added 192
Progress: resolved 193, reused 0, downloaded 193, added 192

/usr/local/pnpm-global/5:
+ pm2 5.2.0
+ ts-node 10.7.0
+ tslib 2.4.0
+ typescript 4.6.3

Progress: resolved 193, reused 0, downloaded 193, added 193, done
Nothing to stop. No server is running for the store at /root/.pnpm-store/v3
Progress: resolved 0, reused 1, downloaded 0, added 0
Progress: resolved 15, reused 14, downloaded 0, added 0
 WARN  deprecated uuid@3.4.0: Please upgrade  to version 7 or higher.  Older versions may use Math.random() in certain circumstances, which is known to be problematic.  See https://v8.dev/blog/math-random for details.
 WARN  deprecated uuid@3.4.0: Please upgrade  to version 7 or higher.  Older versions may use Math.random() in certain circumstances, which is known to be problematic.  See https://v8.dev/blog/math-random for details.
 WARN  deprecated uuid@3.4.0: Please upgrade  to version 7 or higher.  Older versions may use Math.random() in certain circumstances, which is known to be problematic.  See https://v8.dev/blog/math-random for details.
Progress: resolved 112, reused 111, downloaded 0, added 0
Progress: resolved 199, reused 197, downloaded 0, added 0
Packages: +7 -2
+++++++--
Progress: resolved 199, reused 197, downloaded 0, added 6

/usr/local/pnpm-global/5:
+ pnpm 7.1.6

 WARN  Issues with peer dependencies found
.
└─┬ ts-node
  └── ✕ missing peer @types/node@"*"
Peer dependencies that should be installed:
  @types/node@"*"

Progress: resolved 199, reused 197, downloaded 1, added 7, done
 ERROR  Unable to find the global bin directory
Run "pnpm setup" to create it automatically, or set the global-bin-dir setting, or the PNPM_HOME env variable. The global bin directory should be in the PATH.
 ERROR  Unable to find the global bin directory
Run "pnpm setup" to create it automatically, or set the global-bin-dir setting, or the PNPM_HOME env variable. The global bin directory should be in the PATH.
 ERROR  Unable to find the global bin directory
Run "pnpm setup" to create it automatically, or set the global-bin-dir setting, or the PNPM_HOME env variable. The global bin directory should be in the PATH.
 ERROR  Unable to find the global bin directory
Run "pnpm setup" to create it automatically, or set the global-bin-dir setting, or the PNPM_HOME env variable. The global bin directory should be in the PATH.
 ERROR  Unable to find the global bin directory
Run "pnpm setup" to create it automatically, or set the global-bin-dir setting, or the PNPM_HOME env variable. The global bin directory should be in the PATH.
 ERROR  Unable to find the global bin directory
Run "pnpm setup" to create it automatically, or set the global-bin-dir setting, or the PNPM_HOME env variable. The global bin directory should be in the PATH.
 ERROR  Unable to find the global bin directory
Run "pnpm setup" to create it automatically, or set the global-bin-dir setting, or the PNPM_HOME env variable. The global bin directory should be in the PATH.
 ERROR  Unable to find the global bin directory
Run "pnpm setup" to create it automatically, or set the global-bin-dir setting, or the PNPM_HOME env variable. The global bin directory should be in the PATH.
 ERROR  Unable to find the global bin directory
Run "pnpm setup" to create it automatically, or set the global-bin-dir setting, or the PNPM_HOME env variable. The global bin directory should be in the PATH.
 ERROR  Unable to find the global bin directory
Run "pnpm setup" to create it automatically, or set the global-bin-dir setting, or the PNPM_HOME env variable. The global bin directory should be in the PATH.
 ERROR  Unable to find the global bin directory
Run "pnpm setup" to create it automatically, or set the global-bin-dir setting, or the PNPM_HOME env variable. The global bin directory should be in the PATH.
Collecting jieba
  Downloading jieba-0.42.1.tar.gz (19.2 MB)
Using legacy 'setup.py install' for jieba, since package 'wheel' is not installed.
Installing collected packages: jieba
    Running setup.py install for jieba: started
    Running setup.py install for jieba: finished with status 'done'
Successfully installed jieba-0.42.1

所需依赖安装完成!

## 执行结束... 2022-05-27 16:48:01 耗时 72 秒

麻烦帮我看看咋回事，还有京东保价会有，这个错误


🔔京东保价, 开始!

====================共4个京东账号Cookie=================

============脚本执行时间：2022/5/27 17:12:19=============

>>>>>>>>>>>>>>6Dylan6 提示：任务正常运行中>>>>>>>>>>>>>>>

node:internal/modules/cjs/loader:942
  throw err;
  ^

Error: Cannot find module 'jsdom'
Require stack:
- /ql/data/scripts/6dylan6_jdpro/jd_price.js
    at Module._resolveFilename (node:internal/modules/cjs/loader:939:15)
    at Module._load (node:internal/modules/cjs/loader:780:27)
    at Module.require (node:internal/modules/cjs/loader:1005:19)
    at require (node:internal/modules/cjs/helpers:102:18)
    at Object.<anonymous> (/ql/data/scripts/6dylan6_jdpro/jd_price.js:25:28)
    at Module._compile (node:internal/modules/cjs/loader:1105:14)
    at Module._extensions..js (node:internal/modules/cjs/loader:1159:10)
    at Module.load (node:internal/modules/cjs/loader:981:32)
    at Module._load (node:internal/modules/cjs/loader:827:12)
    at Function.executeUserEntryPoint [as runMain] (node:internal/modules/run_main:77:12) {
  code: 'MODULE_NOT_FOUND',
  requireStack: [ '/ql/data/scripts/6dylan6_jdpro/jd_price.js' ]
}

Node.js v18.0.0

## 执行结束... 2022-05-27 17:12:19 耗时 1 秒

**Comment by 6dylan6** [comment]
依赖安装失败，在运行一次

**Comment by lunati-wei** [comment]
最后是依赖安装不成功，后来重新多弄了几次，好像好啦，此问题关闭
