### ISSUE TITLE
美丽研究院-种植园报错

### ISSUE THREAD

**Issue by fengchenzhihun1** [6dylan6/jdpro#236]
## 开始执行... 2022-05-28 18:40:07

🔔, 开始!

====================共6个京东账号Cookie=================

============脚本执行时间：2022/5/28 18:40:07=============

>>>>>>>>>>>>>>6Dylan6 提示：任务正常运行中>>>>>>>>>>>>>>>

******开始【京东账号1】jd_74ed6fbaf8228*********

SyntaxError: Unexpected token < in JSON at position 0
获取accessToken失败

******开始【京东账号2】jd_490c773a1f3fb*********

SyntaxError: Unexpected token < in JSON at position 0
获取accessToken失败

******开始【京东账号3】jd_cjGwuhSTBVIU*********

SyntaxError: Unexpected token < in JSON at position 0
获取accessToken失败

******开始【京东账号4】ha我啊*********

SyntaxError: Unexpected token < in JSON at position 0
获取accessToken失败

******开始【京东账号5】jd_xoeWsWWomVCy*********

SyntaxError: Unexpected token < in JSON at position 0
获取accessToken失败

******开始【京东账号6】jd_585f1b4c0a864*********

SyntaxError: Unexpected token < in JSON at position 0
获取accessToken失败

**Comment by 6dylan6** [comment]
像是黑了，手动进去看看

**Comment by dotaxl** [comment]
感觉是环境问题

**Comment by fengchenzhihun1** [comment]
@6dylan6  手动可以做   账号没有被黑；但是就是报这个获取访问token失败好奇怪

**Comment by fengchenzhihun1** [comment]
@dotaxl  环境问题怎么解决 有解决办法吗 谢谢  我用的青龙最新版

**Comment by fengchenzhihun1** [comment]
感觉是依赖安装的问题APKINDEX.tar.gz
