### ISSUE TITLE
关于自动触发wskey

### ISSUE THREAD

**Issue by winsphinx** [6dylan6/jdpro#249]
我看有人提到用
NOTIFY_CKTASK = 6dylan6_jdpro/jd_wskey.py
自动触发，但我尝试了不成功。有人成功了的吗？是不支持核酸我没设置对？

**Comment by 6dylan6** [comment]
export NOTIFY_CKTASK="jd_wskey.py"

**Comment by winsphinx** [comment]
谢谢大佬，不过还是不行。
单独执行wskey.py 是能修改ck的，但是我把ck特意改错，然后执行其他任意一个脚本提示ck过期，但这时候没触发wskey。。。
我的实验流程没错误吧？

**Comment by 6dylan6** [comment]
执行的日志贴上来看下

**Comment by 344108150** [comment]
我的可以啊 
环境变量里面设置的  
![image](https://user-images.githubusercontent.com/90685197/171529963-c5f3765c-ea3d-4328-93e3-3ac445cb1903.png)

**Comment by 6dylan6** [comment]
> 我的可以啊 环境变量里面设置的 ![image](https://user-images.githubusercontent.com/90685197/171529963-c5f3765c-ea3d-4328-93e3-3ac445cb1903.png
嗯，可能他通知文件不对

**Comment by 344108150** [comment]
> > 我的可以啊 环境变量里面设置的 ![image](https://user-images.githubusercontent.com/90685197/171529963-c5f3765c-ea3d-4328-93e3-3ac445cb1903.png
> > 嗯，可能他通知文件不对

对对对 这个很重要 忘记了

**Comment by winsphinx** [comment]
![image](https://user-images.githubusercontent.com/5674054/171540693-ba0fb880-b7cd-4ebd-8080-c008ece07816.png)
有两个sendnotify，里面的是3088行的，但过一会儿会变成外面那个900行的，这是什么情况？

**Comment by 344108150** [comment]
3000多行的是作者的 900多行的是系统的 你把系统的换掉就好了

**Comment by winsphinx** [comment]
可是一会儿就会被外面900的覆盖，青龙 v2.13.2

**Comment by winsphinx** [comment]
![image](https://user-images.githubusercontent.com/5674054/171543911-65f81218-e416-4efa-b224-74d78ce2e140.png)
顺路问一下，拉取是没有日志，没有记录时间吗？怎么看她有没有成功？

**Comment by 6dylan6** [comment]
> 可是一会儿就会被外面900的覆盖，青龙 v2.13.2
> 
> 你是说，把系统的900用作者的3000手工覆盖一次？

青龙每次拉库会覆盖，放一份到deps目录就行了

**Comment by 6dylan6** [comment]
> ![image](https://user-images.githubusercontent.com/5674054/171543911-65f81218-e416-4efa-b224-74d78ce2e140.png) 顺路问一下，拉取是没有日志，没有记录时间吗？怎么看她有没有成功？

有日志update.log

**Comment by 344108150** [comment]
> > ![image](https://user-images.githubusercontent.com/5674054/171543911-65f81218-e416-4efa-b224-74d78ce2e140.png) 顺路问一下，拉取是没有日志，没有记录时间吗？怎么看她有没有成功？
> 
> 有日志update.log

新版本任务里面好像屏蔽了拉库的命令  放到订阅里面去弄 
看我的issue
https://github.com/6dylan6/jdpro/issues/251

**Comment by winsphinx** [comment]
感谢各位的帮助！:thx:

**Comment by cy920820** [comment]
> deps

这个 deps 目录，我在 ql 目录下没有找到？

**Comment by cy920820** [comment]
> > > 可是一会儿就会被外面900的覆盖，青龙 v2.13.2
> > > 你是说，把系统的900用作者的3000手工覆盖一次？
> > 
> > 
> > 青龙每次拉库会覆盖，放一份到deps目录就行了
> 
> 这个 deps 目录，我在 ql 目录下没有找到？

版本是作用 一键安装中指定的版本，是不是就不需要这一步了？

**Comment by 6dylan6** [comment]
@cy920820 这个deps目录需要进容器才有的。docker exec -it qinglong bash， 你现在啥问题了。

**Comment by cy920820** [comment]
再尝试使用 wskey 脚本，但是发现 sendnotify.js 没有一个是 3K 行的，再想是不是被覆盖掉了

**Comment by QZAiXH** [comment]
@6dylan6 /ql/data/deps是这个路径吗？我怎么感觉还是会被覆盖
