### ISSUE TITLE
东东农场问题

### ISSUE THREAD

**Issue by chenwingsing** [6dylan6/jdpro#25]
由于您第1个京东账号未提供shareCode,将采纳本脚本自带的助力码？  这个sharecode是怎么提供的？

**Comment by 6dylan6** [comment]
跑获取互助码任务会获取到，需要先跑一遍农场任务。在跑获取

**Comment by chenwingsing** [comment]
已经运行好几天了，不知道为啥还是这样，所以才过来问，而且我单独运行sharecode，日志中能显示农场的互助码

**Comment by chenwingsing** [comment]
咦，不过我发现刚才我自己运行了sharecode，农场又可以互助了，好奇怪

**Comment by chenwingsing** [comment]
咦，不过我发现刚才我自己运行了sharecode，农场又可以互助了，好奇怪

**Comment by biewenwoshishui021** [comment]
请问一下，我弄成sharecode.sh跑完了，能输出，但跑fruit不能助力内置的，每天3次助力都不助力，请问怎么回事？
