### ISSUE TITLE
jx_cxjhelp.js 京喜抽现金不能自动提现

### ISSUE THREAD

**Issue by leifeng-N** [6dylan6/jdpro#25]

**Comment by leifeng-N** [comment]
开始抽奖和提现：

开始【账号1】jd_

当前有1次抽奖机会！
开始第1次抽奖:
----获得红包：0.20 🧧

本次抽奖获得红包总计：0.2元

开始【账号2】jd_

当前有0次抽奖机会！

**Comment by 6dylan6** [comment]
@leifeng-N 你没有可提现的
