### ISSUE TITLE
为啥我拉库的命令好像没有执行，手动点了也没反应，青龙版本2.13.1

### ISSUE THREAD

**Issue by 344108150** [6dylan6/jdpro#251]
连日志都没生成  日志还是5.28号的

**Comment by anxiaolei** [comment]
版本问题，我之前也是版本，依赖都提示失败，没有日志，然后重装2.11解决

**Comment by 344108150** [comment]
> 版本问题，我之前也是版本，依赖都提示失败，没有日志，然后重装2.11解决

这就尴尬了。。。。

**Comment by 6dylan6** [comment]
新版本俺还没用过。不会用，哈哈

**Comment by 344108150** [comment]
> 新版本俺还没用过。不会用，哈哈

大佬有空研究一下呗  新版本好像出了个订阅的功能  把repo rew 命令放里面去了  
不知道是不是 我试了一下 没搞懂 哈哈

**Comment by 344108150** [comment]
研究了一下 可以了 
原来是因为他那个自动解析有的问题  收到调整一下就好 
![image](https://user-images.githubusercontent.com/90685197/171536769-66c87ccc-a0ef-4276-92cc-bcfaf306cf28.png)
![image](https://user-images.githubusercontent.com/90685197/171536819-872dda38-6179-4875-89de-a8dda2b21e40.png)

**Comment by gujiwuqing** [comment]
<img width="625" alt="image" src="https://user-images.githubusercontent.com/44566835/197371995-9ca86705-7b11-4ed3-a222-110bbd9cafcb.png">

**Comment by gujiwuqing** [comment]
> @gujiwuqing #251 订阅看看对不对

应该是 我直接点的复制 感觉不太对劲 前面是需要ql repo再加上链接吗

**Comment by gujiwuqing** [comment]
> @gujiwuqing #251 订阅看看对不对

ok了 是我误解了 链接应该是仓库的地址 谢了

**Comment by xhanglizhu** [comment]
拉库了之后，脚本管理里只有2个脚本。。。 什么情况？ 国内地址ql repo https://js.dayplus.xyz/https://github.com/6dylan6/jdpro.git "jd_|jx_|jddj_" "backUp" "^jd[^_]|USER|JD|function|sendNotify"

**Comment by Unclefat-hub** [comment]
> @xhanglizhu 你参考配置截图，你可能订阅配置错误

大佬，按照你的配置截图没问题了，拉库正常，但是每个任务都提示ccokie不对，api请求失败，可否百忙之中帮助下
![微信截图_20221104201441](https://user-images.githubusercontent.com/117451954/199970549-af0e1ca0-4a73-4f05-95cb-f8ee5922c6c8.png)
![微信截图_20221104200945](https://user-images.githubusercontent.com/117451954/199970556-482fc87f-a6a5-44f5-9ae2-66227ac06e18.png)

万分感谢

**Comment by Unclefat-hub** [comment]
> @xhanglizhu 你参考配置截图，你可能订阅配置错误

大佬我拉库成功了，部分任务运行没问题，部分任务出现这个错误，可否请教是怎么回事
![微信截图_20221104203651](https://user-images.githubusercontent.com/117451954/199974852-b1c45d84-ac6d-459e-ab33-41330497a751.png)
![微信截图_20221104203635](https://user-images.githubusercontent.com/117451954/199974862-83a17fac-852c-4d7d-b44a-857267932d82.png)
![微信截图_20221104201441](https://user-images.githubusercontent.com/117451954/199974865-f5336448-c3b2-4b9b-8ff7-b292a6b24187.png)

**Comment by chpter** [comment]
为什么提示我网络问题拉库失败呢？

**Comment by xhanglizhu** [comment]
> > @xhanglizhu 你参考配置截图，你可能订阅配置错误
> 
> 大佬我拉库成功了，部分任务运行没问题，部分任务出现这个错误，可否请教是怎么回事 ![微信截图_20221104203651](https://user-images.githubusercontent.com/117451954/199974852-b1c45d84-ac6d-459e-ab33-41330497a751.png) ![微信截图_20221104203635](https://user-images.githubusercontent.com/117451954/199974862-83a17fac-852c-4d7d-b44a-857267932d82.png) ![微信截图_20221104201441](https://user-images.githubusercontent.com/117451954/199974865-f5336448-c3b2-4b9b-8ff7-b292a6b24187.png)

要添加axios依赖

**Comment by Unclefat-hub** [comment]
> > > @xhanglizhu 你参考配置截图，你可能订阅配置错误
> > 
> > 
> > 大佬我拉库成功了，部分任务运行没问题，部分任务出现这个错误，可否请教是怎么回事 ![微信截图_20221104203651](https://user-images.githubusercontent.com/117451954/199974852-b1c45d84-ac6d-459e-ab33-41330497a751.png) ![微信截图_20221104203635](https://user-images.githubusercontent.com/117451954/199974862-83a17fac-852c-4d7d-b44a-857267932d82.png) ![微信截图_20221104201441](https://user-images.githubusercontent.com/117451954/199974865-f5336448-c3b2-4b9b-8ff7-b292a6b24187.png)
> 
> 要添加axios依赖

这个加上去了 只有canvas这个死活加不上

**Comment by 3225579752** [comment]
> 拉库了之后，脚本管理里只有2个脚本。。。 什么情况？ 国内地址ql repo https://js.dayplus.xyz/https://github.com/6dylan6/jdpro.git "jd_|jx_|jddj_" "backUp" "^jd[^_]|USER|JD|function|sendNotify"
> 
> 订阅管理里，执行后，日志： 开始执行... 2022-11-01 23:13:50 开始更新仓库：/ql/data/repo/6dylan6_jdpro Fetching origin 更新/ql/data/repo/6dylan6_jdpro成功... 开始执行... 2022-11-01 23:13:50 执行结束... 2022-11-01 23:14:10 耗时 20 秒 执行结束... 2022-11-01 23:14:10 耗时 20 秒

同样的问题
