### ISSUE TITLE
创建 定时任务后   无法执行任务是什么问题？日志 就“任务未运行”这几个字

### ISSUE THREAD

**Issue by sonemacho** [6dylan6/jdpro#251]
创建 定时任务后   无法执行任务是什么问题？
![PixPin_2024-03-13_17-33-30](https://github.com/6dylan6/jdpro/assets/89234834/0de3b91d-9706-4e74-a5ec-4fb9d7648e0e)
日志 就“任务未运行”这几个字

**Comment by 6dylan6** [comment]
@sonemacho 配置订阅

**Comment by 6dylan6** [comment]
@sonemacho 更新
