### ISSUE TITLE
物流积分换京豆和摇京豆有问题

### ISSUE THREAD

**Issue by lyb1992** [6dylan6/jdpro#254]
大佬，前段时间，一直有运行积分换京东成功，之前试过，快到期的京东换了积分，然后再把积分换了京东，
最近积分换京东，一直提示风险，无法兑换，京豆换成了积分，无法兑换回来京豆了。

是账号问题吗？还是更改了规则，无法使用了？

另外，摇京豆，一直无法运行成功。 403；

请大佬帮忙看看问题

**Comment by 6dylan6** [comment]
@lyb1992 摇京豆删了，换积分风控没法换

**Comment by lyb1992** [comment]
好的，谢谢，
轻松赚豆是不是也没修复

**Comment by 6dylan6** [comment]
@lyb1992 赚豆好的啊
