### ISSUE TITLE
CK作废这个脚本的不理解

### ISSUE THREAD

**Issue by gaojianpete** [6dylan6/jdpro#258]
我看这个脚本每天都会运行 我就手贱手动运行了一下
然后我所有的变量全部过期了   o(╥﹏╥)o
然后我重新填写正确的变量之后 他自动运行会再给kill了吗

**Comment by 6dylan6** [comment]
大哥，你会玩啊。就是ck泄露了，给作废用的，没事用这个干啥。哈哈

**Comment by gaojianpete** [comment]
可是我看他下次运行时间是明天呀 明天他不会自动运行吗

**Comment by gaojianpete** [comment]
新版的2.13青龙

**Comment by 6dylan6** [comment]
发我看下你拉库配置，可能错了

**Comment by gaojianpete** [comment]
![微信截图_20220603140154](https://user-images.githubusercontent.com/25995439/171796117-adea847e-c252-4ca9-8fda-f6a5e1f787a0.png)

**Comment by gaojianpete** [comment]
我也感觉我写错了 但是我有能拉到

**Comment by 6dylan6** [comment]
点开里面详细配置

**Comment by gaojianpete** [comment]
![Dingtalk_20220603140332](https://user-images.githubusercontent.com/25995439/171796272-ebf060b1-e035-438f-be40-53f328618d84.jpg)

**Comment by gaojianpete** [comment]
我没怎么改 我就直接给他扔上去了 应该加上白名单的对吧

**Comment by gaojianpete** [comment]
大佬 给页面加个配置信息吧 让我这么蠢的人直接贴上去 我应该是没加白名单

**Comment by 6dylan6** [comment]
https://user-images.githubusercontent.com/90685197/171536819-872dda38-6179-4875-89de-a8dda2b21e40.png

**Comment by gaojianpete** [comment]
ok  谢谢  感谢大佬 我是笨比

**Comment by 6dylan6** [comment]
都删掉重新拉吧。很多不需要的都拉进去了

**Comment by gaojianpete** [comment]
已经搞定了 他自动把那些任务给删除了
