### ISSUE TITLE
telegram通知用代理是不是不能发送通知

### ISSUE THREAD

**Issue by jaesony** [6dylan6/jdpro#258]
青龙装在群晖里。群晖直接科学上网，telegram机器人可以发送通知。群晖正常设置的话，给telegram机器人设置代理则不能发送通知
京东资产统计, 失败! 原因: Error: Cannot find module 'tunnel'

**Comment by 6dylan6** [comment]
@jaesony ## 3. Telegram
## 下方填写自己申请@BotFather的Token，如10xxx4:AAFcqxxxxgER5uw
export TG_BOT_TOKEN="xxx"
## 下方填写 @getuseridbot 中获取到的纯数字ID
export TG_USER_ID="xxx"
## Telegram 代理IP（选填）
## 下方填写代理IP地址，代理类型为 http，比如您代理
## 如需使用，请赋值代理地址链接，并自行解除下一行的注释
export TG_API_HOST="xxx"
