### ISSUE TITLE
大佬 这个覆盖notify.sendNotify 这个怎么处理

### ISSUE THREAD

**Issue by gaojianpete** [6dylan6/jdpro#263]
每天都需要手动更换一下这个文件 为了发一对一推送 
我应该怎么一次解决掉他
❌ 京东资产统计, 失败! 原因: TypeError: notify.sendNotifybyWxPucher is not a function!

**Comment by EchoChan314** [comment]
进入deps目录，下载最新的sendNotify

**Comment by gaojianpete** [comment]
我的deps目录下面啥都没有

**Comment by gaojianpete** [comment]
已解决 找到了deps目录
