### ISSUE TITLE
京东财富岛问题

### ISSUE THREAD

**Issue by chenwingsing** [6dylan6/jdpro#264]
5个号都是这样，黑号了吗
******开始【京东账号1】Mr陈哥哥*********

获取用户信息：success

当前等级:undefined,金币:undefined,财富值:undefined,连续营业天数:undefined,离线收益:undefined

寻宝

❗️京喜财富岛, 错误!
TypeError: Cannot read properties of undefined (reading 'filter')
    at cfd (/ql/scripts/6dylan6_jdpro/jd_cfd.js:145:48)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
    at async /ql/scripts/6dylan6_jdpro/jd_cfd.js:88:7

**Comment by 6dylan6** [comment]
@chenwingsing 进app看看能不能进去活动了

**Comment by chenwingsing** [comment]
> @chenwingsing 进app看看能不能进去活动了

可以进  5个号都能进去的

**Comment by 6dylan6** [comment]
那是每次运行都这错么。

**Comment by chenwingsing** [comment]
可以进去

获取 Outlook for iOS<https://aka.ms/o0ukef>
________________________________
发件人: 6dylan6 ***@***.***>
发送时间: Saturday, June 4, 2022 5:33:48 PM
收件人: 6dylan6/jdpro ***@***.***>
抄送: chenwingsing ***@***.***>; Mention ***@***.***>
主题: Re: [6dylan6/jdpro] 京东财富岛问题 (Issue #264)


@chenwingsing<https://github.com/chenwingsing> 进app看看能不能进去活动了

―

**Comment by chenwingsing** [comment]
对，每次都这样

获取 Outlook for iOS<https://aka.ms/o0ukef>
________________________________
发件人: 6dylan6 ***@***.***>
发送时间: Saturday, June 4, 2022 8:22:26 PM
收件人: 6dylan6/jdpro ***@***.***>
抄送: chenwingsing ***@***.***>; Mention ***@***.***>
主题: Re: [6dylan6/jdpro] 京东财富岛问题 (Issue #264)


那是每次运行都这错么。

―

**Comment by 6dylan6** [comment]
这有点迷了，可能网络问题。啥时开始的。看看日志

**Comment by chenwingsing** [comment]
不知道为啥3 4 5 月份的日志不见了 。目前2月份都是正常的，最近的6月份一直这个错误，重新安装了也一样

**Comment by chenwingsing** [comment]
获取签名参数成功！
fp: 打码
token: 打码
return algo.HmacSHA512(str,tk)}

******开始【京东账号1】Mr陈哥哥*********

获取用户信息：success


当前等级:undefined,金币:undefined,财富值:undefined,连续营业天数:undefined,离线收益:undefined

寻宝

❗️京喜财富岛, 错误!
TypeError: Cannot read properties of undefined (reading 'filter')
    at cfd (/ql/scripts/6dylan6_jdpro/jd_cfd.js:145:48)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
    at async /ql/scripts/6dylan6_jdpro/jd_cfd.js:88:7

**Comment by chenwingsing** [comment]
我看issue#149也是这个问题

**Comment by 6dylan6** [comment]
@chenwingsing 不清楚了，我这边正常，可能网络问题
