### ISSUE TITLE
物流积分换豆

### ISSUE THREAD

**Issue by BNDou** [6dylan6/jdpro#272]
6佬，我看到物流积分换豆页面的“活动规则”好像有点变化，京豆换的积分，不能用来换回京豆。

如图：
![Screenshot_2024-04-11-16-46-43-567_com.jingdong.app.mall-edit.jpg](https://github.com/6dylan6/jdpro/assets/67632799/5edfcf09-abcc-40f8-bc5f-1ec5b461db74)

**Comment by 6dylan6** [comment]
@BNDou 正常换
