### ISSUE TITLE
无法接收推送消息

### ISSUE THREAD

**Issue by YAOmeihah** [6dylan6/jdpro#273]
我把GitHub上的sendNotify 拷贝到deps后  还是 不能推送  是需要修改  deps的sendNotify  环境变量吗    ， 我发现好多地方都有这个sendNotify 文件
![image](https://user-images.githubusercontent.com/51868611/172534689-64e410a7-fe5f-4ac2-80f8-81a88f4eacf7.png)
![image](https://user-images.githubusercontent.com/51868611/172534773-3f6ee72a-3fe5-4da5-8a2d-cf913500177d.png)
![1654664187(1)](https://user-images.githubusercontent.com/51868611/172534917-ac6e0059-95f4-46bf-8b23-ac62ec5ba660.jpg)
我修改  图一的  变量 是会推送成功的  ，但是 过段时间  3000行的  会变成900行的  里面的  添加的东西也没有了

**Comment by YAOmeihah** [comment]
所以是 拷贝之后还有其他 操作吗

**Comment by 6dylan6** [comment]
不管哪个都能推送，只是3000多行的功能多点，可以一对一，你使用企业微信推送么

**Comment by 6dylan6** [comment]
你变量要写到config.sh，不然肯定会被覆盖了

**Comment by YAOmeihah** [comment]
我用的WxPusher，配置文件里面没有这个 变量  是需要自己加嘛

**Comment by YAOmeihah** [comment]
![image](https://user-images.githubusercontent.com/51868611/172540668-1d6b2b8f-b4e1-4fb7-9195-e4b67079aa49.png)
是这样嘛 大佬

**Comment by YAOmeihah** [comment]
我懂了  可以了
