### ISSUE TITLE
新农场报错，昨天还没问题的

### ISSUE THREAD

**Issue by ysf37** [6dylan6/jdpro#277]
![1713495389162](https://github.com/6dylan6/jdpro/assets/19886505/69822504-33f7-48c3-841e-91d477907421)

大佬，有时间看看这个，昨天还可以的
![00696514](https://github.com/6dylan6/jdpro/assets/19886505/50d4dd24-65f6-494f-8612-c8ba829e8a65)

**Comment by 6dylan6** [comment]
@ysf37 更新修复

**Comment by ysf37** [comment]
好了，感谢大佬
