### ISSUE TITLE
没有使用 wskey 自动刷新 ck？

### ISSUE THREAD

**Issue by cy920820** [6dylan6/jdpro#278]
<img width="511" alt="image" src="https://user-images.githubusercontent.com/21211512/173089893-ebe6fb2b-5943-4325-9371-5fd02bd2fc28.png">

**Comment by cy920820** [comment]
手动执行的

<img width="520" alt="image" src="https://user-images.githubusercontent.com/21211512/173090308-7fd16e44-c7bb-417b-8b78-2275adda407f.png">

**Comment by 6dylan6** [comment]
你没有配置咋刷新

**Comment by cy920820** [comment]
我配置的不对吗？

**Comment by 6dylan6** [comment]
@cy920820 参考wskey环境变量的使用。

**Comment by cy920820** [comment]
参考了 还是不太清楚为什么当 ck 失效后没有自动刷新？

**Comment by 6dylan6** [comment]
@cy920820 不用等失效，定时转就行了
