### ISSUE TITLE
晒单评价运行错误

### ISSUE THREAD

**Issue by lyb1992** [6dylan6/jdpro#279]
日志信息：
当前使用内置sign，控制变量SIGN_URL
sign获取失败,请检查网络；

之前也没有设置变量，但是能运行晒单。现在执行不了

**Comment by 6dylan6** [comment]
@lyb1992 不是我库的吧，我这正常

**Comment by lyb1992** [comment]
之前的QL出问题了，我重新安装，拉库的，但以前也是没设置变量的

**Comment by lyb1992** [comment]
是这个库，重新安装后，只拉了这个库

**Comment by lyb1992** [comment]
这个内置sign是运行什么任务才会拿到吗？

**Comment by lyb1992** [comment]
好像是青龙面板的问题，重新安装的是最新版本，
刚刚再试了一遍，再其他路径下，安装2.11.3的版本，将之前的配置和文件复制过去新路径，晒单评价就可以用了，

**Comment by 6dylan6** [comment]
@lyb1992 不知道你什么情况，和版本没关系

**Comment by xiaozhang404** [comment]
可能是网络问题，我也遇到这个情况了，关闭了本机的clash后，可以正常运行
