### ISSUE TITLE
M京东签到挂了  403

### ISSUE THREAD

**Issue by gujiwuqing** [6dylan6/jdpro#280]
<img width="563" alt="image" src="https://user-images.githubusercontent.com/44566835/173172519-db0f6bc3-d194-4f4f-94a6-9b706f0914f7.png">
老哥 M京东签到这个挂了

**Comment by 6dylan6** [comment]
@gujiwuqing 哪个？

**Comment by gujiwuqing** [comment]
M京东签到这个



| |
***@***.***
|
|
***@***.***
|




---- 回复的原邮件 ----
| 发件人 | ***@***.***> |
| 日期 | 2022年06月11日 14:27 |
| 收件人 | ***@***.***> |
| 抄送至 | ***@***.******@***.***> |
| 主题 | Re: [6dylan6/jdpro] M京东签到挂了  403 (Issue #280) |

@gujiwuqing 哪个？

**Comment by 6dylan6** [comment]
@gujiwuqing 没有这个任务

**Comment by gujiwuqing** [comment]
> @gujiwuqing 没有这个任务

呃。好吧

**Comment by gujiwuqing** [comment]
> @gujiwuqing 没有这个任务

老哥 想问问 那个助力码能自己填一下吗 我想和我其他的号互助下

**Comment by 6dylan6** [comment]
@gujiwuqing 自动搜集互助码的，运行获取互助码任务

**Comment by gujiwuqing** [comment]
好的



| |
***@***.***
|
|
***@***.***
|




---- 回复的原邮件 ----
| 发件人 | ***@***.***> |
| 日期 | 2022年06月11日 15:08 |
| 收件人 | ***@***.***> |
| 抄送至 | ***@***.******@***.***> |
| 主题 | Re: [6dylan6/jdpro] M京东签到挂了  403 (Issue #280) |

@gujiwuqing 自动搜集互助码的，运行获取互助码任务
