### ISSUE TITLE
农场助力失败，新旧农场都是同样的提示。求求解决

### ISSUE THREAD

**Issue by jiojiojackson** [6dylan6/jdpro#284]
![农场](https://github.com/6dylan6/jdpro/assets/128605081/a6daae44-d9f8-4e0f-a811-59dc15535039)

**Comment by 6dylan6** [comment]
@jiojiojackson 任务正常吗

**Comment by jiojiojackson** [comment]
> @jiojiojackson 任务正常吗

农场任务都正常，就是助力任务不正常。

**Comment by jiojiojackson** [comment]
> @jiojiojackson 任务正常吗

已经更新了，还是同样的报错。今天才出现这个问题的。

**Comment by 6dylan6** [comment]
@jiojiojackson 脚本管理找到fruit_helpcode_new看看有没有内容

**Comment by likefu40** [comment]
同样的问题

**Comment by 6dylan6** [comment]
@likefu40 更新试试，任务要正常跑完才会有本地缓存

**Comment by likefu40** [comment]
> @likefu40 更新试试，任务要正常跑完才会有本地缓存
重现安装后，把旧的备份，导入后，重启了一下，目前助力正常运行

**Comment by likefu40** [comment]
> > @likefu40 更新试试，任务要正常跑完才会有本地缓存
> > 重现安装后，把旧的备份，导入后，重启了一下，目前助力正常运行

今天发现又不能助力了，可能是助力4.29版本有问题之前的旧版本能正常助力

**Comment by 6dylan6** [comment]
@likefu40 日志贴出看看

**Comment by jiojiojackson** [comment]
今天又可以了。
