### ISSUE TITLE
口令转链接不能用了

### ISSUE THREAD

**Issue by Jerry-zx** [6dylan6/jdpro#29]
口令转链接，大佬看看
![image](https://github.com/6dylan6/jdpro/assets/84613314/a79f9c54-f4dd-43f2-be0a-635e7057a1e3)

**Comment by 6dylan6** [comment]
@xie-zhixiang 已修复

**Comment by Jerry-zx** [comment]
好的，谢谢，已验证正常。

**Comment by Jerry-zx** [comment]
> @xie-zhixiang 已修复

好的，谢谢，已验证正常

**Comment by Jerry-zx** [comment]
好像又不行了，大佬看看
