### ISSUE TITLE
保价脚本报错

### ISSUE THREAD

**Issue by Pengfei00** [6dylan6/jdpro#298]
dom.window.JAB is not a constructor

**Comment by moumouren** [comment]
我得今天也报错了，
❌ 京东价保, 失败! 原因: TypeError: Cannot read properties of undefined (reading 'getToken')!。。

之前正常的

**Comment by moumouren** [comment]
> @moumouren 刚跑一遍，正常的，你换时间再试试

我现在又跑了一次，还是提示这个，前几天还没问题的

**Comment by moumouren** [comment]
> @moumouren 那可能ip问题，请求jd失败

这玩意还会导致被封ip吗，就是按照Readme 设置了几个并发的 

`极速版签到建议并发，号多跑很久的，一个号要30多分钟。。


task 6dylan6_jdpro_jd_speed_sign.js conc JD_COOKIE （具体任务路径不同版本不一样，按自己的写）


3、保价建议并发，否则可能前几个号正常跑，后面会报频繁！`

**Comment by moumouren** [comment]
> @moumouren 猜测，所有号都这样么，那就和网络有关系

是的 所有的都这样

**Comment by moumouren** [comment]
> @moumouren 换ip试试了

好的

**Comment by Pengfei00** [comment]
@6dylan6 代码第205行 window没有挂上JAB这个对象 - - JAB是什么

**Comment by Pengfei00** [comment]
@6dylan6 
去最新网页版上看了下请求 没有用到$.token 相关参数 将 JAB $.token相关注释掉之后已正常运行

**Comment by Pengfei00** [comment]
> > @moumouren 换ip试试了
> 
> 好的

你这个和我一个问题 你换ip有用吗？

**Comment by Pengfei00** [comment]
> @Pengfei00 进app申请记录看看，申请成功没有呢

APP上显示成功的 我提个mr 你试试吧 没问题可以合一下 #299

**Comment by moumouren** [comment]
> > > @moumouren 换ip试试了
> > 
> > 
> > 好的
> 
> 你这个和我一个问题 你换ip有用吗？

没有解决等你的pr，我再更新看看了
