### ISSUE TITLE
为什么JD_COOKIE失效不能自动禁用，要加什么变量吗？

### ISSUE THREAD

**Issue by amxoy** [6dylan6/jdpro#3]

**Comment by 6dylan6** [comment]
需要变量。export NOTIFY_AUTOCHECKCK=true

**Comment by shaufo** [comment]
true前后需要加“”吗？

**Comment by 6dylan6** [comment]
@shaufo export NOTIFY_AUTOCHECKCK=true

**Comment by shaufo** [comment]
好的，感谢

**Comment by 6dylan6** [comment]
@shaufo 在配置管理里配置，不要在环境变量

**Comment by shaufo** [comment]
是的，刚开始是在环境变量里面写的，后来在配置文件最下面发先有export XXXX=""，才知道要在配置文件那里写，但是由于配置文件那里的上面的export XXXX=后面都有“”，所以才有上面的疑问。感谢你的答复。
