### ISSUE TITLE
通知账号不显示备注，日志中用户名与JD_COOKIE里面的pin不一样

### ISSUE THREAD

**Issue by hackgsl** [6dylan6/jdpro#306]
最近发现京东资产统计、农场可收取等通知里面账号的备注没有显示
之前是：【账号6🆔】6.弟，
现在是：【账号6🆔】tgp64umv4ian(已实名)
然后我看日志里面显示的账号跟我JD_COOKIE里面的pin不一样，
我试了下把JD_COOKIE里面的pin改成跟日志里面的用户名一样后，京东资产统计通知账户名正常，但是一些脚本运行后报错
******开始【京东账号6】tgp64umv4ian*********
officialAccountSign_homePage TypeError: Cannot read properties of undefined (reading 'scanTaskList')

**Comment by 6dylan6** [comment]
不能改ck的pin，你备注呀

**Comment by hackgsl** [comment]
> 不能改ck的pin，你备注呀
有备注的，配置也没变过，然后最近出现同一个账户显示不一样，【账号10 jd_43492zf2x36j】这里的jd_开头跟pin里面的不一样，不知道这个是哪来的，导致发送通知时跟备注匹配不上所以不会显示备注信息

资产统计：
【账号10 jd_43492zf2x36j】广西小米蕉5斤 (老农场)
东东农场-任务：
【京东账号10🆔】10.细
【水果名称】广西小米蕉5斤
新农场：
京东账号10🆔】10.细
【水果名称】惠寻京东自有品牌 鲜肉肉包子1kg（约12个）大肉包 加热即食早茶点心

**Comment by noonecheck** [comment]
> > 不能改ck的pin，你备注呀
> > 有备注的，配置也没变过，然后最近出现同一个账户显示不一样，【账号10 jd_43492zf2x36j】这里的jd_开头跟pin里面的不一样，不知道这个是哪来的，导致发送通知时跟备注匹配不上所以不会显示备注信息
> 
> 资产统计： 【账号10 jd_43492zf2x36j】广西小米蕉5斤 (老农场) 东东农场-任务： 【京东账号10🆔】10.细 【水果名称】广西小米蕉5斤 新农场： 京东账号10🆔】10.细 【水果名称】惠寻京东自有品牌 鲜肉肉包子1kg（约12个）大肉包 加热即食早茶点心

大佬，怎么解决的，可以显示设置备注吗，我也出现对不上的情况了

**Comment by noonecheck** [comment]
> > 不能改ck的pin，你备注呀
> > 有备注的，配置也没变过，然后最近出现同一个账户显示不一样，【账号10 jd_43492zf2x36j】这里的jd_开头跟pin里面的不一样，不知道这个是哪来的，导致发送通知时跟备注匹配不上所以不会显示备注信息
> 
> 资产统计： 【账号10 jd_43492zf2x36j】广西小米蕉5斤 (老农场) 东东农场-任务： 【京东账号10🆔】10.细 【水果名称】广西小米蕉5斤 新农场： 京东账号10🆔】10.细 【水果名称】惠寻京东自有品牌 鲜肉肉包子1kg（约12个）大肉包 加热即食早茶点心

大佬，怎么解决的，可以显示设置备注吗，我也出现对不上的情况了

**Comment by hackgsl** [comment]
> > > 不能改ck的pin，你备注呀
> > > 有备注的，配置也没变过，然后最近出现同一个账户显示不一样，【账号10 jd_43492zf2x36j】这里的jd_开头跟pin里面的不一样，不知道这个是哪来的，导致发送通知时跟备注匹配不上所以不会显示备注信息
> > 
> > 
> > 资产统计： 【账号10 jd_43492zf2x36j】广西小米蕉5斤 (老农场) 东东农场-任务： 【京东账号10🆔】10.细 【水果名称】广西小米蕉5斤 新农场： 京东账号10🆔】10.细 【水果名称】惠寻京东自有品牌 鲜肉肉包子1kg（约12个）大肉包 加热即食早茶点心
> 
> 大佬，怎么解决的，可以显示设置备注吗，我也出现对不上的情况了

删掉脚本管理里面的：CKName_cache.json，然后重新跑一次看下

**Comment by hackgsl** [comment]
> > > 不能改ck的pin，你备注呀
> > > 有备注的，配置也没变过，然后最近出现同一个账户显示不一样，【账号10 jd_43492zf2x36j】这里的jd_开头跟pin里面的不一样，不知道这个是哪来的，导致发送通知时跟备注匹配不上所以不会显示备注信息
> > 
> > 
> > 资产统计： 【账号10 jd_43492zf2x36j】广西小米蕉5斤 (老农场) 东东农场-任务： 【京东账号10🆔】10.细 【水果名称】广西小米蕉5斤 新农场： 京东账号10🆔】10.细 【水果名称】惠寻京东自有品牌 鲜肉肉包子1kg（约12个）大肉包 加热即食早茶点心
> 
> 大佬，怎么解决的，可以显示设置备注吗，我也出现对不上的情况了

删掉脚本管理里面的：CKName_cache.json，然后重新跑一次看下

**Comment by noonecheck** [comment]
> > > > 不能改ck的pin，你备注呀
> > > > 有备注的，配置也没变过，然后最近出现同一个账户显示不一样，【账号10 jd_43492zf2x36j】这里的jd_开头跟pin里面的不一样，不知道这个是哪来的，导致发送通知时跟备注匹配不上所以不会显示备注信息
> > > 
> > > 
> > > 资产统计： 【账号10 jd_43492zf2x36j】广西小米蕉5斤 (老农场) 东东农场-任务： 【京东账号10🆔】10.细 【水果名称】广西小米蕉5斤 新农场： 京东账号10🆔】10.细 【水果名称】惠寻京东自有品牌 鲜肉肉包子1kg（约12个）大肉包 加热即食早茶点心
> > 
> > 大佬，怎么解决的，可以显示设置备注吗，我也出现对不上的情况了
> 
> 删掉脚本管理里面的：CKName_cache.json，然后重新跑一次看下

好的，谢谢。但是在脚本里面找不到这个CKName_cache.json，也试了找Name关键词，也没有这个脚本
