### ISSUE TITLE
批量取关店铺和商品, 失败! 原因: AggregateError!

### ISSUE THREAD

**Issue by rongyihui** [6dylan6/jdpro#307]
---------------API代理模式（非白名单）已开启---------------

Tips：查询关注的商品容易403，支持DY_PROXY
使用代理IP：111.174.217.218:37475
使用代理IP：171.42.101.214:37934
"Response code 503 (Service Unavailable)"
批量取关店铺和商品 API请求失败，请检查网路重试

❌ 批量取关店铺和商品, 失败! 原因: AggregateError!

🔔批量取关店铺和商品, 结束! 🕛 13.278 秒

![微信截图_20240524201149](https://github.com/6dylan6/jdpro/assets/22475635/a2a1e309-d971-4955-a186-1e65d1ad29f4)

**Comment by 6dylan6** [comment]
@rongyihui 你代理有问题，不用试试

**Comment by rongyihui** [comment]
感谢，貌似是被拦截了，现在好了
