### ISSUE TITLE
你好，请问

### ISSUE THREAD

**Issue by WuhuGoldPilot** [6dylan6/jdpro#312]
wskey中的
变量名: JD_WSCK 参数: pin=xxxx;wskey=xxxx;

请问wskey填的是什么？

**Comment by WuhuGoldPilot** [comment]
是什么app来的@[6dylan6](https://github.com/6dylan6)

**Comment by WuhuGoldPilot** [comment]
@6dylan6 是不是就是网页版登陆的pt-key，只不过是命名不一样而已？

**Comment by WuhuGoldPilot** [comment]
@6dylan6 https://home.m.jd.com/myJd/newhome.action?sceneval=2&ufc=&是不是不能通过这个网址获取的？

**Comment by WuhuGoldPilot** [comment]
@6dylan6 感谢

**Comment by winsphinx** [comment]
搭车问一下，apple有什么工具抓包？

**Comment by xtexChooser** [comment]
那你可以把这个Issue close了（
