### ISSUE TITLE
单个店铺签到 jd_dpqd_single.js 为什么定时时间是每月2号的29点？！

### ISSUE THREAD

**Issue by donald001** [6dylan6/jdpro#318]
我发现单个店铺签到 jd_dpqd_single.js 在青龙上显示cron是 `7 7 29 2 *` 也就是定时时间是每月2号的29点？！，一天一共24个小时吧，这里是29点，请问是什么高深写法？
![image](https://github.com/6dylan6/jdpro/assets/38281146/df0a950a-0bfe-4502-8adf-a28c8beaf2a5)

**Comment by donald001** [comment]
![image](https://github.com/6dylan6/jdpro/assets/38281146/a6242d33-a7be-44a2-ba93-cab21c5c3a8b)

**Comment by 6dylan6** [comment]
@donald001 就是让不自动跑的，2月29号执行，4年后

**Comment by donald001** [comment]
那这个表达式错位了吧？

**Comment by catsimple** [comment]
cron 5位代表最小到分钟
这是2月29号 7点7分
这个解析式没错
你访问到了垃圾网站

**Comment by donald001** [comment]
原来是这样。
