### ISSUE TITLE
临期京豆兑换兑换不了

### ISSUE THREAD

**Issue by chenxiaozhen123** [6dylan6/jdpro#32]
临期京豆兑换报错，signature verification failed

**Comment by 6dylan6** [comment]
@chenxiaozhen123 日志截图看看

**Comment by chenxiaozhen123** [comment]
![image](https://github.com/6dylan6/jdpro/assets/26481478/e3fcc3c3-f2fd-408b-ac84-9612b9c6d023)

**Comment by 6dylan6** [comment]
稍微往上截下呢，不知道哪地方报的错啊

**Comment by chenxiaozhen123** [comment]
![Uploading Screenshot_20230616_215741_edit_390806626870574.jpg…]()
![Screenshot_20230616_215844](https://github.com/6dylan6/jdpro/assets/26481478/f3df72a2-4631-4264-ba19-ef6ed8133543)
临过期已经11京豆，但是兑换不了

**Comment by chenxiaozhen123** [comment]
![Uploading Screenshot_20230616_215741_edit_390806626870574.jpg…]()

**Comment by 6dylan6** [comment]
我这正常，你可能账号问题，手戳都换不了那种

**Comment by leifeng-N** [comment]
> 我这正常，你可能账号问题，手戳都换不了那种

我的是能兑换，手机上京豆也看得到兑换成功，但是就是没到账
