### ISSUE TITLE
最近执行的都提示这个

### ISSUE THREAD

**Issue by hcliu987** [6dylan6/jdpro#328]
![image](https://github.com/6dylan6/jdpro/assets/52879991/0afabbac-a754-4fa0-8693-e202a9c9c518)

**Comment by hcliu987** [comment]
![image](https://github.com/6dylan6/jdpro/assets/52879991/4fe0f989-e736-44d6-8384-87b7b33093e6)

**Comment by 6dylan6** [comment]
@hcliu987 检查你ck格式对不对，有没有中文？

**Comment by hcliu987** [comment]
重新抓了一下好了，确定没中文，下次注意知道怎么回事了
