### ISSUE TITLE
京东赚赚系统异常

### ISSUE THREAD

**Issue by bling6** [6dylan6/jdpro#332]
请问这个该怎么解决啊
![image](https://user-images.githubusercontent.com/51282956/180677839-b3d1ff48-bdd1-4538-a26a-59a3e0e4b761.png)

**Comment by oldye2020** [comment]
重新运行一遍就行

**Comment by bling6** [comment]
> 重新运行一遍就行

谢谢，第二次确实可以了，难道每天要运行两次吗

**Comment by bling6** [comment]
> @bling6 可能那个时间人多拥挤，自己调整下定时看看

好
