### ISSUE TITLE
ck过期后不会自动禁用

### ISSUE THREAD

**Issue by J2zl** [6dylan6/jdpro#34]

**Comment by J2zl** [comment]
<img width="438" alt="image" src="https://github.com/6dylan6/jdpro/assets/23160330/9dcf7c95-322e-4561-a7b2-de61a404aebd">
能收到通知，但是不会禁用
<img width="594" alt="image" src="https://github.com/6dylan6/jdpro/assets/23160330/1cdfa25d-fb55-4d55-94d1-5547f9df6143">
配置文件已经配置了

**Comment by 6dylan6** [comment]
你看运行日志，sendnotify文件看看是否正确

**Comment by J2zl** [comment]
> 你看运行日志，sendnotify文件看看是否正确

sendnotify.js这个文件没有日志
<img width="360" alt="image" src="https://github.com/6dylan6/jdpro/assets/23160330/1daa1972-de0a-4721-9724-225e76b7cebb">

**Comment by J2zl** [comment]
> 你看运行日志，sendnotify文件看看是否正确

找到问题了sendnotify被青龙覆盖了

**Comment by amxoy** [comment]
@J2zl @6dylan6 怎么弄好的，我的也是一样的变量加了，sendnotify没有运行,没有运行日志
