### ISSUE TITLE
拉库后的目录不一致

### ISSUE THREAD

**Issue by stayStrong007** [6dylan6/jdpro#340]
## 我的拉库命令：
![image](https://github.com/6dylan6/jdpro/assets/139205472/37c01863-2df9-4fbd-afd2-c3c71e5c72a6)
## 拉库结果：
![image](https://github.com/6dylan6/jdpro/assets/139205472/0cae7def-b099-47ef-a578-baf956a832d7)
## 文件对比：
![image](https://github.com/6dylan6/jdpro/assets/139205472/f8b5cf77-74cc-4117-90df-497bfecfe221)

**Comment by 6dylan6** [comment]
不用管库的目录，不一样的，有些目录是不需要拉
一对一可以不用CK_WxPusherUid.json，直接在ck备注加上@@UIDxxx  例 xxx@@UID_dbLa2ExxxxxxxxxxxxxxxxjYauk

**Comment by stayStrong007** [comment]
> 不用管库的目录，不一样的，有些目录是不需要拉 一对一可以不用CK_WxPusherUid.json，直接在ck备注加上@@UIDxxx 例 xxx@@UID_dbLa2ExxxxxxxxxxxxxxxxjYauk

如果仍想用“CK_WxPusherUid.json”的方式呢？我自己手动创建文件并写好，放在某个目录下就可以吗？

**Comment by 6dylan6** [comment]
![image](https://github.com/6dylan6/jdpro/assets/86815944/3e361e39-bb7b-41f1-9a14-a44386366d9a)
那就和库并列放

**Comment by stayStrong007** [comment]
> ![image](https://private-user-images.githubusercontent.com/86815944/343998661-3e361e39-bb7b-41f1-9a14-a44386366d9a.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTk1MzkyNjYsIm5iZiI6MTcxOTUzODk2NiwicGF0aCI6Ii84NjgxNTk0NC8zNDM5OTg2NjEtM2UzNjFlMzktYmI3Yi00MWYxLTlhMTQtYTQ0Mzg2MzY2ZDlhLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA2MjglMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNjI4VDAxNDI0NlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTdjZjU0YTYwZTk3YWJjZDU2N2ZjMjg1NzlmMjA5Y2Q3ODhjYjQ2NGRkY2U1NTEwYTQxOTViZjk5NmYwMWIwZWEmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.b4FO7sG1p_TLENx_HoI0yo5XuvhPnj0R2weogMZsJbY) 那就和库并列放

### 我做的修改：
![image](https://github.com/6dylan6/jdpro/assets/139205472/740507e6-088d-4095-8914-3d033f91260f)


### 结果：
![image](https://github.com/6dylan6/jdpro/assets/139205472/76582180-734f-473b-8f14-187e8d165bcc)

### 解决办法：
看报错提示，在utils文件夹下缺少Rebels_jdCommon.js文件，手动创建后，从github上复制code粘贴进去，推送正常

**Comment by 6dylan6** [comment]
@stayStrong007 拉库命令不全这是，，你对对

**Comment by stayStrong007** [comment]
> @stayStrong007 拉库命令不全这是，，你对对

好的，非常感谢
