### ISSUE TITLE
【东东农场-任务】初始化农场数据异常, 请确认此账号是否开通农场

### ISSUE THREAD

**Issue by Leo4ML** [6dylan6/jdpro#349]
青龙面板版本：2.17.7
jdpro版本：2024/6/23 fix
新农场任务执行正常，东东农场报错，但是手动进入京东APP——首页——东东农场，可以进入且能浇水。

东东农场-任务的运行日志如下

## 开始执行... 2024-07-03 14:01:25

🔔东东农场-任务, 开始!
开始获取配置文件

====================共1个京东账号Cookie=================
===========脚本执行时间：2024/07/03 14:01:27============
>>>>>>>>>>>>6Dy提醒您：有问题先更新不行在反馈>>>>>>>>>>>>>

当前版本：2024/6/23 fix
TG反馈：https://t.me/dylan_jdpro

环境变量：
export DY_PROXY='api_url' 可使用代理api
export NO_WATER='true' 完全不浇水，浇水任务不做了
export FRUIT_PIN='pin1&pin2' 不浇水的pin，多个&分隔，使用pin控制就不要使用NO_WATER
export DO_TEN_WATER_AGAIN='true' 攒水滴只交10次水，默认不攒水滴
epxort FRUIT_DELAY='1000',设置等待时间(毫秒)，默认请求5次接口等待5秒（5000）

export FRUIT_NOTIFY=false 开启详情通知，默认只通知成熟和异常
------------------【京东账号1】Leo大魔王-------------------

初始化农场数据异常, 请确认此账号是否开通农场

【数据异常】请确认此账号是否开通农场

🔔东东农场-任务, 结束! 🕛 7.296 秒

## 执行结束...   耗时 8 秒

**Comment by Leo4ML** [comment]
有没有人知道这个问题该怎么解决～

**Comment by 6dylan6** [comment]
@Leo4ML 你这老农场吧？看看新农场正常吗

**Comment by Leo4ML** [comment]
这是一封自动回复邮件。已经收到您的来信，我会尽快回复。

**Comment by Leo4ML** [comment]
> @Leo4ML 你这老农场吧？看看新农场正常吗

有个任务名叫【新农场任务】的任务都很正常。还有老农场么，请问老农场和新农场是不是就是一个东西，我新农场能跑就不用管老农场了？

**Comment by 6dylan6** [comment]
@Leo4ML 嗯是，老农场之前开通的才能正常玩

**Comment by Leo4ML** [comment]
> @Leo4ML 嗯是，老农场之前开通的才能正常玩

明白了 感谢！此问题完结~
