### ISSUE TITLE
依赖安装问题

### ISSUE THREAD

**Issue by FUNJUNWEI** [6dylan6/jdpro#35]
依赖安装
拉库后，执行'依赖安装'任务安装此库脚本所需依赖，脚本名jd_indeps，首次拉库执行一次即可，有新依赖再次执行
没有这个任务？

**Comment by 6dylan6** [comment]
请看readme哈，config.sh里面需要配置

**Comment by LxzBUG** [comment]
青龙config.sh配置需要把GithubProxyUrl="https://ghproxy.com/" 修改为GithubProxyUrl=""否则拉取失败

我看了下青龙config.sh 并没有GithubProxyUrl设置😂😂😂 然后我用代理的话 其他任务都是已经拉下来了 就是依赖安装没有

**Comment by 6dylan6** [comment]
1、修改青龙config.sh配置（特别注意，没有修改此配置，不内部互助）

RepoFileExtensions="js py"修改为

RepoFileExtensions="js py sh"
