### ISSUE TITLE
健康社区兑换京豆

### ISSUE THREAD

**Issue by djlq** [6dylan6/jdpro#35]
42行的time.sleep((tomorrow - int(time.time()*1000) + diff)/1000) 停止时间太长了

**Comment by shaufo** [comment]
我也是遇到这个，一直卡住，
![微信截图_20230623164007](https://github.com/6dylan6/jdpro/assets/63514384/1427e620-14e4-4bba-a280-ffc0bc60e31e)

**Comment by 6dylan6** [comment]
@shaufo 删了，已经没用了

**Comment by shaufo** [comment]
好的！
