### ISSUE TITLE
 东东农场-任务 jd_fruit.js

### ISSUE THREAD

**Issue by zhuo2002** [6dylan6/jdpro#352]
增加一个黑名单，现在的新号都是无法开通旧农场，这种号通过pin跳过一下？

**Comment by 6dylan6** [comment]
@zhuo2002 tempblock_ck_envs_num="3"
tempblock_ck_envs1="jd_fruit@-@pin&jd_farm@-@pin"
这样就是屏蔽某pin的ck参与指定的任务

**Comment by zhuo2002** [comment]
> @zhuo2002 tempblock_ck_envs_num="3"tempblock_ck_envs_num=“3” tempblock_ck_envs1="jd_fruit@-@pin&jd_farm@-@pin"tempblock_ck_envs1=“jd_fruit@-&jd_farm@-” 这样就是屏蔽某pin的ck参与指定的任务

 可这不是连带新农场一起禁用了吗？

**Comment by 6dylan6** [comment]
@zhuo2002 好像是，没开通的跑什么报错，我看看给跳过

**Comment by zhuo2002** [comment]
> @zhuo2002 好像是，没开通的跑什么报错，我看看给跳过

初始化农场数据异常, 请确认此账号是否开通农场


【数据异常】请确认此账号是否开通农场

没办法单独加黑名单吗

**Comment by geelinsir** [comment]
旧农场未开通的我觉得可以不用推送了，推送了也解决不了

**Comment by formyangel1219** [comment]
旧农场感觉可以弃用了，现在一天浇水就10几个水滴，就浇1 2次，
看起来京东就是想让人家不玩，然后默默关掉这个功能。

**Comment by 6dylan6** [comment]
@formyangel1219 是的，基本种不出了。变相下线。
