### ISSUE TITLE
安装依赖报错 getaddrinfo ENOTFOUND registry.nlark.com

### ISSUE THREAD

**Issue by Chat240515** [6dylan6/jdpro#355]
安装依赖报错
npm ERR! network request to https://registry.nlark.com/https-proxy-agent/download/https-proxy-agent-5.0.0.tgz failed, reason: getaddrinfo ENOTFOUND registry.nlark.com
![20240705112322](https://github.com/6dylan6/jdpro/assets/169867353/9a5b2216-e585-4d81-975d-546e26b909b7)

**Comment by geelinsir** [comment]
代理没开或开了错误的代理吧，手动curl一下看看通不通

**Comment by Chat240515** [comment]
> 代理没开或开了错误的代理吧，手动curl一下看看通不通

好像也不行
![20240708163329](https://github.com/6dylan6/jdpro/assets/169867353/fd51a1f1-7117-40fc-8853-5cf62a03880b)
