### ISSUE TITLE
自定义webhook时获取配置的process.env获取到的WEBHOOK_BODY参数中$title和$content会被替换为空

### ISSUE THREAD

**Issue by mikoshu** [6dylan6/jdpro#360]
自定义webhook时获取配置的process.env获取到的WEBHOOK_BODY参数中$title和$content会被替换为空导致无法发送通知
如配置为 "title:$title"在sendNotify中打印出来结果为"title:"导致脚本直接resolve

**Comment by 6dylan6** [comment]
@mikoshu 是库里的通知文件吗。好像不支持webhook

**Comment by mikoshu** [comment]
试了下 确实是他本身提供的 notify.js 的问题 process.env[key] 那里就会被替换掉了 我去那边提issue试试

**Comment by Clov614** [comment]
@6dylan6 你好，青龙面板的自定义webhook通知方式不支持吗

**Comment by mikoshu** [comment]
支持的 已经调通了 @Clov614

**Comment by dustsoar** [comment]
> 支持的 已经调通了 [@Clov614](https://github.com/Clov614)

可否具体说下是那个版本，需要什么设置吗？
