### ISSUE TITLE
请教spy监控类的脚本运行报错

### ISSUE THREAD

**Issue by jaxenDevelop** [6dylan6/jdpro#367]
比如知识超人（超级无线）这类通过spy监控自动执行的脚本报错
报错内容：
🚫 getSign 请求失败 ➜ 无法解析的域名或地址 [ENOTFOUND]
🚫 getToken 签名获取失败
获取 Token 失败！

报错原因：
之前运行都是没问题的，最近配置了家里光猫桥接然后ipv6+ddns以供外网访问(docker应该是没有配置ipv6的，因为我有个firefox的容器内ipv6连接测试是不通过的，firefox和青龙都是bridge模式）就不行了，而且仅是spy监控执行类的会报上面的错，普通的签到、农场都没问题。。。我试了在青龙内ping知识超人（超级无线）的js头部写的 lzkj-isv.isvjcloud.com域名是可以ping通，但是getToken.js被加密过了看不到具体代码无法继续分析，求教大佬是否知道这个报错原因？

**Comment by 6dylan6** [comment]
@jaxenDevelop 先更新

**Comment by jaxenDevelop** [comment]
> @jaxenDevelop 先更新

更新什么呢，青龙容器还是jdm里的脚本？

**Comment by 6dylan6** [comment]
@jaxenDevelop 直接拉库更新呀

**Comment by jaxenDevelop** [comment]
> @jaxenDevelop 直接拉库更新呀

我就是拉的jdm那个库，是最新的

**Comment by jaxenDevelop** [comment]
> @jaxenDevelop 直接拉库更新呀

我刚运行原来的报错没有了，请问是因为jdm那个库昨天提交了更改么？
