### ISSUE TITLE
玩一玩时不时活动火爆

### ISSUE THREAD

**Issue by u-mie** [6dylan6/jdpro#371]
家宽试过换IP也火爆，但是手动进入APP可用完成任务，其他群好像也遇到过，说是脚本问题
参与用户较多，去看看其他活动吧～ -7004 啊哦~活动太火爆了
"{\n  \"code\": \"403\",\n  \"message\": \"活动太火爆了， 请稍后重试！\"\n}"

**Comment by 6dylan6** [comment]
@u-mie 没事，多运行两次就完成了
