### ISSUE TITLE
Tg推送资产查询结果失败的问题请教

### ISSUE THREAD

**Issue by noonecheck** [6dylan6/jdpro#372]
我使用的cookie有16个，执行资产统计6dylan6_jdpro/jd_bean_change.js时，应该是字符数量太大了，给tg发送总是提示
`开始发送通知...
通知标题: 京东资产统计
添加缓存2024-07-11.json成功!
telegram发送通知消息失败！！

HTTPError: Response code 400 (Bad Request)
    at onResponse (/ql/data/scripts/node_modules/.pnpm/got@11.5.1/node_modules/got/dist/source/as-promise/index.js:142:28)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5) {
  code: undefined,
  timings: {
    start: 1720692467866,
    socket: 1720692467866,
    lookup: 1720692467866,
    connect: 1720692468176,
    secureConnect: 1720692468489,
    upload: 1720692468489,
    response: 1720692468801,
    end: 1720692468802,
    error: undefined,
    abort: undefined,
    phases: {
      wait: 0,
      dns: 0,
      tcp: 310,
      tls: 313,
      request: 0,
      firstByte: 312,
      download: 1,
      total: 936
    }
  }
}
开始发送通知...
通知标题: 京东白嫖提醒
Telegram发送通知消息成功🎉`
当我把cookie缩减到13个以下就会正常发送，查了好久，没有找到原因，也查看了之前有人有推文太长失败的，但他自己解决了，我这个折腾了几天还是不能解决，希望能帮我看看，指导一下，谢谢。

**Comment by 6dylan6** [comment]
@noonecheck 用分段变量

**Comment by noonecheck** [comment]
好的，非常感谢

**Comment by noonecheck** [comment]
> @noonecheck 用分段变量

好的，非常感谢

**Comment by noonecheck** [comment]
> @noonecheck 用分段变量

请问大佬，是在帮助文档2.2.6中提到的这个分段模式是吗，谢谢

**Comment by 6dylan6** [comment]
@noonecheck (1) EANCHANGE_PERSENT  分段通知  
    例子 :  export BEANCHANGE_PERSENT="10"    
    总共有22个账号,结果会分成3条推送通知，1~10为第一条推送，11~20为第二条推送，剩余的为第三条推送

**Comment by noonecheck** [comment]
> @noonecheck (1) EANCHANGE_PERSENT  分段通知  
>     例子 :  export BEANCHANGE_PERSENT="10"    
>     总共有22个账号,结果会分成3条推送通知，1~10为第一条推送，11~20为第二条推送，剩余的为第三条推送

大佬，这个我是要改几个地方，是要改sendNotify.js这里面吗，还是jd_bean_change.js这里面，还是在环境变量界面配置，也没有搜到BEANCHANGE_PERSENT这个代码的位置，自己学着整比较小白，再次感谢大佬，谢谢

**Comment by 6dylan6** [comment]
@noonecheck 变量啊，改什么，在config.sh文件写变量 export BEANCHANGE_PERSENT="10"

**Comment by noonecheck** [comment]
> @noonecheck 变量啊，改什么，在config.sh文件写变量 export BEANCHANGE_PERSENT="10"

明白了，感谢大佬指点，谢谢！！

**Comment by noonecheck** [comment]
感谢大佬指点，成功了！
