### ISSUE TITLE
玩一玩-翻翻乐提示黑号怎么办？

### ISSUE THREAD

**Issue by formyangel1219** [6dylan6/jdpro#378]
去签到...
该账户可能黑子！无法签到和任务！

["。。。。。。"]这些pin的账号是是黑子，不要执行翻翻乐
能否有请求日志以供调试？

**Comment by 6dylan6** [comment]
@formyangel1219 ？什么意思，要做什么

**Comment by formyangel1219** [comment]
我想知道以后是不是这个号做不了玩一玩了？还是只是临时封禁。
还有其他号怎么防止被黑

**Comment by 6dylan6** [comment]
@formyangel1219 临时禁，可能隔几天又好，没法防止

**Comment by u-mie** [comment]
感觉可能封IP段了，有的号换IP可以跑，有的不行
