### ISSUE TITLE
pushplus 通知失败，如图

### ISSUE THREAD

**Issue by Skylerliutian** [6dylan6/jdpro#379]
<img width="521" alt="image" src="https://github.com/user-attachments/assets/06259295-800a-4a4a-89fd-d4c329a3dadc">

**Comment by crane168** [comment]
> <img alt="image" width="521" src="https://private-user-images.githubusercontent.com/49233429/348982459-06259295-800a-4a4a-89fd-d4c329a3dadc.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjExMTU4MTgsIm5iZiI6MTcyMTExNTUxOCwicGF0aCI6Ii80OTIzMzQyOS8zNDg5ODI0NTktMDYyNTkyOTUtODAwYS00YTRhLTg5ZmQtZDRjMzI5YTNkYWRjLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA3MTYlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNzE2VDA3MzgzOFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTYyNGMxMDA3NjFkZjllNjk0MDlhNDE4ZmQ3NjQxZjlkYTJhNWMwMGU1YTc1MWM0ODYzYzk1Nzg3YTAyZjA2YTUmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.TkbyiAYw925Wz42q-jxO_YvNalNvZC_uIt-vrG24Pz4">

我也遇到这种情况了

**Comment by 6dylan6** [comment]
@crane168 push+问题吧，我正常

**Comment by Skylerliutian** [comment]
估计是pushplus的问题，测试手动修改为http://www.pushplus.plus/send可用
