### ISSUE TITLE
如何禁用某些帐号不参加某个活动？

### ISSUE THREAD

**Issue by formyangel1219** [6dylan6/jdpro#380]
根据文档，在配置文件（config.sh）中设置以下内容，但是不起效？

想要把第2，4,5个不参加玩一玩活动

## 其他需要的变量，脚本中需要的变量使用 export 变量名= 声明即可
export tempblock_ck_envs_num="4"
export tempblock_ck_envs1="jd_wanyiwan@2,4,5"
export tempblock_ck_envs2="jd_wyw_ffl@2,4,5"
export tempblock_ck_envs3="jd_wyw_y1y@2,4,5"
export tempblock_ck_envs4="jd_wyw_lottery@2,4,5"

**Comment by 6dylan6** [comment]
@formyangel1219 什么版本青龙，task_before有内容吗

**Comment by formyangel1219** [comment]
拾光坞部署的内置青龙，docker没法配置，没法查看和修改里面的脚本。

**Comment by formyangel1219** [comment]
task_before，这个文件在哪，青龙的web可以看到？

**Comment by 6dylan6** [comment]
@formyangel1219 web配置管理可以看到

**Comment by formyangel1219** [comment]
#!/usr/bin/env bash


task_before,这个文件是空的

**Comment by 6dylan6** [comment]
@formyangel1219 那不行，https://github.com/6dylan6/jdpro/blob/main/docker/task_before.sh 到这拷贝

**Comment by formyangel1219** [comment]
ok,现在好像有生效了，感谢
