### ISSUE TITLE
玩一玩-任务抽奖失败

### ISSUE THREAD

**Issue by formyangel1219** [6dylan6/jdpro#384]
玩一玩-任务抽奖, 开始!

====================共5个京东账号Cookie=================
===========脚本执行时间：2024/07/18 07:27:34============
>>>>>>>>>>>>6Dy提醒您：有问题先更新不行在反馈>>>>>>>>>>>>>

问题反馈：https://t.me/dylan_jdpro

******开始【京东账号1】*********

undefined
获取任务失败！

******开始【京东账号2】*********

undefined
获取任务失败！

**Comment by 6dylan6** [comment]
@formyangel1219 结束了
