### ISSUE TITLE
新农场任务报错，无法获取助力好友名单

### ISSUE THREAD

**Issue by xyflii** [6dylan6/jdpro#397]
任务执行异常，请检查执行日志 ‼️‼️

❗️新农场任务, 错误!
Cannot read properties of undefined (reading 'assistFriendList')

**Comment by xyflii** [comment]
这个有办法解决吗，很多天了都是这样;
关键是这之后的浇水不执行了

**Comment by 6dylan6** [comment]
@xyflii 你更新再试试

**Comment by xyflii** [comment]
> @xyflii 你更新再试试

可以正常浇水了，感谢
