### ISSUE TITLE
请问是否支持自动更新cookies呢？

### ISSUE THREAD

**Issue by godad** [6dylan6/jdpro#40]
https://github.com/mrabit/aliyundriveDailyCheck
类似这个阿里云盘签到，添加CLIENT_ID 和 CLIENT_SECRET后就可以自动更新refreshToken，省的每个月都要上去操作一遍登陆获取ck，再更新到青龙里面。

**Comment by 6dylan6** [comment]
@godad 使用wskey

**Comment by shyg866** [comment]
这个能使用多久啊？pt这种用不了几天就失效了。
----------------------------
使用wskey

**Comment by shyg866** [comment]
邮件已收到，我会尽快回复！祝你身体健康,事业有成.
