### ISSUE TITLE
wskey转换失败

### ISSUE THREAD

**Issue by formyangel1219** [6dylan6/jdpro#402]
===============开始转换JD_WSCK==============
【警告】xxxx在获取token时失败，等待5秒后重试
【警告】xxxx在获取token时失败，等待5秒后重试
【警告】xxxx在获取token时失败，等待5秒后重试
【警告】xxxx在获取token时失败，等待5秒后重试
Terminated

**Comment by 6dylan6** [comment]
@formyangel1219 换另一个试试

**Comment by formyangel1219** [comment]
现在又好了，之前 半小时试了好多次，都是失败
