### ISSUE TITLE
> 我这里也是好多任务从ck1开始，不能单独跑一个ck了

### ISSUE THREAD

**Issue by chaoqun1982** [6dylan6/jdpro#408]
> 我这里也是好多任务从ck1开始，不能单独跑一个ck了

昨天更新后就这样了
是的，更新后不能单独跑一个ck了，只能从ck1开始
_Originally posted by @flyingthecat in https://github.com/6dylan6/jdpro/issues/407#issuecomment-1272252437_

**Comment by chaoqun1982** [comment]
2 13 8

**Comment by chaoqun1982** [comment]
怎么远程？

**Comment by chaoqun1982** [comment]
稍等，我安装个向日葵

**Comment by flyingthecat** [comment]
> 



> @chaoqun1982 谁来个远程我排查下。
 向日葵 699447534   1234321

**Comment by chaoqun1982** [comment]
你有了，我就不下载了

**Comment by chaoqun1982** [comment]
你有，我就不下载了，都一样问题

**Comment by chaoqun1982** [comment]
大佬，你给他远程吧，都一样的问题，我没下载

> 向日葵 todesk都行

**Comment by chaoqun1982** [comment]
> @chaoqun1982好
向日葵 699447534 1234321

**Comment by flyingthecat** [comment]
> @flyingthecat 确定问题了，等等

好的 大佬辛苦

**Comment by flyingthecat** [comment]
> @flyingthecat 可以了，更新，运行获取互助码任务就可以了

ok 大佬辛苦
