### ISSUE TITLE
希望大佬增强一下【玩一玩兑换】

### ISSUE THREAD

**Issue by jiubaK** [6dylan6/jdpro#409]
感谢大佬提供使用的脚本！🙏
1，个人认为可以设定多个兑换ID，依照顺序兑换（目前只能设定一个，如果这个没有库存，就很难受，现在官方限制数量了，很难抢到指定的那个兑换）
2，希望增加一个校验，如果没有库存，就不执行兑换（现在不管是否有库存都会执行兑换，而结果就是兑换失败，又留下了兑换记录，感觉容易被识别）
再次感谢大佬🙏
这脚本加密了，不然手改了。

**Comment by 6dylan6** [comment]
@jiubaK 好的

**Comment by jiubaK** [comment]
@6dylan6 感谢哈，看到已经增强了，用着很丝滑。后面再来提issue【手动dog】。
