### ISSUE TITLE
你好，sendnotify.js文件用库里的到青龙deps目录下后运行脚本出错，换回青龙自带又恢复，这是怎么回事？

### ISSUE THREAD

**Issue by liugdls** [6dylan6/jdpro#411]
如题：sendnotify.js文件用库里的到青龙deps目录下后运行脚本出错，换回青龙自带又恢复
![fed7d4dc4c56af50de7f3137a40336b](https://github.com/user-attachments/assets/14e6c625-446f-4616-a05a-d19e67a969db)

**Comment by 6dylan6** [comment]
@liugdls 你仔细检查，肯定不一样和库里的。。
