### ISSUE TITLE
批量取消关注的店铺和商品 建议

### ISSUE THREAD

**Issue by MengyuCai** [6dylan6/jdpro#417]
在批量取消关注的店铺和商品时，可以不可以做一个校验，比如写一个通用的关注方法，在关注时，把关注的商品id或者店铺的id写入环境变量中，然后在批量取消的时候，去获取这个环境变量中写入的商品id和店铺id，只取消这些id的关注，避免自己手动关注的商品和店铺被批量取消关注给取消了

**Comment by 6dylan6** [comment]
@MengyuCai 有过滤的，不想取消的添加关键词
JD_UNSUB_GKEYWORDS  商品关键词，多个@分割
JD_UNSUB_SKEYWORDS  店铺关键词

**Comment by MengyuCai** [comment]
> @MengyuCai 有过滤的，不想取消的添加关键词
> JD_UNSUB_GKEYWORDS  商品关键词，多个@分割
> JD_UNSUB_SKEYWORDS  店铺关键词

好的，感谢
