### ISSUE TITLE
能否取消单个任务的随机延时

### ISSUE THREAD

**Issue by formyangel1219** [6dylan6/jdpro#419]
玩一玩兑换，设置23.59.35，结果延时后都到0.03了。
![无标题](https://github.com/user-attachments/assets/b7521560-c650-4790-8332-b0b1d03bffeb)

**Comment by 6dylan6** [comment]
@formyangel1219 你那有问题啊，找青龙原因

**Comment by formyangel1219** [comment]
# 开始执行... 2024-08-12 12:00:03


🔔玩一玩兑换, 开始!

====================共6个京东账号Cookie=================
===========脚本执行时间：2024/08/12 12:00:25============
>>>>>>>>>>>>6dylan6提醒您：有问题先更新不行在反馈>>>>>>>>>>>>



好像之前不会，设置0 0 * * *，就没有延时，
昨天晚上改成35 59 23 * * *，运行就出现延时了

**Comment by 6dylan6** [comment]
@formyangel1219 脚本没有随机延迟，你手动开始看看

**Comment by formyangel1219** [comment]
我看执行的命令是task 6dylan6_jdpro/jd_wyw_award.js，
百度搜加上now：task 6dylan6_jdpro/jd_wyw_award.js now，是否有效

**Comment by formyangel1219** [comment]
手动没延时，但没办法卡晚上12点去手动啊

**Comment by 6dylan6** [comment]
@formyangel1219 所以还是你青龙问题

**Comment by formyangel1219** [comment]
好吧，你是对的，吃了没文化的亏。

**Comment by 6dylan6** [comment]
@formyangel1219 青龙本来就随机延迟，加now或手动才即时，不会现在才发现吧，你没发现其他任务也这样吗，config里有延迟参数，可以设置0取消延迟

**Comment by formyangel1219** [comment]
从来没有注意过执行任务命令，学习了，感谢。
