### ISSUE TITLE
M集卡直接报错

### ISSUE THREAD

**Issue by yumengbdw** [6dylan6/jdpro#42]
直接报，activityId|activityUrl不存在
感觉是/function/magic运行有误

**Comment by yumengbdw** [comment]
看了下M系列活动都没成功   
M加购有礼 /ql/scripts/dylanote_jdpro/m_jd_wx_addCart.js 开始运行...
活动不存在
 M幸运抽奖 /ql/scripts/dylanote_jdpro/m_jd_wx_luckDraw.js 开始运行...
活动id不存在
活动id不存在

**Comment by 6dylan6** [comment]
嗯这些是通用，有活动id和url设置变量就可跑任务。没有获取渠道就禁用这任务吧
