### ISSUE TITLE
不同任务禁用帐号怎么设置

### ISSUE THREAD

**Issue by formyangel1219** [6dylan6/jdpro#421]
之前用这样子：
#export tempblock_ck_envs_num="5"
#export tempblock_ck_envs1="jd_wanyiwan@-@pin1,pin2,pin3"
#export tempblock_ck_envs2="jd_wyw_ffl@-@pin4,pin5,pin6"

但是后面改成了下面这样：
export BANPIN="jd_wyw_award@pin1&pin2"
export BANPIN="jd_wyw_ffl@pin3&pin4"

如果多次export，后面的会覆盖掉前面的值，如何做到之前的这种效果？

**Comment by 6dylan6** [comment]
@formyangel1219 可以多个关键字啊，不用多个变量，看下面
变量BANPIN禁止指定pin执行某任务
多个任务同pin：任务1|任务2@pin1&pin2  
多个任务不同pin：任务1@pin&任务2@pin2
不指定任务只写pin  全部任务都不执行

**Comment by formyangel1219** [comment]
ok，感谢

**Comment by formyangel1219** [comment]
多个任务不同pin：任务1@pin&任务2@pin2

但是这样只能一个一个设置吧，如
任务1@pin1    &任务1@pin2         &任务2@pin2        &任务2@pin3
（空格只是方便阅读 ）

**Comment by 6dylan6** [comment]
@formyangel1219 ？同任务可合并指定pin啊，看第一条。融会贯通下

**Comment by formyangel1219** [comment]
没看懂，打个比方吧，任务1禁pin1和pin2，任务2禁pin2和pin3，

任务1@pin1&pin2（这里该用什么连接？）任务2@pin2&pin2

**Comment by 6dylan6** [comment]
@formyangel1219 &

**Comment by formyangel1219** [comment]
任务1@pin1**&**pin2**&**任务2@pin2&pin2
 
pin间是&,任务也是&，不会冲突么

**Comment by 6dylan6** [comment]
@formyangel1219 写错啦，多个pin直接,分割
多个任务同pin：任务1|任务2@pin1,pin2
