### ISSUE TITLE
玩一玩助力经常报错

### ISSUE THREAD

**Issue by 18265028909** [6dylan6/jdpro#424]
开始助力...
去助力 --> Z4UN75nF1yKJrftsxEfqX2dNkJIk4kUN

-------开始【账号1】jd_dZmgGeORejQq------

❌ 405 参与用户较多，去看看其他活动吧～

-------开始【账号2】jd_ZITLlAIfRKST------

去助力 --> Z4UN75nF1yKJrftsxEfqX2dNkJIk4kUN
❌ 405 参与用户较多，去看看其他活动吧～

🔔玩一玩_指定助力, 结束! 🕛 6.07 秒
运行助力经常报错偶尔可以成功一下

**Comment by 6dylan6** [comment]
@18265028909 更新试试

**Comment by 18265028909** [comment]
最新的
![微信截图_20240815210004](https://github.com/user-attachments/assets/78741a10-8d39-422f-a4c1-67099426b967)
依旧不行还是报错

> @18265028909 更新试试

**Comment by 6dylan6** [comment]
@18265028909 在拉

**Comment by 18265028909** [comment]
> @18265028909 在拉

可以了感谢
