### ISSUE TITLE
互助码生效问题

### ISSUE THREAD

**Issue by vpw2011** [6dylan6/jdpro#425]
@6dylan6 大佬，
在配置文件config.sh最后一行已经加了export HelpType=1，也自动/手动运行了 获取互助码 脚本，查看日志有看到生成互助码，例如：（互助码和账号隐去了部分信息；#之前加‘，为了避免github格式问题，原日志没有的）
'## 东东农场：
MyFruit1='7f07xxxxx'

'### 采用"按编号优先"互助模板
ForOtherFruit1=""

但请问要查看东东农场日志什么地方或什么脚本的日志，可以得知已经助力他人或被他人助力的次数或状态。谢谢。（因为感觉东东农场日志都是自己助力自己，互助没有生效）

第1个京东账号将要助力的好友[""]

【京东账号1（隐去）的东东农场好友互助码】7f07xxxxx

【已成功兑换水果】1次

开始助力好友
去助力: 
助力好友结束，即将开始领取额外水滴奖励

**Comment by vpw2011** [comment]
@6dylan6 

类似，但我只有MyFruit1

![搜狗截图20221020081928](https://user-images.githubusercontent.com/108579368/196828353-b107445c-4f12-4db4-8022-a31448ca4c95.jpg)

**Comment by vpw2011** [comment]
@6dylan6 哈哈哈，自用的，只有自己的CK。误以为这个功能是可以和陌生人互助。

**Comment by vpw2011** [comment]
@6dylan6 谢谢大佬指点。我原来误会大了。

**Comment by firethefox** [comment]
@6dylan6 大佬好，请问我在config.sh 添加了export HelpType=1,然后运行jd_sharecode.sh脚本，依然是使用按编号顺序互助模板。查看jd_sharecode.sh，里面第53行HelpType=""这句是写死的嘛，没有从环境变量获取HelpType的值呢？
