### ISSUE TITLE
京东转赚红包2

### ISSUE THREAD

**Issue by noonecheck** [6dylan6/jdpro#425]
![IMG_20240816_073734.jpg](https://github.com/user-attachments/assets/ce6ba026-93a0-437f-9b3f-30ac450e785e)

大佬，现在抽奖都是垃圾券正常吗，我没挂代理

**Comment by 6dylan6** [comment]
@noonecheck 手动进app抽就知道啊，也是券，就是没水

**Comment by noonecheck** [comment]
> @noonecheck 手动进app抽就知道啊，也是券，就是没水

好的，感谢大佬
