### ISSUE TITLE
双十一活动

### ISSUE THREAD

**Issue by bling6** [6dylan6/jdpro#428]
大佬，更新双十一活动的脚本吗

**Comment by basten1899** [comment]
目前仅对6dy开放 /(ㄒoㄒ)/~~

**Comment by aliyy2021** [comment]
> 目前仅对6dy开放 /(ㄒoㄒ)/~~

这个咋解决啊，我也是提示这个

**Comment by MagicCheshireMeow** [comment]
> @aliyy2021 11以上版本青龙跑。不要用互助研究院就不会有问题。

怎么样不用互助研究院啊……除了青龙配置里面的助力模式外还有哪些地方
