### ISSUE TITLE
建议京东试用采用JD_TRY_TITLEFILTERS自定义屏蔽。

### ISSUE THREAD

**Issue by yumengbdw** [6dylan6/jdpro#43]
建议判断JD_TRY_TITLEFILTERS用户设置自定义屏蔽，采用用户自定义的，没定义再采用内置的屏蔽词innerKeyWords

$.innerKeyWords =
    [
        "幼儿园", "教程", "英语", "辅导", "培训",
        "孩子", "小学", "成人用品", "套套", "情趣",
        "自慰", "阳具", "飞机杯", "男士用品", "女士用品",
        "内衣", "高潮", "避孕", "乳腺", "肛塞", "肛门",
        "宝宝", "玩具", "芭比", "娃娃", "男用",
        "女用", "神油", "足力健", "老年", "老人",
        "宠物", "饲料", "丝袜", "黑丝", "磨脚",
        "脚皮", "除臭", "性感", "内裤", "跳蛋",
        "安全套", "龟头", "阴道", "阴部", "手机卡", "电话卡", "流量卡"
    ]

**Comment by 6dylan6** [comment]
目前逻辑是自定义变量+内置比较好。以防没设置变量，申请一堆垃圾，哈哈。

**Comment by yumengbdw** [comment]
有京东白名单，白名单优先级大于黑名单JD_TRY_WHITELIST
