### ISSUE TITLE
拉库失败

### ISSUE THREAD

**Issue by cy465728759** [6dylan6/jdpro#43]
## 开始执行... 2023-07-04 17:40:48

开始更新仓库：/ql/repo/6dylan6_jdpro

Fetching origin
HEAD is now at b44edb8 1

日志如上，这也是代理的问题？

**Comment by 6dylan6** [comment]
@cy465728759 更新不出东西那是青龙bug了，执行拉库失败修复

**Comment by cy465728759** [comment]
好了
