### ISSUE TITLE
农场助力判断条件

### ISSUE THREAD

**Issue by formyangel1219** [6dylan6/jdpro#430]
【额外奖励】领取失败,原因：给您助力的人未达2个

实际上第一级好像一个助力就能达成了
![微信图片_20240819152010](https://github.com/user-attachments/assets/406966ce-10e5-4c12-b019-1f7afbf5d214)

**Comment by 6dylan6** [comment]
@formyangel1219 更新

**Comment by formyangel1219** [comment]
ok了
