### ISSUE TITLE
京东种豆得豆无法使用

### ISSUE THREAD

**Issue by leifeng-N** [6dylan6/jdpro#44]
第1个京东账号将要助力的好友["hzsxvtmuobdm6i5pdkv5h55ewgr22wptoo27mzi"]
获取任务及基本信息
哎呀！活动太火爆，前方道路拥挤！
种豆得豆-初始失败:  {"code":"420","errorMessage":"哎呀！活动太火爆，前方道路拥挤！"}

开始【京东账号2】

第2个京东账号将要助力的好友["o7eiltak46s2wqjjmf3ppmc33vmk3yjy3lzk32q"]
获取任务及基本信息
哎呀！活动太火爆，前方道路拥挤！
种豆得豆-初始失败:  {"code":"420","errorMessage":"哎呀！活动太火爆，前方道路拥挤！"}

**Comment by BNDou** [comment]
我的也是，app里面可以正常访问，换了ip返回的也是这个log

**Comment by 6dylan6** [comment]
@BNDou 坏了，等修

**Comment by 6dylan6** [comment]
@leifeng-N 账号无效

**Comment by leifeng-N** [comment]
> @leifeng-N账号无效

1；换cookie解决了。
2；种豆还是不行

**Comment by tangguocpu** [comment]
获取任务及基本信息
undefined
种豆得豆-初始失败:  {"code":"1","echo":"required string parameter 'functionId' is not present"}

**Comment by 6dylan6** [comment]
@tangguocpu 你自己问题吧，拉库修复，在更新试试
