### ISSUE TITLE
依赖安装问题

### ISSUE THREAD

**Issue by lunati-wei** [6dylan6/jdpro#44]
这是什么问题呢，对这个东东不是太懂
安装脚本所需依赖，首次拉库运行一次即可
开始安装............
 ERR_PNPM_REGISTRIES_MISMATCH  This modules directory was created using the following registries configuration: {"default":"https://registry.npmjs.org/"}. The current configuration is {"default":"https://registry.npm.taobao.org/"}. To recreate the modules directory using the new settings, run "pnpm install".
 ERR_PNPM_REGISTRIES_MISMATCH  This modules directory was created using the following registries configuration: {"default":"https://registry.npmjs.org/"}. The current configuration is {"default":"https://registry.npm.taobao.org/"}. To recreate the modules directory using the new settings, run "pnpm install".

**Comment by 6dylan6** [comment]
更新了安装依赖任务，你更新再试下

**Comment by lunati-wei** [comment]
现在好了，另外，我看日志里面没啥内容啊，帮看下，这样正常不

## 开始执行... 2022-02-21 13:54:43


🔔QQ星系牧场, 开始!

====================共6个京东账号Cookie=========

==================脚本执行- 北京时间(UTC+8)：2022/2/21 下午1:54:44=====================


******开始【京东账号1】jd*********


## 执行结束... 2022-02-21 13:54:47 耗时 4 秒

**Comment by lunati-wei** [comment]
我用的青龙面板是 [v2.10.12]

**Comment by lunati-wei** [comment]
日志-领京豆额外奖励
## 开始执行... 2022-02-21 13:54:11


🔔领京豆额外奖励, 开始!

====================共6个京东账号Cookie=========

==================脚本执行- 北京时间(UTC+8)：2022/2/21 下午1:54:13=====================


## 执行结束... 2022-02-21 13:54:15 耗时 4 秒

**Comment by lunati-wei** [comment]
我还用了青龙的一个 任务如下：好像和你的那个获取互助码是不是存在冲突？ 
 **格式化更新互助码 | task /ql/config/code.sh**

**Comment by 6dylan6** [comment]
code.sh是互助使用的。你这运行和互助没关系。是有点奇怪了。其他任务都是这样么？

**Comment by lunati-wei** [comment]
好像都是这样的，我cp了几个，如下：

日志-京东资产统计
## 开始执行... 2022-02-21 16:59:34

🔔京东资产统计, 开始!

====================共6个京东账号Cookie=========

==================脚本执行- 北京时间(UTC+8)：2022/2/21 下午4:59:35=====================

检测到设定了临期京豆转换喜豆,但时间未到17点后，暂不执行转换...
检测到设定了分段通知:3
******开始查询【京东账号1】jd_*********


## 执行结束... 2022-02-21 16:59:38 耗时 4 秒

日志-东东农场
## 开始执行... 2022-02-21 13:55:53


🔔东东农场, 开始!
开始获取配置文件


====================共6个京东账号Cookie=========

==================脚本执行- 北京时间(UTC+8)：2022/2/21 下午1:55:55=====================

共6个京东账号

您提供了5个账号的农场助力码

开始【京东账号1】jd_187wg

第1个京东账号将要助力的好友["1039708d3d004a4a94c03076b67f81e1","ef9ffb9c616c4a18b59bce3fd845aba3","38271ae5e71c4346893a92c336d4a265","cbe963cb270449f1a85fe6837175c6b6","872bc373775446e98dc4038b1bcbb331","5072d2b27aed4c688476535c43c526af","157157332b4b478886389f41b1805f98","261c12bb3c064581b4e6e7d40571f151","a549c177d5374a0987beb7b57443a2f6","fbed4a909b3a45da8033d71b5ba6c139"]

## 执行结束... 2022-02-21 13:55:57 耗时 4 秒

**Comment by lunati-wei** [comment]
我是直接在pc端，使用m.jd.com抓取的cookie，这样应该没啥问题吧？

**Comment by 6dylan6** [comment]
没问题。，搞个新环境吧，环境可能有问题

**Comment by Unclefat-hub** [comment]
> 更新了安装依赖任务，你更新再试下

老哥 这个问题又出现了
