### ISSUE TITLE
天天签到领京豆兑换 就第一天领到了豆，后面都不行了

### ISSUE THREAD

**Issue by leifeng-N** [6dylan6/jdpro#45]
"Response code 504 (Gateway Time-out)"
getMyPing API请求失败，请检查网路重试
获取[Pin]失败！

******开始【京东账号2】*********

总签到天数:16 连续签到天数：6
当前礼享金:915 累计活动京豆：56
"Response code 504 (Gateway Time-out)"
exchangePrizeList API请求失败，请检查网路重试
TypeError: Cannot read properties of undefined (reading 'length')
    at run (/ql/data/scripts/6dylan6_jdpro/jd_lzkj_ttljd_exchange.js:24:10179)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async /ql/data/scripts/6dylan6_jdpro/jd_lzkj_ttljd_exchange.js:24:5128

**Comment by 6dylan6** [comment]
@leifeng-N 看运气了，那么多人一起冲

**Comment by leifeng-N** [comment]
> @leifeng-N看运气了，那么多人一起冲

明白
