### ISSUE TITLE
京东玩一玩兑换g了

### ISSUE THREAD

**Issue by 18265028909** [6dylan6/jdpro#457]
玩一玩兑换改版运行不了了还有嘛

**Comment by 18265028909** [comment]
1

**Comment by 6dylan6** [comment]
@18265028909 提现暂时不行，其他正常

**Comment by 18265028909** [comment]
> @18265028909 提现暂时不行，其他正常

88的提现提不了是吧

**Comment by QQ853695231** [comment]
我连京豆和红包都不行，都显示补货中，但是我爱人的号可以

**Comment by 6dylan6** [comment]
@QQ853695231 正常兑啊

**Comment by QQ853695231** [comment]
> @QQ853695231 正常兑啊

我的不行，我媳妇的行，很奇怪，感觉京东双标了

**Comment by 6dylan6** [comment]
@QQ853695231 不行是什么样的

**Comment by QQ853695231** [comment]
> @QQ853695231 不行是什么样的

我的奖票够，但是京东和红包显示补货中，我媳妇的奖票不够，红包和京豆就不是补货中

**Comment by 6dylan6** [comment]
@QQ853695231 别管显示，我也显示补货

**Comment by QQ853695231** [comment]
> @QQ853695231 别管显示，我也显示补货
但是我都好几天了，从来不让我兑换京豆，但是同一时刻我媳妇的能兑换，这怎么解释呢？

**Comment by 6dylan6** [comment]
@QQ853695231 就问兑换提示什么呀，你说显示补货，汗

**Comment by QQ853695231** [comment]
> @QQ853695231 就问兑换提示什么呀，你说显示补货，汗

我的 是压根不让我兑换，显示补货，我媳妇的 京豆和红包不显示补货，而且能兑换

**Comment by 6dylan6** [comment]
@QQ853695231 脚本兑换提示什么？补货？

**Comment by QQ853695231** [comment]
不是脚本，是我自己进手机APP里面去兑换，显示的是补货

**Comment by hackgsl** [comment]
大佬，兑换成功的可以给个提示吗？我有几个号兑换成功了但是不知道，自己去看了下红包才知道。
