### ISSUE TITLE
汪贝游戏报错

### ISSUE THREAD

**Issue by Yeung168** [6dylan6/jdpro#458]
![image](https://github.com/user-attachments/assets/7140da35-af49-4550-9f73-00d899e4104e)

**Comment by 6dylan6** [comment]
@Yeung168 更

**Comment by Yeung168** [comment]
> @Yeung168 更

农场小程序助力能加个互助吗？好像后面的ck都只给第一个ck助力，没有相互助力。

**Comment by 6dylan6** [comment]
@Yeung168 第一个满了会换下一个的

**Comment by Yeung168** [comment]
> @Yeung168 第一个满了会换下一个的

噢噢，这样阿，因为我看玩一玩、汪贝、种豆这些都可以相互助力（没有满），所以才有这个想法。谢谢大佬

**Comment by 6dylan6** [comment]
@Yeung168 那是每个号有多次助力机会，新农场只有一次机会

**Comment by Yeung168** [comment]
> @Yeung168 那是每个号有多次助力机会，新农场只有一次机会
明白了谢谢
