### ISSUE TITLE
库拉了之后，怎么授权账号执行呀

### ISSUE THREAD

**Issue by m511386374** [6dylan6/jdpro#47]
![image](https://user-images.githubusercontent.com/19544200/154922193-ce7f345a-809f-4152-936e-e8966830e1cc.png)

**Comment by m511386374** [comment]
![image](https://user-images.githubusercontent.com/19544200/154922415-77165d03-1ff1-4ce6-a05a-83c6962f06af.png)
jd_indeps 这个脚本名字也没有找到呀

**Comment by lunati-wei** [comment]
右上角，搜索“依赖”

**Comment by m511386374** [comment]
![Uploading image.png…]()
没有搜索到

**Comment by m511386374** [comment]
![image](https://user-images.githubusercontent.com/19544200/154925319-d70cb080-da84-40dc-9481-a2c19c940a54.png)
没有搜索到

**Comment by 6dylan6** [comment]
## ql repo命令拉取脚本时需要拉取的文件后缀，直接写文件后缀名即可
RepoFileExtensions="js py sh"

17行样子修改这样，配置文件config.sh

**Comment by m511386374** [comment]
恩恩 设置RepoFileExtensions="js py sh"  在去拉库 依赖安装就有了。但是执行了依赖安装之后。在直接去执行jddj_plantBeans这个脚本吗。我执行了这个之后提示让我填写ck 。 
![image](https://user-images.githubusercontent.com/19544200/155053711-d9cae6fd-5c05-4d8b-9d05-b013fd938925.png)
但是我发现我不知道在哪里去配置这个ck。我在你源码中发现了[jdCookie.js](https://github.com/6dylan6/jdpro/blob/main/jdCookie.js) 这里好像可以配置ck 但是我在青龙定时任务列表里面没有搜索到呢
![image](https://user-images.githubusercontent.com/19544200/155053936-e95dfc08-ad32-4464-99a1-7744c9b1d978.png)
 不知道接下来如何下手。
