### ISSUE TITLE
依赖安装脚本的npm的源需要更换了 !

### ISSUE THREAD

**Issue by php737** [6dylan6/jdpro#475]
![image](https://user-images.githubusercontent.com/31496660/200151228-5dd3a844-cdfb-4b18-ae29-11b8c971c05b.png)
淘宝这个链接都是跳转到https://registry.npmmirror.com/ 了  如果和配置文件的npm源不一样  安装依赖都会报错的!

**Comment by bao3** [comment]
一样的问题。

建议直接就使用官方的的库吧。或设置成一个变量，让大家可以自由选择。现在的这个方式，让人很难受。

**Comment by bao3** [comment]
确认已经修复了～

**Comment by php737** [comment]
感谢解决!
