### ISSUE TITLE
农场脚本自动停止问题

### ISSUE THREAD

**Issue by HAN915** [6dylan6/jdpro#476]
我挂了十个CK，到第五个CK时，水果可领取，然后脚本就不往下走了，直接就推送账号5可领取，然后停止运行了。请问该如何设置让脚本继续呢？

**Comment by HAN915** [comment]
【京东账号5（jd_RwumZlJQENdl）的东东农场好友互助码】3982fb8a32504108af87e4571196021c


【已成功兑换水果】2次

开始助力好友
去助力: 8bdea5c8d03e4fa7b4ba0c7ec72aee93
【助力结果】: 对方已满助力
【助力次数还剩】0次

您当前助力次数已耗尽，跳出助力
助力好友结束，即将开始领取额外水滴奖励


==============📣系统通知📣==============
东东农场
【京东账号5】jd_RwumZlJQENdl
【提醒⏰】天然竹筷20双装已可领取
请去京东APP或微信小程序查看
点击弹窗即达
server酱发送通知消息成功🎉



## 执行结束...   耗时 173 秒

**Comment by HAN915** [comment]
#助力模式，前2个账号始终保持在前部，剩余账号按照轮换模式每天轮换5个
export Recombin_CK_Mode="3"
export Recombin_CK_ARG1="2"
export Recombin_CK_ARG2="5" 

现在是设置了这个，但是没设置之前也是这样，只要中间碰到完成的，脚本就会停止

**Comment by HAN915** [comment]
没有种完的正常浇水做任务是没问题的，就是碰到刚好成熟的，就停止了，后面就不执行了
就是说脚本任务做到某个ck时，刚好这个ck的果树成熟了，那么这个脚本就到这个成熟的位置就停止了，后面就不跑了，手动再开始还是到这里就结束了

**Comment by HAN915** [comment]
怀疑这个是和青龙版本有关，以前都没问题的，现在除了这个问题外，还有就是碰到失效的ck也会导致脚本停止运行

**Comment by HAN915** [comment]
@6dylan6 是青龙面板版本问题，出问题的是2.14版本，我换回2.13.6，就没问题了

**Comment by wang25669** [comment]
我也遇到这个问题了 @6dylan6 
重新装的latest青龙，[v2.14.12]， 我4个号，跑到第3个，果子熟了，任务直接就结束了，第4个号不管了 。。。。

> @6dylan6 是青龙面板版本问题，出问题的是2.14版本，我换回2.13.6，就没问题了

怎么换回2.13.6 ，新建docker的命令贴一下 大佬  ，之前我装2.11版本的青龙，用官方命令私自组装的就遇到一些奇奇怪怪的问题

**Comment by HAN915** [comment]
@wang25669 我是用群晖docker装的，拉取镜像的时候可以选择版本，其他系统的我也不会

**Comment by underlaw** [comment]
我也有这种情况

**Comment by HAN915** [comment]
换个版本的青龙面板就好了，我用2.13.6没问题了



| |
***@***.***
|
|
***@***.***
|




---- 回复的原邮件 ----
| 发件人 | ***@***.***> |
| 日期 | 2022年11月12日 13:59 |
| 收件人 | ***@***.***> |
| 抄送至 | ***@***.******@***.***> |
| 主题 | Re: [6dylan6/jdpro] 农场脚本自动停止问题 (Issue #476) |

我也有这种情况

**Comment by HAN915** [comment]
我的问题解决了，用2.15也没问题了！原因应该是sendNotify.js文件问题。
解决方法：
ssh进入docker里面，到/ql/data/deps下，把原来的sendNotify.js文件删除，下一份本库里的放进去，重新拉一遍库就解决了。
我是群晖docker上跑的青龙，其他的解决方案应该也差不多。
