### ISSUE TITLE
京东新农场任务0916版本任务报错，0915版本正常，求解答

### ISSUE THREAD

**Issue by tr3711** [6dylan6/jdpro#480]
## 开始执行... 2024-09-17 07:07:10

🔔新农场任务, 开始!
开始获取配置文件

加载sendNotify，当前版本: 20230712

====================共7个京东账号Cookie=================
===========脚本执行时间：2024/09/17 07:07:20============
>>>>>>>>>>>>6dylan6提醒您：有问题先更新不行在反馈>>>>>>>>>>>>>

版本：20240916 
问题建议：https://t.me/dylan_jdpro

环境变量（可选项）：
export DY_PROXY='url' 代理API
export WTNUM_NEW='100' 指定浇水次数
export FRUIT_NOTIFY='true' 开启详情通知，默认只通知成熟和异常
export FRUIT_LEVEL='2' 自动种植等级，默认最高3级，只能设置1-3

------------------【京东账号1】jd_ItYyWuUVdgoQ-------------------

【账号（jd_ItYyWuUVdgoQ）的新农场任务好友互助码】
【已完成种植】8次

京鲜匠山东正宗真贝贝南瓜栗香小南瓜粉糯老瓜新鲜蔬菜香甜软糯产地直发 5斤礼盒装（5-6个）净 4.5斤 精品   种植中...
种植进度：4/5----58%

准备浇水20次
任务执行异常，请检查执行日志 ‼️‼️

❗️新农场任务, 错误!
ss is not defined

【水果名称】京鲜匠山东正宗真贝贝南瓜栗香小南瓜粉糯老瓜新鲜蔬菜香甜软糯产地直发 5斤礼盒装（5-6个）净 4.5斤 精品
【已完成种植】8次

**Comment by 6dylan6** [comment]
@tr3711 更新

**Comment by tr3711** [comment]
已解决
