### ISSUE TITLE
APP我的-钱包-保险-中间领京豆-签到 可得京豆

### ISSUE THREAD

**Issue by geelinsir** [6dylan6/jdpro#484]
建议大佬开发

**Comment by tpc188** [comment]
具体是：我的-保险服务-买保险-领京豆
任务名称：天天领权益

**Comment by 6dylan6** [comment]
> 具体是：我的-保险服务-买保险-领京豆 任务名称：天天领权益

金融的做不了

**Comment by geelinsir** [comment]
> > 具体是：我的-保险服务-买保险-领京豆 任务名称：天天领权益
> 
> 金融的做不了

是考虑风险问题吗？

**Comment by 6dylan6** [comment]
@geelinsir 嗯容易黑
