### ISSUE TITLE
临期京豆换积分

### ISSUE THREAD

**Issue by BNDou** [6dylan6/jdpro#49]
6佬，我记得之前临期换积分运行一次可以兑换好几次，现在怎么只兑换一次啦，是更新源码了吗，还是我的问题😁
![Screenshot_2023-07-14-22-57-02-282_com.android.browser.png](https://github.com/6dylan6/jdpro/assets/67632799/42367a35-08bd-4fdb-b8f5-77d94e413af1)

**Comment by 6dylan6** [comment]
@BNDou 这个只换积分，另一个换豆，拆分了

**Comment by BNDou** [comment]
> @BNDou 这个只换积分，另一个换豆，拆分了

您理解错我的意思了，我的意思是说号里还有3000多个临期豆，只兑换了500个，不应该循环几次全部兑换嘛

**Comment by 6dylan6** [comment]
@BNDou 不是，每次最多500，一直这样的
