### ISSUE TITLE
环境变量配置问题

### ISSUE THREAD

**Issue by ksweb2** [6dylan6/jdpro#495]
新农村活动提示太火爆：export FRUIT_NEW_DELAY='5' 延时，单位秒默认1，如果出现火爆，可尝试增加，我想增加这个延时，在config.sh里设置了：“export FRUIT_NEW_DELAY='10' ”，但是运行脚本还是显示：“export FRUIT_NEW_DELAY='5' ”。
请问大佬是哪里有问题

**Comment by 6dylan6** [comment]
@ksweb2 这只是日志输出固定提示啊，你设置后运行看看啊

**Comment by ksweb2** [comment]
对我在config.sh设置了
![image](https://github.com/user-attachments/assets/b5d4000b-4bb2-4a6d-b885-9370c3b853fc)
然后再次运行他的日志提示里还是这样的，还是你的意思是这个提示就是固定的，和改没改变量没关系
![image](https://github.com/user-attachments/assets/53bd8d0c-9cdf-47b1-9bf9-1dc340ade467)

**Comment by 6dylan6** [comment]
@ksweb2 你这开始就火爆，和延时没关系，手动进app看看，另外云服务器肯定火爆，跑不了的

**Comment by ksweb2** [comment]
好的谢谢

> @ksweb2 你这开始就火爆，和延时没关系，手动进app看看，另外云服务器肯定火爆，跑不了的
