### ISSUE TITLE
你好，请问有宠汪汪定时兑换京豆的脚本吗？

### ISSUE THREAD

**Issue by arsenalpoll** [6dylan6/jdpro#497]
入口：宠汪汪 --> 积分超值兑换 

![image](https://github.com/user-attachments/assets/5d0c3754-8a17-4b94-af0e-ea4970a17c09)

**Comment by 6dylan6** [comment]
@arsenalpoll 没有哈

**Comment by arsenalpoll** [comment]
> @arsenalpoll 没有哈

好的，感谢回复。

**Comment by geelinsir** [comment]
> > @arsenalpoll 没有哈
> 
> 好的，感谢回复。

应该是有验证码的
