### ISSUE TITLE
京东特价版任务报错，大佬怎么解决？

### ISSUE THREAD

**Issue by sdytwuph** [6dylan6/jdpro#5]
## 开始执行... 2023-05-30 10:59:49

🔔京东特价版任务, 开始!

====================共3个京东账号Cookie=================

============脚本执行时间：2023-5-30 10:59:50=============

>>>>>>>>>>>>>>6Dylan6 提示：任务正常运行中>>>>>>>>>>>>>>>

"Response code 403 (Forbidden)"
startItem API请求失败，请检查网路重试
"Response code 403 (Forbidden)"
startItem API请求失败，请检查网路重试
"Response code 403 (Forbidden)"
startItem API请求失败，请检查网路重试
检测到403，暂停2分钟后重试

**Comment by 6dylan6** [comment]
@sdytwuph 云服务器吗

**Comment by sdytwuph** [comment]
> @sdytwuph 云服务器吗

是的，应该是IP黑名单了，换服务器正常了
