### ISSUE TITLE
任务的执行时间问题

### ISSUE THREAD

**Issue by 939224390** [6dylan6/jdpro#50]
看着好多任务的执行时间是2024年1月1日 1 1 1 1* 
但这些任务有一部分是需要每天都跑的
![image](https://github.com/6dylan6/jdpro/assets/31273215/b75ed17c-035c-4592-8a35-466cfd15166f)

**Comment by 6dylan6** [comment]
这种需要手动设置，开卡、以及有黑的风险的都不会自动执行，反正有些考虑的，自己决定跑不跑

**Comment by 6dylan6** [comment]
还有些一次性的，也不会定时，自行看看文件注释
