### ISSUE TITLE
新农场商品

### ISSUE THREAD

**Issue by Yeung168** [6dylan6/jdpro#502]
请问大佬能另外搞一个查看新农场不同等级里面所含的商品吗？就是可以每天跑一下看看不同等级的树里面有哪些商品，然后我就可根据自己的需求去种树。因为它好像每天的商品都不一样，比如今天有这个，第二天种完想再换就没有了，毕竟他只能把树种完才能通过优惠券的入口进去看有什么商品。

**Comment by 6dylan6** [comment]
@Yeung168 没必要呀，不管种什么最后给优惠券可购买商品都一样啊

**Comment by Yeung168** [comment]
这个真不一样，我对比过了，比如等级3的树，我上周换了好几瓶洗衣液，这周想给朋友换点就没有了，不知道什么时候会再次上架，而且有些商品上周没有 这周就上新了，它应该是有个周期，可能隔两三天就上新或者下架一些东西。

**Comment by 6dylan6** [comment]
@Yeung168 是不一样的，不是说种植的不一样优惠券的商品不一样

**Comment by Yeung168** [comment]
就是优惠券里面的商品不一样，我也不知道是不是每天上新下架，反正不同的号 同一天的商品是一样的，所以跟号应该没关系。所以如果可以提前看的话，就能看看有没有自己想要的再去把树种完，这样就不会浪费。

**Comment by Yeung168** [comment]
原来现在换了界面，我还没更新过来，现在官方的那种就是我想要的了，不好意思打扰了

**Comment by 6dylan6** [comment]
@Yeung168 ok
