### ISSUE TITLE
❌ 京东资产统计, 失败! 原因: ReferenceError: WP_APP_TOKEN_ONE is not defined!

### ISSUE THREAD

**Issue by charleschangz** [6dylan6/jdpro#504]
🧧🧧🧧红包明细🧧🧧🧧
【红包总额】0.46元(今日总过期0.00) 
【全平台通用】0.46元 

❌ 京东资产统计, 失败! 原因: ReferenceError: WP_APP_TOKEN_ONE is not defined!

早上第一次运行好好的，后来就这样了，第一个账号就出错

**Comment by charleschangz** [comment]
切换过不同账号，都是第一个就停下来

**Comment by 6dylan6** [comment]
@charleschangz g更新

**Comment by charleschangz** [comment]
已解决
