### ISSUE TITLE
怎样实现自动禁用失效CK功能

### ISSUE THREAD

**Issue by HAN915** [6dylan6/jdpro#507]
在配置文件里写了export NOTIFY_AUTOCHECKCK="true"，但是好像没啥效果，有失效CK的时候也没见给它禁用了。
请大佬指点一下如何操作，谢谢。

**Comment by HAN915** [comment]
@6dylan6 这个文件不对的话要如何操作呢

**Comment by HAN915** [comment]
@6dylan6 大佬能不能详细说一下，没找到这方面教程，实在不知道怎么下手

**Comment by BNDou** [comment]
@HAN915 你每次拉库的时候青龙都会把它的sendnotify文件覆盖进来，所以需要把6神😀大佬的文件备份到青龙里面。

你环境是在本地机还是云端？就是把下面这个文件复制到你青龙的文件目录的deps这个文件里

```
https://github.com/6dylan6/jdpro/blob/main/sendNotify.js
```

我的直接目录粘贴进来，拉了一遍库，然后就覆盖过来了

![mmexport1669541315992.png](https://user-images.githubusercontent.com/67632799/204128172-8a24ceb9-7fdb-46a0-bb70-a8ae97302009.png)

**Comment by HAN915** [comment]
@BNDou 我是群晖docker跑的，把sendnotify.js放在/docker/ql/deps目录下，重新拉库并没有反应……
哎，头大……

**Comment by BNDou** [comment]
@HAN915 代码总共2447行，确定没过来？
参考一下这个议题 #302

**Comment by HAN915** [comment]
@6dylan6  我直接复制代码，把sendnotify.js里面的代码替换了，deps文件里也放了新的，但是只要订阅一更新，就又会变成青龙的sendnotify，实在被折磨的没脾气了
大佬能帮忙看一下不

**Comment by HAN915** [comment]
@6dylan6 搞定了大佬，我之前一直以为是docker目录下的/ql/deps，后来仔细找了找之前的问题，发现要先docker exec -it qinglong bash，然后到/ql/data/deps这个目录才对，替换掉就好了
