### ISSUE TITLE
农场可兑换提醒现在没了

### ISSUE THREAD

**Issue by xianyunleo** [6dylan6/jdpro#508]
农场可兑换提醒现在没了。记得以前有，提示兑换。现在没有提醒后，导致兑换过期。

**Comment by 6dylan6** [comment]
@xianyunleo 有的，你看看日志

**Comment by xianyunleo** [comment]
@6dylan6 请问看哪个日志文件

**Comment by xianyunleo** [comment]
@6dylan6 日志有，但是企业微信机器人没有发送消息

**Comment by xianyunleo** [comment]
每天的脚本更新通知一直是正常的

**Comment by xianyunleo** [comment]
@6dylan6 感觉和这个问题很像，https://github.com/6dylan6/jdpro/issues/493

**Comment by 6dylan6** [comment]
@xianyunleo 看新农场任务的日志，有没有发通知

**Comment by xianyunleo** [comment]
==============📣系统通知📣==============
新农场任务
【京东账号1】xxx
【提醒⏰】京家洁空调可伸缩挡风板防直吹挡板免打孔安装月子出风口防风罩挂式通用 伸缩挡风板【1个装】已种成
请去京东APP或微信小程序查看
点击弹窗即达

已种植完成，去自动种植下一个...
未获取到种植种植列表 奖励更新，请刷新页面重新选择


@6dylan6  日志有通知，但是没有收到通知啊

**Comment by 6dylan6** [comment]
@xianyunleo 哪里有发？没有发通知，你检查配置的key，脚本更新通知和这不是一个地方配置的，要在config。sh文件里export变量

**Comment by xianyunleo** [comment]
@6dylan6 谢谢提示。刚才在config.sh配置了，然后ck检查是有用的。之前只配了系统设置里的通知

**Comment by MulderLiu** [comment]
@xianyunleo 老哥 你ck通知正常了？ config.sh都配置的啥能发一下吗

**Comment by xianyunleo** [comment]
@MulderLiu 现在jdpro的脚本通知都正常。在 config.sh 文件不需要你自己写配置，人家有模板的，你把key填进去就行，我是企业微信机器人。

**Comment by MulderLiu** [comment]
@xianyunleo 我配置的是发送邮件，其他通知是可以正常收到邮件的，就是这个ck收不到 怪了
