### ISSUE TITLE
玩一玩的助力码在哪获取呀？

### ISSUE THREAD

**Issue by Arnold4869** [6dylan6/jdpro#510]
我搜了说运行下脚本有提示，但我看了下日志也没提示……

**Comment by 6dylan6** [comment]
@Arnold4869 玩一玩任务啊

**Comment by Arnold4869** [comment]
@6dylan6 运行了任务，也没找到，最后是自己通过分享的二维码，然后解码出来的链接里找到了。。。

**Comment by 6dylan6** [comment]
![image](https://github.com/user-attachments/assets/47001c87-ea36-4a6f-9a2d-cdc2794c542f)
日志没有这个？

**Comment by Arnold4869** [comment]
@6dylan6 没……

**Comment by Arnold4869** [comment]
@6dylan6 你这是哪个脚本里的日志？脚本方便说下吗？我看了几个玩一玩的脚本的日志都没这个

**Comment by Arnold4869** [comment]
可以了，是云服务器的问题，换成本地nas就没问题了

**Comment by Arnold4869** [comment]
关闭问题了哈
