### ISSUE TITLE
玩一玩助力5个人头就够了，默认判断满的话是10个人头

### ISSUE THREAD

**Issue by mijjjj** [6dylan6/jdpro#511]
玩一玩助力5个人头就够了，现在通过条件返回判断的话默认好像10个才显示助力不了了，改一下通过已助力的人数来控制

**Comment by 6dylan6** [comment]
@mijjjj 日志反馈信息发来看看，我没有满

**Comment by mijjjj** [comment]
看错了，尴尬了，邀请码前面都一样，就尾数不一样
