### ISSUE TITLE
玩一玩的助力的奖励，怎么不会领取？

### ISSUE THREAD

**Issue by winsphinx** [6dylan6/jdpro#513]
见图：
![微信图片_20241009070623](https://github.com/user-attachments/assets/ec4fc3b4-4c39-460b-9d90-62957a36ca2f)

**Comment by 6dylan6** [comment]
@winsphinx 运行任务啊

**Comment by winsphinx** [comment]
当然是运行任务跑的。其他任务都能运行，并成功领取。邀请好友的运行完了没领取。

**Comment by 6dylan6** [comment]
![image](https://github.com/user-attachments/assets/bf33afc1-26d7-4202-82ce-366bb8b5491d)
正常

**Comment by winsphinx** [comment]
我就没 领取好友奖励 那一步：

![image](https://github.com/user-attachments/assets/e63950e3-25f8-4588-af84-96387c7ff0ac)

**Comment by 6dylan6** [comment]
@winsphinx 再跑一次，这个要跑至少两次的，一开始没助力怎么领取

**Comment by winsphinx** [comment]
谢谢。想想也是这么个道理，但是怕跑黑。牛牛乐园都黑透了。。。

**Comment by 6dylan6** [comment]
@winsphinx 这个不会，合成系列都那样，黑几天就正常了
