### ISSUE TITLE
小程序超级省出错

### ISSUE THREAD

**Issue by formyangel1219** [6dylan6/jdpro#516]
当前省钱币余额：3380

今日已签到完成，已签4天

去做任务...
开始 ---去逛逛微信9.9包邮
开始 ---万人团官方补贴
开始 ---188元红包！进群速抽
开始 ---来农场浇水 领免费礼品
获得10省钱币！
超级爆品 低至1分---已完成
任务完成！
领取奖励...
系统异常，请稍后再试
任务完成！
领取奖励...
系统异常，请稍后再试
任务完成！
领取奖励...
系统异常，请稍后再试
任务完成！
领取奖励...
系统异常，请稍后再试

停止后再重新执行，提示领取成功。但是后面还是一样出错

**Comment by 6dylan6** [comment]
@formyangel1219 实际是领了，等会再跑看看吧

**Comment by formyangel1219** [comment]
今日已签到完成，已签4天

去做任务...
获得5省钱币！
获得5省钱币！
超级爆品 低至1分---已完成
去超级省领福利---已完成
去逛逛微信9.9包邮---已完成
万人团官方补贴---已完成

看起来是没领 ，停止后又跑了一遍，才提示领取成功。
然后下一个号又是：系统异常，请稍后再试，晚上再跑一次试试。

**Comment by formyangel1219** [comment]
今天还是一样的情况，所有号的完成任务后领奖励都出错了：系统异常，请稍后再试

再次执行可以成功领取

**Comment by 6dylan6** [comment]
@formyangel1219 嗯，等修

**Comment by 6dylan6** [comment]
已修复
