### ISSUE TITLE
执行任务脚本jddj_plantBeans.js

### ISSUE THREAD

**Issue by m511386374** [6dylan6/jdpro#52]
提示缺少依赖
![image](https://user-images.githubusercontent.com/19544200/155058947-1e537bde-9ffc-45c1-8f79-e93c334d06f1.png)

**Comment by 6dylan6** [comment]
请运行一遍依赖安装任务

**Comment by m511386374** [comment]
![image](https://user-images.githubusercontent.com/19544200/155069662-0d82d5de-8a19-44aa-a296-a671a002ac96.png)
![image](https://user-images.githubusercontent.com/19544200/155069709-46cdc72b-325f-436b-821a-eb549e7b878f.png)
已经依赖过了呀。

**Comment by 6dylan6** [comment]
哎呀依赖安装有bug，多了个s，更新了下，你在拉库更新再跑安装依赖。

**Comment by m511386374** [comment]
恩恩 更新依赖可以了。但是又遇到另一个问题
![image](https://user-images.githubusercontent.com/19544200/155094201-08328c44-0ec8-47f9-8f5b-161d9a2e5bd4.png)
这里报错了

**Comment by 6dylan6** [comment]
不是这里报错，你手动进去过这活动么。到家里的

**Comment by m511386374** [comment]
好像没有手动执行过到家里的活动
