### ISSUE TITLE
可以实现一下农场成熟的一对一通知吗。

### ISSUE THREAD

**Issue by SongJgit** [6dylan6/jdpro#526]
因为下面挂了不少同学的号，似乎他们的wxpusher无法收到单独的农场成熟的一对一通知。
能否仿照价保的那个给补充实现一下农场的

**Comment by 6dylan6** [comment]
@SongJgit 有一对一的，你看任务日志发了没

**Comment by SongJgit** [comment]
> @SongJgit 有一对一的，你看任务日志发了没
![image](https://github.com/user-attachments/assets/66ac02bc-3883-45a1-a0bf-f587c5cc442f)
就是这种，我问了一下，他们似乎收不到，只有我这个主号能收到

**Comment by 6dylan6** [comment]
@SongJgit 哦，农场是没有，资产通知会发一对一白嫖提醒的
