### ISSUE TITLE
wskey转换还是不行

### ISSUE THREAD

**Issue by charleschangz** [6dylan6/jdpro#53]
--------------------

5700端口检查通过
使用 id 键值

云端地址全部失效, 请检查网络!

尝试使用nolan接口请求

**Comment by 6dylan6** [comment]
@charleschangz Nolan接口也不行吗？

**Comment by charleschangz** [comment]
不检查账号有效性
--------------------

Params参数获取失败
pt_pin=aaa ;账号禁用

账号禁用成功
--------------------

**Comment by charleschangz** [comment]
--------------------

5700端口检查通过
使用 id 键值

云端地址全部失效, 请检查网络!

尝试使用nolan接口请求

pt_pin=charlesf;检索成功

不检查账号有效性
--------------------

Params参数获取失败
pt_pin=xxx;账号禁用

账号禁用成功
--------------------

**Comment by 6dylan6** [comment]
@charleschangz 更新试试，昨天我修了

**Comment by charleschangz** [comment]
最新的测试了，还是一样，只有我一个人这样么

**Comment by charleschangz** [comment]
Nolan连网站都访问不了了。

Public DNS 解析结果
未检测到 api.nolanstore.top 的 DNS 记录
DNS 服务商解析结果
未检测到 api.nolanstore.top 的 DNS 记录

**Comment by charleschangz** [comment]
不检查账号有效性
--------------------

Starting new HTTPS connection (1): api.nolanstore.top:443
Params参数获取失败
HTTPSConnectionPool(host='api.nolanstore.top', port=443): Max retries exceeded with url: /sign (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7f327edf6ef0>: Failed to establish a new connection: [Errno -2] Name does not resolve'))
