### ISSUE TITLE
东东农场-助力 这个脚本似乎没有生效

### ISSUE THREAD

**Issue by Deleted-Account** [6dylan6/jdpro#530]
脚本文件：6dylan6_jdpro/jd_farm_help.js
脚本日志：
```
开始【京东账号1】aaaaa

第1个京东账号将要助力的好友[""]
开始助力好友
去助力: 
助力好友结束，即将开始领取额外水滴奖励


今日已邀请好友0个 / 每日邀请上限4个
开始删除0个好友,可拿每天的邀请奖励
今日未邀请过好友
开始天天抽奖--好友助力--每人每天只有三次助力机会.

==============📣系统通知📣==============
东东农场-助力
【京东账号1🆔】aaaaa
【今日剩余助力👬】3次

开始【京东账号2】bbbbb

第2个京东账号将要助力的好友[""]
开始助力好友
去助力: 
助力好友结束，即将开始领取额外水滴奖励


今日已邀请好友0个 / 每日邀请上限4个
开始删除0个好友,可拿每天的邀请奖励
今日未邀请过好友
开始天天抽奖--好友助力--每人每天只有三次助力机会.

==============📣系统通知📣==============
东东农场-助力
【京东账号2🆔】bbbbb
【今日剩余助力👬】3次

开始【京东账号3】ccccc

第3个京东账号将要助力的好友[""]
开始助力好友
去助力: 
助力好友结束，即将开始领取额外水滴奖励


今日已邀请好友0个 / 每日邀请上限4个
开始删除0个好友,可拿每天的邀请奖励
今日未邀请过好友
开始天天抽奖--好友助力--每人每天只有三次助力机会.

==============📣系统通知📣==============
东东农场-助力
【京东账号3🆔】ccccc
【今日剩余助力👬】3次

开始【京东账号4】ddddd

第4个京东账号将要助力的好友[""]
开始助力好友
去助力: 
助力好友结束，即将开始领取额外水滴奖励


今日已邀请好友0个 / 每日邀请上限4个
开始删除0个好友,可拿每天的邀请奖励
今日未邀请过好友
开始天天抽奖--好友助力--每人每天只有三次助力机会.
```

实际上并没助力

运行环境：OpenWRT 上的 青龙 2.15.3 docker
拉库用的大佬您的命令，只在 deps 中使用了 ccwav 的 sendNotify.js，其他没动

**Comment by 2eronia** [comment]
> @Deleted-Account 运行获取互助码

可以了。谢谢

之前看了下 jd_sharecode.sh，为了用车头模式后面随机，怕每次更新订阅又把车头模式改回去，所以"获取互助码"单独 copy 了一份放在 /scripts 下运行的，看来放在 /6dylan6_jdpro 之外运行是不行的呀

再次感谢回复

**Comment by Deleted-Account** [comment]
> @Deleted-Account 运行获取互助码

可以了。谢谢

之前看了下 jd_sharecode.sh，为了用车头模式后面随机，怕每次更新订阅又把车头模式改回去，所以"获取互助码"单独 copy 了一份放在 /scripts 下运行的，看来放在 /6dylan6_jdpro 之外运行是不行的呀

再次感谢回复

**Comment by 2eronia** [comment]
> @Deleted-Account 用变量啊，不用改脚本

请教一下应该怎么弄呢？

我尝试在在配置文件中
export HelpType="3"
或者环境变量中添加 HelpType，值为3
运行 jd_sharecode.sh，日志显示 ## 采用"按编号优先"互助模板

**Comment by Deleted-Account** [comment]
> @Deleted-Account 用变量啊，不用改脚本

请教一下应该怎么弄呢？

我尝试在在配置文件中
export HelpType="3"
或者环境变量中添加 HelpType，值为3
运行 jd_sharecode.sh，日志显示 ## 采用"按编号优先"互助模板

**Comment by Deleted-Account** [comment]
> @Deleted-Account 看readme

谢谢。是我疏忽了，没好好看 readme
互助研究院的那个 code.sh 出来很久了也没仔细看过他们的帮助文档
