### ISSUE TITLE
一键价保

### ISSUE THREAD

**Issue by zhangzhen321625** [6dylan6/jdpro#533]
你好，一键价保怎么屏蔽某个CK不运行

**Comment by 6dylan6** [comment]
@zhangzhen321625 变量BANPIN禁止指定pin执行某任务
多个任务同pin：任务1|任务2@pin1,pin2  
多个任务不同pin：任务1@pin,pin2&任务2@pin2,pin3
不指定任务只写pin  全部任务都不执行

**Comment by zhangzhen321625** [comment]
> @zhangzhen321625 变量BANPIN禁止指定pin执行某任务 多个任务同pin：任务1|任务2@pin1,pin2 多个任务不同pin：任务1@pin,pin2&任务2@pin2,pin3 不指定任务只写pin 全部任务都不执行

这个pin值 是怎么写的，如果是第8个CK的话是怎么写。谢谢

**Comment by zhangzhen321625** [comment]
已经可以了，谢谢
