### ISSUE TITLE
新农村浇水报错AggregateError

### ISSUE THREAD

**Issue by wuiiled** [6dylan6/jdpro#534]
❌ 新农场任务, 失败! 原因: AggregateError!

🔔新农场任务, 结束! 🕛 2.61 秒

请问这是什么原因造成的？

**Comment by 6dylan6** [comment]
@wuiiled 没见过这种报错，其他正常吗，再跑一次看看

**Comment by wuiiled** [comment]
> @wuiiled 没见过这种报错，其他正常吗，再跑一次看看

其他都正常，重新跑也是报错这个

**Comment by luokuncool** [comment]
和你遇到一样的问题了，我最后找到是adguardhome把`gia.jd.com`这个给拦截了。  
最后加了个允许的规则就可以了`@@||gia.jd.com^$important`  


![image](https://github.com/user-attachments/assets/35fadf2f-275c-440e-946e-03094b39c759)

**Comment by wuiiled** [comment]
> 和你遇到一样的问题了，我最后找到是adguardhome把`gia.jd.com`这个给拦截了。 最后加了个允许的规则就可以了`@@||gia.jd.com^$important`
> 
> ![image](https://private-user-images.githubusercontent.com/6022635/379195938-35fadf2f-275c-440e-946e-03094b39c759.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3Mjk2OTgwOTEsIm5iZiI6MTcyOTY5Nzc5MSwicGF0aCI6Ii82MDIyNjM1LzM3OTE5NTkzOC0zNWZhZGYyZi0yNzVjLTQ0MGUtOTQ2ZS0wMzA5NGIzOWM3NTkucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MTAyMyUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDEwMjNUMTUzNjMxWiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9ZjM1ZjAwYWQ2ZmQ2MzhiODVhMTFjN2JmODc2MWM4YjQ3OTQ3YTNhZTg3MjQwODIxNWM4ODg4ZmQyYjlhZWRiMCZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QifQ.Ja9_1JFoouE-3KTv3HcGrVpwEmfiLXicR0RbiF1iv4s)

确实是这样，非常感谢
