### ISSUE TITLE
自动评价会因为某些特殊订单而卡住

### ISSUE THREAD

**Issue by SongJgit** [6dylan6/jdpro#537]
最近突然发现，有些订单可能会导致该账号的所有评价都卡住。
比如下面这个一共有11个待评价，从最后一个开始，但是最后一个评价失败了，这个账号就结束了，然后下次还是会失败，又结束了，就相当于这个账号被某个失败的订单卡住了。
这类订单是可能是因为商品下架了，无法评论或者是商品下面本身无评论导致的脚本自动评价失败。然后京东APP手动一键评价这个卡住的订单之后，后面的不是这种奇怪的订单的就会顺利的都完成评价了。
![image](https://github.com/user-attachments/assets/13c47061-4961-4db5-a427-8871f61c1569)
以及下面这个，有137个待评价，但是由于最后一页的七个始终无法评价，导致所有的订单都失败了，然后下次自动评价就还是从这7个开始。
![image](https://github.com/user-attachments/assets/0f7a029a-cb10-43be-be42-0c853222f549)

**Comment by 6dylan6** [comment]
@SongJgit 好的

**Comment by 6dylan6** [comment]
没有评价的商品卡那里已解决，403这个暂时无解，有些账号可能风控，用不了
