### ISSUE TITLE
领京豆签到脚本好像挂了--jd_signbeanact.js

### ISSUE THREAD

**Issue by 2604237845** [6dylan6/jdpro#54]
*****开始【京东账号1】jd_XXXXX****

DEBUG2:"{\"code\":\"0\",\"errorCode\":\"S100\",\"errorMessage\":\"当前签到人数较多，请稍晚再来\"}"

*****开始【京东账号2】jd_XXXXX****

DEBUG2:"{\"code\":\"0\",\"errorCode\":\"S100\",\"errorMessage\":\"当前签到人数较多，请稍晚再来\"}"

**Comment by 6dylan6** [comment]
@2604237845 更新
