### ISSUE TITLE
用了代理地址还一直拉去失败是怎么回事

### ISSUE THREAD

**Issue by Nepenlos** [6dylan6/jdpro#547]
## 开始执行... 2024-10-20 15:18:03

开始拉取仓库 6dylan6_jdpro 到 /ql/data/repo/6dylan6_jdpro

fatal: unable to access 'https://js.okyago.com/https://github.com/6dylan6/jdpro.git/': SSL connection timeout

拉取 6dylan6_jdpro 失败，请检查日志...

## 开始执行... 2024-10-20 14:06:28

开始拉取仓库 6dylan6_jdpro 到 /ql/data/repo/6dylan6_jdpro

error: RPC failed; curl 56 Recv failure: Connection reset by peer
error: 4069 bytes of body are still expected

fetch-pack: unexpected disconnect while reading sideband packet
fatal: early EOF
fatal: fetch-pack: invalid index-pack output

拉取 6dylan6_jdpro 失败，请检查日志...

**Comment by 6dylan6** [comment]
去掉代理试试，青龙什么版本

**Comment by Nepenlos** [comment]
> 去掉代理试试，青龙什么版本

2.17.11 运行在黑裙上，删掉代理直接拉也不行，不知道是不是config有问题

**Comment by Nepenlos** [comment]
> > 去掉代理试试，青龙什么版本
> 
> 2.17.11 运行在黑裙上，删掉代理直接拉也不行，不知道是不是config有问题
