### ISSUE TITLE
wsky转换脚本不能用了

### ISSUE THREAD

**Issue by greenwave1987** [6dylan6/jdpro#55]
已解决，自己环境问题

**Comment by greenwave1987** [comment]
![Uploading Screenshot_20230725_195345_com.huawei.browser_edit_867435161815552.jpg…]()

**Comment by greenwave1987** [comment]
![Uploading Screenshot_20230725_195345_com.huawei.browser_edit_867435161815552.jpg…]()

**Comment by greenwave1987** [comment]
已解决，个例

**Comment by 839777408** [comment]
请问下wsky是咋弄的，最近cookie一直掉

**Comment by charleschangz** [comment]
你是怎么解决的。
