### ISSUE TITLE
农场幸运大转盘抽奖错误

### ISSUE THREAD

**Issue by lyb1992** [6dylan6/jdpro#552]
![63e08a9cdea4e4c65c8f237fd2b088a](https://github.com/user-attachments/assets/257c0ce8-644d-4d19-85d1-c2f0c7898422)
任务完成，但是抽奖失败，每天浪费了抽奖次数，大佬帮忙看看

**Comment by 6dylan6** [comment]
@lyb1992 这个黑ip严重，要么等会再跑要么用代理

**Comment by kkwwang** [comment]
403要怀疑账号和网络，和脚本无关了
