### ISSUE TITLE
带图评价是不能用了吗？

### ISSUE THREAD

**Issue by HAN915** [6dylan6/jdpro#567]
日志报错如下

read ECONNRESET

❌ 带图评价-加密, 失败! 原因: TypeError: Cannot read properties of undefined (reading 'maxPage')!

**Comment by tpc188** [comment]
一样的问题

**Comment by huhao0208** [comment]
faker仓库的可以

**Comment by HAN915** [comment]
现在可以用了，我也不知道怎么就好了
