### ISSUE TITLE
CK检测脚本似乎失效了

### ISSUE THREAD

**Issue by ZGCloud-ZGY** [6dylan6/jdpro#568]
看了一下日志，失败的都报
HTTPError: Response code 401 (Unauthorized)
更新完CK，又都能把信息报出来

话说能不能给每个脚本增加一个，如果CK失效就自动禁用的功能？

![image](https://github.com/user-attachments/assets/db9bb41d-d6ba-43b2-8e76-a85ad593f67d)

**Comment by 6dylan6** [comment]
@ZGCloud-ZGY 一直都有啊，需要用库里的通知文件，设置变量export NOTIFY_AUTOCHECKCK=true
