### ISSUE TITLE
乐养园一直在重试，正常吗？

### ISSUE THREAD

**Issue by lunati-wei** [6dylan6/jdpro#57]
重试】
合成 102297 <=> 102298 失败！【blackfail】 code=1006
开始合成 15 102297 <=> 102298 【限流严重，5秒后合成！如失败会重试】
合成 102297 <=> 102298 失败！【blackfail】 code=1006
开始合成 15 102298 <=> 102297 【限流严重，5秒后合成！如失败会重试】
合成 102298 <=> 102297 失败！【blackfail】 code=1006
开始合成 15 102297 <=> 102298 【限流严重，5秒后合成！如失败会重试】

**Comment by 6dylan6** [comment]
死循環了，已修付。

**Comment by lunati-wei** [comment]
好的，辛苦
