### ISSUE TITLE
最近貌似无法互助了？

### ISSUE THREAD

**Issue by jjj333** [6dylan6/jdpro#57]
库已经拉了N次了，脚本都更新到7月最新版了，但是查看jd_fruit的日志发现如下报错，每个账号最后都是这样，然后从jd客户端里看互助栏都是空的，具体报错信息如下：

初始化任务列表
给好友浇水的25g水滴奖励已领取

小鸭子游戏达到上限
执行再次浇水
开始检查剩余水滴能否再次浇水再次浇水

任务执行异常，请检查执行日志 ‼️‼️

❗️东东农场-任务, 错误!
TypeError: Cannot read properties of undefined (reading 'totalEnergy')
    at doTenWaterAgain (/ql/data/scripts/6dylan6_jdpro_main/jd_fruit.js:362:46)
    at async jdFruit (/ql/data/scripts/6dylan6_jdpro_main/jd_fruit.js:127:17)
    at async /ql/data/scripts/6dylan6_jdpro_main/jd_fruit.js:74:13

**Comment by jjj333** [comment]
还有个现象就是运行获取互助码脚本提示从日志里找不到互助码，但是种豆得豆内部互助的日志里是有每个账号的互助码的

**Comment by 6dylan6** [comment]
@jjj333 看看助力的运行日志

**Comment by jjj333** [comment]
有助力码，但是显示没有助力机会了，从第一个账号开始就这样了。不知道助给谁了。app里看也确实没有助力机会了

**Comment by 6dylan6** [comment]
@jjj333 看的是每日第一次执行的日志吗

**Comment by jjj333** [comment]
> @jjj333 看的是每日第一次执行的日志吗

好吧，并不是，又看了一次完整的日志记录，都报如下错误：

东东农场: API查询请求失败 ‼️‼️
"getaddrinfo EAI_AGAIN api.m.jd.com"

❗️东东农场-助力, 错误!

任务执行异常，请检查执行日志 ‼️‼️

❗️东东农场-助力, 错误!
TypeError: Cannot read properties of undefined (reading 'farmUserPro')
    at jdFruit (/ql/data/scripts/6dylan6_jdpro_main/jd_farm_help.js:70:24)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async /ql/data/scripts/6dylan6_jdpro_main/jd_farm_help.js:56:13
