### ISSUE TITLE
狂聚好物约惠生活运行报错

### ISSUE THREAD

**Issue by Doapeat** [6dylan6/jdpro#581]
这个任务运行报错，尝试更新脚本和依赖并且重启之后仍然无效，由于不是相关专业，看不懂报错信息，来求助一下大佬
![image](https://github.com/user-attachments/assets/25f440cc-8243-4bc9-85f0-985bf7b22cd0)

**Comment by 6dylan6** [comment]
@Doapeat 依赖管理里面删除ds，不要乱装依赖，没必要的装了会出问题

**Comment by Doapeat** [comment]
感谢回复，问题已解决
