### ISSUE TITLE
发现首页炸年兽 自动组队,如何取消？

### ISSUE THREAD

**Issue by insoxin** [6dylan6/jdpro#582]
![8C0A74E0-ADC4-4B73-B146-539C65A25AEB](https://user-images.githubusercontent.com/19371836/211705368-553c775c-82a4-43fd-9a27-9310ff2b124f.png)

**Comment by insoxin** [comment]
> @insoxin ck泄露了呗，改密码

只用了大佬的脚本啊

**Comment by insoxin** [comment]
没排查点了   刚修改了了密码

**Comment by xfchu1988** [comment]
我也有ck被偷自动组队的，说明这个大佬是高手，炸年兽还能玩，厉害！
