### ISSUE TITLE
农场幸运转盘代理问题

### ISSUE THREAD

**Issue by davidoff0210** [6dylan6/jdpro#585]
小白一个，请多多包涵
运行农场转盘配置了携趣的代理url，出现下面这种现象，要怎么解决呢？
![image](https://github.com/user-attachments/assets/53068d2f-d5fb-427f-9628-2555ae5884dc)

**Comment by 6dylan6** [comment]
@davidoff0210 ip提太多了，配置提1个

**Comment by davidoff0210** [comment]
感谢🙏大佬
