### ISSUE TITLE
导入的任务时间设定上有问题

### ISSUE THREAD

**Issue by 939224390** [6dylan6/jdpro#59]
![image](https://github.com/6dylan6/jdpro/assets/31273215/0725b0ab-25ec-41e0-ae31-d17d2bfb1130)
![image](https://github.com/6dylan6/jdpro/assets/31273215/29e1ed0c-e8c3-48c1-8eaf-dc7080a7b04f)
看起来应该是每日执行的任务，但是时间设定上是每年执行一次

**Comment by 6dylan6** [comment]
@939224390 这种需要手动设置，开卡、以及有黑的风险的都不会自动执行，反正有些考虑的，自己决定跑不跑

**Comment by 6dylan6** [comment]
@6dylan6 还有些一次性的，也不会定时，自行看看文件注释
