### ISSUE TITLE
各位大佬，请问京豆临期续命怎么设置参数？

### ISSUE THREAD

**Issue by Timoshao** [6dylan6/jdpro#591]
![image](https://user-images.githubusercontent.com/108260847/215237543-53fef1bf-610f-403c-94b0-f38705117629.png)

**Comment by Timoshao** [comment]
> @Timoshao 变量不会设置吗。。。

不知道去哪里设置，刚接触

**Comment by Timoshao** [comment]
@6dylan6  不知道去哪里设置 刚接触这个东西

**Comment by basten1899** [comment]
不会就设置就把12-15行 直接删了

**Comment by Timoshao** [comment]
> 不会就设置就把12-15行 直接删了

成功了 谢谢

**Comment by Timoshao** [comment]
知道怎么搞了 变量在config.sh文件中配置就好了
