### ISSUE TITLE
农场出现火爆

### ISSUE THREAD

**Issue by cz15632** [6dylan6/jdpro#594]
大佬，部分账号出现农场无法浇水，报错是
“初始化农场数据异常, 请登录京东 app查看农场0元水果功能是否正常,农场初始化数据: {"code":"404","message":"运行环境异常，请您从正规渠道参与活动，稍后再试哦"}”
请问下这个是风控还是哪里的问题呢

**Comment by 6dylan6** [comment]
@cz15632 老的还是新的

**Comment by hiscatwang** [comment]
新的> @cz15632 老的还是新的

**Comment by cz15632** [comment]
新的，光猫重启之后可能是ip刷新了，现在大部分号正常了，但是有一个号却显示：“还未选择种植目标，去选择...
任务执行异常，请检查执行日志 ‼️‼️



❗️新农场任务, 错误!
Cannot read properties of undefined (reading 'farmLevelTrees')”
但是这个号手机上看是正常的

**Comment by cz15632** [comment]
@6dylan6 @hiscatwang 解决了解决了，家里光猫重启了一下再跑就正常了，可能是ip太久没刷新了，以前没见过说正规渠道什么的我还以为是哪里出错了，感谢大佬
