### ISSUE TITLE
Jd抽现金100无法自动提现

### ISSUE THREAD

**Issue by leifeng-N** [6dylan6/jdpro#6]
开始抽奖和提现：

开始【账号1】jd_gzJWwkjHLoJJ

当前有0次抽奖机会！
"Response code 403 (Forbidden)"
 API请求失败，请检查网路重试

开始【账号2】jd_iVNKlBDUosin

当前有0次抽奖机会！
"Response code 403 (Forbidden)"
 API请求失败，请检查网路重试

**Comment by leifeng-N** [comment]
无法拉库，修复了也一样。网络正常。。国内国外一样无法拉库

开始克隆仓库 https://github.com/6dylan6/jdpro.git 到 /ql/data/repo/6dylan6_jdpro


Cloning into '/ql/data/repo/6dylan6_jdpro'...

error: RPC failed; curl 18 Transferred a partial file

fatal: expected flush after ref listing


更新/ql/data/repo/6dylan6_jdpro失败，请检查网络...

**Comment by 6dylan6** [comment]
@leifeng-N 进青龙/ql/data/repo目录，手动删除库目录，再更新

**Comment by leifeng-N** [comment]
> @leifeng-N 进青龙/ql/data/repo目录，手动删除库目录，再更新

好的。顺利拉库tks
