### ISSUE TITLE
关于任务分组

### ISSUE THREAD

**Issue by hushaoyu** [6dylan6/jdpro#60]
请问下，如果需要对ck进行任务分组，分成多组，应该怎么设置，试了下，一组可以成功，但是多组不行。另外，分组可以和并发一起设置吗？

**Comment by 6dylan6** [comment]
自己手动建任务

**Comment by hushaoyu** [comment]
> 自己手动建任务

如果某一个任务需要分两组运行，意思是需要拷贝一份当前任务，再配置分组参数？

**Comment by 6dylan6** [comment]
是的，原任务也修改，不然是全部都跑。一般原任务从1开始这样分

**Comment by hushaoyu** [comment]
> 是的，原任务也修改，不然是全部都跑。一般原任务从1开始这样分

好的，感谢！
