### ISSUE TITLE
关于任务通知的关闭推送

### ISSUE THREAD

**Issue by cz15632** [6dylan6/jdpro#600]
大佬，有看到这边的脚本有ccwav/QLScript2的，它的说明中提到“(1) NOTIFY_SKIP_LIST
如果通知标题在此变量里面存在(&隔开),则用屏蔽不发送通知.(PS: Ningjia 作者写的功能，继承过来.)	
例子 :  export NOTIFY_SKIP_LIST="京东CK检测&京东资产变动"”
我是青龙中部署的，用的是pushplus推送，在环境变量和config.sh中都分别尝试了加入该变量，内容是“export NOTIFY_SKIP_LIST=" 互动消息检查&京东资产统计&京东调研问卷"”以及下方的：“(14) NOTIFY_SKIP_TEXT”也进行了尝试，
但是似乎都无法屏蔽通知，脚本还是正常发送通知，不知道是该功能被删除还是修改了变量名称呢，以及现在还有办法把指定的脚本通知关闭吗

**Comment by 6dylan6** [comment]
@cz15632 #禁用通知
export NOTIFY_SKIP_LIST="金融养猪&京东摇钱树"
确定你的通知文件是没错

**Comment by cz15632** [comment]
因为那几个平常不需要推送很多，所以指定的是那三个程序，但是确实是不起作用，三个程序都还会正常通知

**Comment by 6dylan6** [comment]
@cz15632 所以你确定下你用的通知文件对不对啊，脚本管理里看看sendnotify,js

**Comment by cz15632** [comment]
就是整个拉库的，但是刚才看了一下跟现在库里面的通知程序不完全一样，我就把库里面的完整复制过来了，但是运行之后还是一样的正常通知

**Comment by cz15632** [comment]
@6dylan6 解决了，确实是通知文件不一样导致的，但我是直接拉库的，不知道为啥会出现这种情况，jd下面的通知程序和青龙自带的通知程序一样，不管怎么说还是感谢大佬的解答

**Comment by 6dylan6** [comment]
@cz15632 青龙机制，会从deps目录下拷贝自带的sendnotify文件,所以要替换掉这个默认的
