### ISSUE TITLE
拉取仓库的时候只能拉去两个文件

### ISSUE THREAD

**Issue by liuyongyong6699** [6dylan6/jdpro#603]
如图，挂代理不挂代理都是这个样子的
![image](https://user-images.githubusercontent.com/54737383/218758846-ed7cda1f-ee79-42a1-b2bd-3969fc2dc123.png)
![image](https://user-images.githubusercontent.com/54737383/218758909-9364acea-f89d-4ac4-852a-776e4c7fb001.png)
使用青龙的订阅拉和直接在任务里面拉，日志都是一样的

**Comment by liuyongyong6699** [comment]
已解决，尝试进入青龙文件夹script中手动删除已经拉取的仓库
![image](https://user-images.githubusercontent.com/54737383/218760990-3f16d92b-cfe9-4c0b-86ba-fe0eae452037.png)

**Comment by szj1214** [comment]
> 不行呀，删除了还是只能拉取两个 ![image](https://user-images.githubusercontent.com/58980879/218913189-3309b1ee-e434-4a12-8901-b199cb1c5b93.png)

更换拉取命令为 ql repo https://ghproxy.com/https://github.com/6dylan6/jdpro.git "jd_|jx_|jddj_" "backUp" "^jd[^_]|USER|JD|function|sendNotify" "main" 可以了，就是后面要加 "main" 才能拉下来
