### ISSUE TITLE
新农场今天报错

### ISSUE THREAD

**Issue by ctxwzc** [6dylan6/jdpro#604]
❗️新农场任务, 错误!
connect ECONNREFUSED 172.17.0.4:8080

❗️新农场任务, 错误!
connect ECONNREFUSED 172.17.0.4:8080

❌ 新农场任务, 失败! 原因: Error: connect ECONNREFUSED 172.17.0.4:8080!

**Comment by 6dylan6** [comment]
@ctxwzc 你检查你网络，代理了？
