### ISSUE TITLE
购物车清空

### ISSUE THREAD

**Issue by rongyihui** [6dylan6/jdpro#609]
变量RMVCART='true设置了，还是不执行

![微信截图_20241119220252](https://github.com/user-attachments/assets/7f1e835e-b6c0-4fe4-a261-53824bba28d0)
![微信截图_20241119220559](https://github.com/user-attachments/assets/b96c9525-2763-4249-a0d1-fc7d244d3d02)

**Comment by 6dylan6** [comment]
@rongyihui 在配置文件config.sh里最后一行添加export RMVCART='true‘，，这种变量不要放到环境变量里

**Comment by rongyihui** [comment]
解决了，非常感谢！！！！
