### ISSUE TITLE
种豆得豆脚本不能用了吗？

### ISSUE THREAD

**Issue by sunopen1979** [6dylan6/jdpro#61]
第1个京东账号将要助力的好友[""]
获取任务及基本信息
undefined
种豆得豆-初始失败:  {"code":"1","echo":"no access"}

**Comment by 6dylan6** [comment]
@sunopen1979 你多久没更新了。更新不成功执行拉库失败修复在更新

**Comment by sunopen1979** [comment]
更新都是自动的，没报错我一直以为更新成功了呢，执行拉库失败之后再更新就好了

**Comment by sunopen1979** [comment]
运行了一个账号之后就出错误 
 
获取任务及基本信息
undefined
种豆得豆-初始失败:  {"code":"3"}

然后
【访问接口次数达到3次，休息一分钟.....】
继续运行第四个账号，然后又是错误

进入app打开活动都正常

**Comment by sunopen1979** [comment]
唉，不好意思 {"code":"3"} 是 cookie失效了
