### ISSUE TITLE
携趣代理报错

### ISSUE THREAD

**Issue by ghost** [6dylan6/jdpro#615]
![image](https://github.com/user-attachments/assets/b8906e98-e83b-4210-8261-be1b1f7a4497)

**Comment by 6dylan6** [comment]
@SherryHanTech 提取一个，你提太多了

**Comment by ghost** [comment]
> @SherryHanTech 提取一个，你提太多了

解决了，作者，谢谢
但是还是无法执行任务
'''
"Unsupported `GLOBAL_AGENT.HTTP_PROXY` configuration value: URL must not have query."
getgo 请求失败，请检查网路重试
"Unsupported `GLOBAL_AGENT.HTTP_PROXY` configuration value: URL must not have query."
getgo 请求失败，请检查网路重试

种豆得豆: API查询请求失败 ‼️‼️
function_id:plantBeanIndex

❗️种豆得豆任务, 错误!
Unsupported `GLOBAL_AGENT.HTTP_PROXY` configuration value: URL must not have query.

❗️种豆得豆任务, 错误!
Cannot read properties of undefined (reading 'errorCode')
'''

**Comment by 6dylan6** [comment]
@SherryHanTech 你代理配置有问题吧。GLOBAL_AGENT.HTTP_PROXY 这个什么？

**Comment by ghost** [comment]
> @SherryHanTech 你代理配置有问题吧。GLOBAL_AGENT.HTTP_PROXY 这个什么？

export DP_POOL='携趣代理api地址'
export PERMIT_JS='farm&plant&opencard'
