### ISSUE TITLE
JD的cookie已改变格式

### ISSUE THREAD

**Issue by uoow** [6dylan6/jdpro#616]
请问下，现在的cookie里并不包含脚本需要的格式：正确格式为: pt_key=xxx;pt_pin=xxx;（分号;不可少）
脚本的变量要怎么填？

**Comment by 6dylan6** [comment]
@uoow 在环境变量里添加JD_COOKIE

**Comment by uoow** [comment]
> @uoow 在环境变量里添加JD_COOKIE

并不是怎么设置cookie，而是怎么获取。在登录了JD后，F12打开请求头里得到的cookie里，已经没有了pt_key、pt_pin这两项，那这个JD_COOKIE变量里应该填什么内容？

**Comment by 6dylan6** [comment]
@uoow 电脑版的抓不到的，手机抓

**Comment by uoow** [comment]
> @uoow 电脑版的抓不到的，手机抓

@6dylan6 项目里没有怎么抓的说明，用手机抓是不是要安装特殊的app？能否补充在说明里？谢谢！

**Comment by 6dylan6** [comment]
@uoow 基操拉，不会百度搜也一堆

**Comment by uoow** [comment]
> @uoow 基操拉，不会百度搜也一堆

这样啊，好的，感谢。有空再研究一下互助码
