### ISSUE TITLE
农场提示植物枯萎了，但是实际有在种东西，请问怎么处理

### ISSUE THREAD

**Issue by noonecheck** [6dylan6/jdpro#621]
![IMG_20241126_094246.jpg](https://github.com/user-attachments/assets/07ad0fcb-4802-4d00-aa81-397a6ed080bd)

**Comment by zhhdfsdfsdf** [comment]
你看看好像奖品没选择

**Comment by noonecheck** [comment]
> 你看看好像奖品没选择

好的，谢谢
