### ISSUE TITLE
乐园脚本不能正常工作

### ISSUE THREAD

**Issue by Nepenlos** [6dylan6/jdpro#624]
******开始【京东账号2】jd_HRViVuQaqXTr*********

"Response code 403 (Forbidden)"
getJoyBaseInfo API请求失败，请检查网路重试

🔔牛牛乐园合成, 结束! 🕛 5.367 秒
******开始【京东账号2】jd_HRViVuQaqXTr*********

"Response code 403 (Forbidden)"
getJoyBaseInfo API请求失败，请检查网路重试
=== 任务列表 start ===
下单任务(指定SKU商品组) 0/1
下单任务(指定SKU商品组) 0/1
下单任务(指定SKU商品组) 0/1
全量下单任务 0/1
汪汪乐园邀请好友 0/1
汪汪乐园签到 1/1
汪汪乐园浏览商品 1/1
汪汪乐园浏览商品 5/5
=== 任务列表 end  ===

======开始内部互助======

🔔牛牛赚钱任务, 结束! 🕛 9.731 秒
******开始【京东账号1】18725444412_p*********

"Response code 403 (Forbidden)"
getJoyBaseInfo API请求失败，请检查网路重试

******开始【京东账号2】jd_HRViVuQaqXTr*********

"Response code 403 (Forbidden)"
getJoyBaseInfo API请求失败，请检查网路重试

🔔汪汪庄园合成, 结束! 🕛 5.523 秒

手机端访问正常

**Comment by 6dylan6** [comment]
@Nepenlos 你不是最新版，更新

**Comment by Nepenlos** [comment]
> @Nepenlos 你不是最新版，更新

## 开始执行... 2024-11-30 16:13:40



🔔牛牛乐园合成, 开始!

====================共2个京东账号Cookie=================
===========脚本执行时间：2024/11/30 16:13:41============
>>>>>>>>>>>>6dylan6提醒您：有问题先更新不行在反馈>>>>>>>>>>>>>


当前版本：20241126
跑几次可能会黑，一周后解除
问题建议：https://t.me/dylan_jdpro


******开始【京东账号1】18725444412_p*********

"Response code 403 (Forbidden)"
getJoyBaseInfo API请求失败，请检查网路重试

===== JOY 状态 start =====
在逛街的JOY ⬇️⬇️⬇️⬇️⬇️⬇️⬇️⬇️
id:664671|name: 旅行牛|level: 18
id:664575|name: 航海牛|level: 20
id:664665|name: 飞行牛|level: 19
id:661707|name: 叮当牛|level: 21
id:664668|name: 旅行牛|level: 18

在铲土的JOY ⬇️⬇️⬇️⬇️⬇️⬇️⬇️⬇️
工位: 1 [已开]|JOY= 空位
工位: 2 [已开]|JOY= 空位
工位: 3 [未开]|JOY= 空位
工位: 4 [未开]|JOY= 空位
工位: 5 [未开]|JOY= 空位
===== JOY 状态  end  =====

工位清理完成！
"Response code 403 (Forbidden)"
getJoyBaseInfo API请求失败，请检查网路重试

❗️牛牛乐园合成, 错误!
Cannot read properties of undefined (reading 'fastBuyLevel')


******开始【京东账号2】jd_HRViVuQaqXTr*********

"Response code 403 (Forbidden)"
getJoyBaseInfo API请求失败，请检查网路重试

===== JOY 状态 start =====
在逛街的JOY ⬇️⬇️⬇️⬇️⬇️⬇️⬇️⬇️
id:637787|name: 飞行牛|level: 19
id:639311|name: 飞行牛|level: 19

在铲土的JOY ⬇️⬇️⬇️⬇️⬇️⬇️⬇️⬇️
工位: 1 [已开]|JOY= 空位
工位: 2 [已开]|JOY= 空位
工位: 3 [未开]|JOY= 空位
工位: 4 [未开]|JOY= 空位
工位: 5 [未开]|JOY= 空位
===== JOY 状态  end  =====

工位清理完成！
"Response code 403 (Forbidden)"
getJoyBaseInfo API请求失败，请检查网路重试

❗️牛牛乐园合成, 错误!
Cannot read properties of undefined (reading 'fastBuyLevel')

🔔牛牛乐园合成, 结束! 🕛 17.247 秒


## 执行结束... 2024-11-30 16:13:58  耗时 18 秒　　　　　
最新版，还是403

**Comment by Nepenlos** [comment]
> @Nepenlos 你不是最新版，更新

## 开始执行... 2024-11-30 16:22:32



🔔牛牛乐园合成, 开始!

====================共2个京东账号Cookie=================
===========脚本执行时间：2024/11/30 16:22:33============
>>>>>>>>>>>>6dylan6提醒您：有问题先更新不行在反馈>>>>>>>>>>>>>


当前版本：20241126
跑几次可能会黑，一周后解除
问题建议：https://t.me/dylan_jdpro


******开始【京东账号1】18725444412_p*********

"Response code 403 (Forbidden)"
getJoyBaseInfo API请求失败，请检查网路重试

===== JOY 状态 start =====
在逛街的JOY ⬇️⬇️⬇️⬇️⬇️⬇️⬇️⬇️
id:664671|name: 旅行牛|level: 18
id:664668|name: 旅行牛|level: 18
id:664575|name: 航海牛|level: 20
id:664665|name: 飞行牛|level: 19
id:661707|name: 叮当牛|level: 21

在铲土的JOY ⬇️⬇️⬇️⬇️⬇️⬇️⬇️⬇️
工位: 1 [已开]|JOY= 空位
工位: 2 [已开]|JOY= 空位
工位: 3 [未开]|JOY= 空位
工位: 4 [未开]|JOY= 空位
工位: 5 [未开]|JOY= 空位
===== JOY 状态  end  =====

工位清理完成！
"Response code 403 (Forbidden)"
getJoyBaseInfo API请求失败，请检查网路重试

❗️牛牛乐园合成, 错误!
Cannot read properties of undefined (reading 'fastBuyLevel')


******开始【京东账号2】jd_HRViVuQaqXTr*********

"Response code 403 (Forbidden)"
getJoyBaseInfo API请求失败，请检查网路重试

===== JOY 状态 start =====
在逛街的JOY ⬇️⬇️⬇️⬇️⬇️⬇️⬇️⬇️
id:637787|name: 飞行牛|level: 19
id:639311|name: 飞行牛|level: 19

在铲土的JOY ⬇️⬇️⬇️⬇️⬇️⬇️⬇️⬇️
工位: 1 [已开]|JOY= 空位
工位: 2 [已开]|JOY= 空位
工位: 3 [未开]|JOY= 空位
工位: 4 [未开]|JOY= 空位
工位: 5 [未开]|JOY= 空位
===== JOY 状态  end  =====

工位清理完成！
"Response code 403 (Forbidden)"
getJoyBaseInfo API请求失败，请检查网路重试

❗️牛牛乐园合成, 错误!
Cannot read properties of undefined (reading 'fastBuyLevel')

🔔牛牛乐园合成, 结束! 🕛 17.71 秒


## 执行结束... 2024-11-30 16:22:51  耗时 19 秒

**Comment by Nepenlos** [comment]
> @Nepenlos 你不是最新版，更新

## 开始执行... 2024-11-30 16:23:10



🔔汪汪庄园合成, 开始!

====================共2个京东账号Cookie=================
===========脚本执行时间：2024/11/30 16:23:11============
>>>>>>>>>>>>6dylan6提醒您：有问题先更新不行在反馈>>>>>>>>>>>>>


当前版本：20241126
跑几次可能会黑，一周后解除
问题建议：https://t.me/dylan_jdpro

******开始【京东账号1】18725444412_p*********

"Response code 403 (Forbidden)"
getJoyBaseInfo API请求失败，请检查网路重试

******开始【京东账号2】jd_HRViVuQaqXTr*********

"Response code 403 (Forbidden)"
getJoyBaseInfo API请求失败，请检查网路重试

🔔汪汪庄园合成, 结束! 🕛 10.682 秒


## 执行结束... 2024-11-30 16:23:21  耗时 11 秒

**Comment by 6dylan6** [comment]
@Nepenlos 更新今天版本

**Comment by Nepenlos** [comment]
> @Nepenlos 更新今天版本

问题解决
