### ISSUE TITLE
新农场浇水几次后，报超时等待；后面几个号浇水几次也同样报错

### ISSUE THREAD

**Issue by violetfircats** [6dylan6/jdpro#628]
![1000142256](https://github.com/user-attachments/assets/1be76b97-fa61-4e4a-96df-0f5761809561)
问题图片如上

**Comment by 6dylan6** [comment]
@violetfircats 检查网络吧，网络不行肯定超时啦。

**Comment by violetfircats** [comment]
> @violetfircats 检查网络吧，网络不行肯定超时啦。

好的，谢谢！我检查一下
