### ISSUE TITLE
多合一自动签到_签到失败

### ISSUE THREAD

**Issue by BNDou** [6dylan6/jdpro#628]
6神好~
多合一的京豆签到最近报出签到人数较多，app上边手动签到是没问题的，麻烦请教下大佬这个情况如何解决哩😄
![image](https://user-images.githubusercontent.com/67632799/226120805-24c66233-d154-487d-8975-a17b07984976.png)

**Comment by 6dylan6** [comment]
@BNDou 手动在运行看看正常签吗

**Comment by magicnobob** [comment]
> 

手动也一样

**Comment by BNDou** [comment]
> @BNDou 手动在运行看看正常签吗

不行喔，而且我还换了时间段测试，一样都是签到人数较多

**Comment by 6dylan6** [comment]
@BNDou 手动进app正常签吗，其他号正常吗

**Comment by BNDou** [comment]
> @BNDou 手动进app正常签吗，其他号正常吗

手动签是正常的无异常，其他号也是相同的情况，只有现金签到可以成功

**Comment by linzhaokang-rgb** [comment]
我也是这个问题

**Comment by linzhaokang-rgb** [comment]
这个问题好像就前几天才开始有的

**Comment by 6dylan6** [comment]
@linzhaokang-rgb 我又传了个，试试新的正常吗

**Comment by BNDou** [comment]
> @linzhaokang-rgb 我又传了个，试试新的正常吗

这不会是限制ip了吧😂
```
{"code":"0","errorCode":"TI-100","errorMessage":"活动太火爆了,请稍后再试"}
DEBUG2:"{\"code\":\"0\",\"errorCode\":\"S100\",\"errorMessage\":\"当前签到人数较多，请稍晚再来\"}"
```

**Comment by 6dylan6** [comment]
@BNDou 有可能，换IP试试

**Comment by 6dylan6** [comment]
@BNDou 几个ck签，我这都正常呢

**Comment by 6dylan6** [comment]
@6dylan6 一般黑了才会这报错，app手动签看看有没有出现滑块，或者火爆

**Comment by BNDou** [comment]
> @6dylan6 一般黑了才会这报错，app手动签看看有没有出现滑块，或者火爆

没有，手机访问app是正常的，估计就是服务器的IP请求频繁限制了，撂他几天吧

**Comment by BNDou** [comment]
> > @6dylan6 一般黑了才会这报错，app手动签看看有没有出现滑块，或者火爆
> 
> 没有，手机访问app是正常的，我这8个ck都是这个情况，估计就是服务器的IP请求频繁限制了，撂他几天吧

**Comment by 6dylan6** [comment]
@BNDou app正常签？没有要滑块拼图？

**Comment by BNDou** [comment]
> @BNDou app正常签？没有要滑块拼图？

嗯呐，没有。而且我的环境在云服务器，经常抽风也正常😂

**Comment by 6dylan6** [comment]
@BNDou 汗，云环境那怪不得了，对云ip早就有限制了

**Comment by BNDou** [comment]
> @BNDou 汗，云环境那怪不得了，对云ip早就有限制了

它是怎么检测是云环境的😂

**Comment by 6dylan6** [comment]
@BNDou ip啊

**Comment by BNDou** [comment]
> @BNDou ip啊

😁明白了，多谢大佬哥

**Comment by linzhaokang-rgb** [comment]
哈哈一样的问题我也是云环境 谢谢大佬

**Comment by cy920820** [comment]
> @BNDou 汗，云环境那怪不得了，对云ip早就有限制了

我是腾讯云服务器，现在也是 app 手动签到没有影响，但是青龙上也报这个错误

**Comment by BNDou** [comment]
@cy920820 手机上可以用是因为你手机网络环境是家用ip，云服务器ip和家用ip不一样，现在都有屏蔽，所以就认了吧别折腾了😁要么就去搭个家用ip环境

**Comment by cy920820** [comment]
> 机网络环境是家用ip，云服务器ip和家用ip不一样，现在都有屏蔽，所以就认了吧别折腾了😁要么就去搭个家用ip环境

京东这风控太卷了吧
