### ISSUE TITLE
东东农场没法使用了

### ISSUE THREAD

**Issue by JILJEKLFI** [6dylan6/jdpro#63]
{"code":"404","message":"运行环境异常，请您从正规渠道参与活动，稍后再试哦"}
你好，报错如上

**Comment by doony15** [comment]
同，报错
初始化农场数据异常, 请登录京东 app查看农场0元水果功能是否正常,农场初始化数据: {"code":"404","message":"运行环境异常，请您从正规渠道参与活动，稍后再试哦"}

**Comment by nosferatu747** [comment]
应该是号被黑我兑换过的号同样报错，可手动参加活动，昨天新挂的账号就没事正常。

**Comment by JILJEKLFI** [comment]
可是404应该是接口没了，是不是农场换接口了

**Comment by ySirius** [comment]
锁IP了嘛，挂的八个号都不行了

**Comment by 6dylan6** [comment]
@ySirius 都更新到最新没有

**Comment by ySirius** [comment]
> @ySirius 都更新到最新没有

重新拉库了，还是不好用
