### ISSUE TITLE
3.1-3.31 SK2互动抽奖，至高赢经典神仙水異常

### ISSUE THREAD

**Issue by linzhaokang-rgb** [6dylan6/jdpro#630]
入口:
https://lzkjdz-isv.isvjcloud.com/m/1000009821/TaskDraw/?activityId=2303100000982116

******开始【京东账号1】jd_74b13ae44033f*********

🔁 当前使用内置Sign服务

activityContent 
获取不到[actorUuid]退出执行，请重新执行

🔔3.1-3.31 SK2互动抽奖，至高赢经典神仙水, 结束! 🕛 7.226 秒
大佬我想問下這種的是什麽問題？

**Comment by 6dylan6** [comment]
@linzhaokang-rgb 云服务器跑不动
