### ISSUE TITLE
小白咨询两个问题

### ISSUE THREAD

**Issue by intxzt** [6dylan6/jdpro#633]
首先感谢下作者，使用了半年多了，一直很稳定，极大的满足了羊毛党爱占小便宜的心思。
下边说问题：
一是：如果只用COOKIE，不使用CK，会有盗刷的风险吗？
二是：你的库里面有一些执行时间在下半年或者明年的默认不执行的脚步，是出于安全的考虑不建议执行吗？

**Comment by 6dylan6** [comment]
@intxzt 第一，cookie就是ck啊
第二，定时设置那样是不想自动跑的，比如开卡活动没水时候跑了浪费，有的可能跑会黑，有的涉及资产兑换，总之是自动跑没啥水的，如需自动跑脚本都有注释根据需求设置定时
