### ISSUE TITLE
视频浏览

### ISSUE THREAD

**Issue by Yeung168** [6dylan6/jdpro#635]
为什么这两天视频浏览每次只允许一分钟就结束了？

**Comment by Yeung168** [comment]
视频任务里面多了两个任务和邀请好友的任务，能加进去吗？

**Comment by 6dylan6** [comment]
@Yeung168 没看到哪里有

**Comment by Yeung168** [comment]
app要更新到最新版才会显示(不清楚是不是部分用户才有)，不过我刚刚测试了一下邀请好友那个很容易火爆感觉没什么必要了
