### ISSUE TITLE
东东农场任务（更新后解决）

### ISSUE THREAD

**Issue by smile20170826** [6dylan6/jdpro#64]
初始化农场数据异常, 请登录京东 app查看农场0元水果功能是否正常,农场初始化数据: {"code":"404","message":"运行环境异常，请您从正规渠道参与活动，稍后再试哦"}

**Comment by 6dylan6** [comment]
@smile20170826 更新试试

**Comment by medego** [comment]
请问时更新青龙面板还是更新仓库呢

**Comment by ySirius** [comment]
@medego  请问解决了嘛
