### ISSUE TITLE
老大，有没有京东到家果园的脚本？

### ISSUE THREAD

**Issue by lunati-wei** [6dylan6/jdpro#64]
京东到家果园信息

【jd_187295wvg】
一箱橙子,本次领取0滴水,浇水0次,还需浇水2次长大,还剩4017滴水

本通知 By 6dylan6
通知时间: 2022-02-25 11:18:23

**Comment by 6dylan6** [comment]
我的正常啊，你看看运行日志
![image](https://user-images.githubusercontent.com/86815944/155651502-e9840930-4572-436e-809d-b0a93a9f7428.png)
