### ISSUE TITLE
种豆得豆任务问题

### ISSUE THREAD

**Issue by lhdbxyq** [6dylan6/jdpro#640]
以前用青龙[v2.10.13]可以跑种豆得豆任务，现在升级新版青龙[v2.17.12]了，提示：此路拥堵中，前方不通
种豆得豆-初始失败:  {"code":"0","errorCode":"PB003","errorMessage":"此路拥堵中，前方不通"}。

然后我测试了下，有个白号，青龙[v2.17.12]是能跑的，不能跑的是有点黑的号，用青龙[v2.10.13]发现都可以跑。

**Comment by 6dylan6** [comment]
@lhdbxyq 和青龙版本没关系，你拉库更新

**Comment by lhdbxyq** [comment]
![360截图20241211083306052](https://github.com/user-attachments/assets/9196cded-9635-4895-9a96-1c044b992346)

一直这样，搞不明白。其他号确定是能跑的。
