### ISSUE TITLE
老农场问题

### ISSUE THREAD

**Issue by lhdbxyq** [6dylan6/jdpro#644]
东东农场-任务、东东农场-助力、东东农场-删好友奖励这三个脚本在最新版青龙[v2.17.12]运行有问题，表现为：

没有每日签到

初始化农场数据异常, 请登录京东 app查看农场0元水果功能是否正常,农场初始化数据: {"code":"402","message":"运行环境异常，请您从正规渠道参与活动，稍后再试"}

老版本青龙[v2.10.13]可以正常运行。

**Comment by 6dylan6** [comment]
@lhdbxyq 更新试试吧

**Comment by lhdbxyq** [comment]
@6dylan6 重新拉了，新版的青龙还是没跑起来，就一个账号跑。跟昨天种豆的情况一样，种豆是修好了的。


初始化农场数据异常, 请登录京东 app查看农场0元水果功能是否正常,农场初始化数据: {"code":"402","message":"运行环境异常，请您从正规渠道参与活动，稍后再试"}

![image](https://github.com/user-attachments/assets/377e1e9d-c736-4c32-aa94-22d363958af6)

**Comment by lhdbxyq** [comment]
东东农场-任务正常了，助力和删好友报错。

**Comment by 6dylan6** [comment]
@lhdbxyq 更新，新农场正常吗

**Comment by lhdbxyq** [comment]
@6dylan6 现在都正常了。新农场任务里的浇水是正常的，单独的那个浇水我没启用。
