### ISSUE TITLE
口令转链接报错

### ISSUE THREAD

**Issue by jingbohi** [6dylan6/jdpro#651]
口令转链接提示错误，口令检查无误，无法转换，上个月使用正常。
## 开始执行... 2024-12-16 14:47:11

执行前置命令

执行前置命令结束

🔔口令转链接, 开始!

❗️口令转链接, 错误!

🔔口令转链接, 结束! 🕛 1.249 秒

## 执行结束... 2024-12-16 14:47:16  耗时 5 秒

**Comment by jingbohi** [comment]
## 开始执行... 2024-12-16 14:47:11

执行前置命令


执行前置命令结束


🔔口令转链接, 开始!

❗️口令转链接, 错误!


🔔口令转链接, 结束! 🕛 1.249 秒


## 执行结束... 2024-12-16 14:47:16  耗时 5 秒

**Comment by 6dylan6** [comment]
@jingbohi 更新

**Comment by jingbohi** [comment]
@6dylan6 感谢大佬！
