### ISSUE TITLE
浏览器获取登陆失败

### ISSUE THREAD

**Issue by linzhaokang-rgb** [6dylan6/jdpro#658]
<img width="152" alt="1681091831713" src="https://user-images.githubusercontent.com/59006891/230810540-40d1daad-9dfd-4726-9b1e-97ac2780fe13.png">
大家有遇到过这个问题吗？

**Comment by 6dylan6** [comment]
@linzhaokang-rgb 账号风控了，安卓可以用alook浏览器正常获取

**Comment by linzhaokang-rgb** [comment]
试过了还是提示的这个 呜呜

**Comment by 6dylan6** [comment]
@linzhaokang-rgb 那改密码吧

**Comment by linzhaokang-rgb** [comment]
感谢大佬修改了下密码可以了
