### ISSUE TITLE
种豆得豆里的东东农场任务没办法完成

### ISSUE THREAD

**Issue by 2604237845** [6dylan6/jdpro#66]
开始【京东账号1】wdRtCOEPXEwaTm

获取任务及基本信息

【京东账号1（wdRtCOEPXEwaTm）的种豆得豆好友互助码】pg4fihv4obetrh5q2me536lwa35gsj43wqxzpqa

开始做 金融双签任务
做 金融双签任务结果:{"code":"0","data":{"nutrState":"1","nutrNum":1,"nutrToast":"恭喜你获得营养液，快去培养小小豆吧"}}

开始做 东东农场任务
做 东东农场任务结果:{"code":"0","data":{"nutrState":"1","nutrNum":1,"nutrToast":"恭喜你获得营养液，快去培养小小豆吧"}}
......
......
......
     任务   进度
[免费水果]  0/10   0
[金融双签]  1/1   1
[东东农场]  1/1   1
[好友助力]  20/20   1
[关注频道]  3/3   1
[浏览店铺]  4/4   1
[挑选商品]  6/6   1
[每日签到]  1/1   1

上面显示虽然完成了，下面任务进度实际并没有完成，手动进去查看也是未完成状态

**Comment by 2604237845** [comment]
@6dylan6 大佬种豆得豆里有个农场的任务没办法完成😂

**Comment by goodwenhao** [comment]
> @6dylan6 大佬种豆得豆里有个农场的任务没办法完成😂


更新
