### ISSUE TITLE
更新后缺少tough-cookie

### ISSUE THREAD

**Issue by winsphinx** [6dylan6/jdpro#661]
貌似多个脚本都调用这个模块：
node:internal/modules/cjs/loader:1249
  const err = new Error(message);
              ^

Error: Cannot find module 'tough-cookie'
Require stack:
- /ql/data/scripts/6dylan6_jdpro/jd_signbeanact_.js

**Comment by wwqwq2313** [comment]
Hello, we tried to solve the issue.

This is what we did:

Add tough-cookie as a dependency in package.json and ensure it's installed. Also update the jd_signbeanact_.js file to properly require the module.

You can review changes in this commit: https://github.com/wwqwq2313/6dylan6-jdpro-661/commit/be65cf1ac3694aaa9e5267669b0c72d1780a2a94.


> [!CAUTION]
> Disclaimer: The concept of solution was created by AI and you should never copy paste this code before you check the correctness of generated code. Solution might not be complete, you should use this code as an inspiration only.

---

Latta AI seeks to solve problems in open source projects as part of its mission to support developers around the world. Learn more about our mission at https://latta.ai/ourmission . If you no longer want Latta AI to attempt solving issues on your repository, you can block this account.

**Comment by 6dylan6** [comment]
@wwqwq2313 青龙坏了吧不需要这依赖

**Comment by plsy1** [comment]
遇到同样的问题，试着重新部署了下没有解决:(

**Comment by 6dylan6** [comment]
@plsy1 那自己安装tough-cookie依赖，这个模块青龙正常是自带的

**Comment by mimimiaomiao1** [comment]
> [@plsy1](https://github.com/plsy1) 那自己安装tough-cookie依赖，这个模块青龙正常是自带的

请问怎么装这个依赖。

**Comment by 6dylan6** [comment]
@mimimiaomiao1 依赖管理创建，怎么会缺这个依赖，青龙自带的啊

**Comment by plsy1** [comment]
> > [@plsy1](https://github.com/plsy1) 那自己安装tough-cookie依赖，这个模块青龙正常是自带的
> 
> 请问怎么装这个依赖。

是不是开了adguardhome之类的，关了试试

**Comment by mimimiaomiao1** [comment]
> [@mimimiaomiao1](https://github.com/mimimiaomiao1) 依赖管理创建，怎么会缺这个依赖，青龙自带的啊

谢谢大佬，我前两天不知道咋搞的出错了，然后卸载了青龙，在安装青龙忘记 依赖模块安装这个事了。昨儿执行了一下，就安装了。
