### ISSUE TITLE
大佬年货节今天会出吗？

### ISSUE THREAD

**Issue by velonic5438** [6dylan6/jdpro#665]

**Comment by zhoulinshi** [comment]
已经出了，但是「获取url1失败」报这个提示，，怎么解决啊

**Comment by 6dylan6** [comment]
@zhoulinshi 你访问你的链接看看能刀领红包页面吗

**Comment by zhoulinshi** [comment]
> @zhoulinshi 你访问你的链接看看能刀领红包页面吗

@6dylan6 我将链接分享给他人以后，我自己和他人，都可以正常打开页面并且领取红包～

**Comment by 6dylan6** [comment]
@zhoulinshi 发来连接我测下

**Comment by zhoulinshi** [comment]
> @zhoulinshi 发来连接我测下

@6dylan6 好的大佬，是这个：
https://u.jd.com/sGHwQxI

**Comment by 6dylan6** [comment]
@zhoulinshi 我这侧正常，你所有ck都获取失败吗

**Comment by zhoulinshi** [comment]
@6dylan6 是的，我有两个CK，都提示「获取url1失败」，如果不好解决就算啦。😂

**Comment by 6dylan6** [comment]
@zhoulinshi 你变量设置的是最后7位字母吗

**Comment by zhoulinshi** [comment]
@6dylan6 解决了。原来是变量设置错了。😂。谢谢大佬
