### ISSUE TITLE
请问下如何正确禁用某些任务？

### ISSUE THREAD

**Issue by zhoulinshi** [6dylan6/jdpro#667]
目前的做法是，把一些不用的任务删掉，只需要执行一些基础的任务

但是更新拉库的时候会全部拉一遍，删除的任务又出现了

我看REDEME里面有一个task_before.sh，请问作者大佬，是通过在这里中注释掉不需要执行的任务吗？

**Comment by 6dylan6** [comment]
@zhoulinshi 不需要的直接禁用，不要删

**Comment by zhoulinshi** [comment]
> @zhoulinshi 不需要的直接禁用，不要删

好的，感谢～
