### ISSUE TITLE
种豆任务执行报错

### ISSUE THREAD

**Issue by besty99** [6dylan6/jdpro#669]
报错信息：

undefined
种豆得豆-初始失败:  {"code":"3"}

上周开始，所有账号都报错，已检查ck正常，其余任务可以运行 青龙版本正式版 v2.17.13

**Comment by 6dylan6** [comment]
@besty99 开始账号有显示账户名 吗，种豆全部ck都这样？

**Comment by besty99** [comment]
不好意思，仔细看了日志发现有提示，是ck中少了一个分号，问题已解决 @6dylan6
