### ISSUE TITLE
邮箱经常收到 京东已接收你的订单邮件，但是去查看订单里没有，有风险吗？

### ISSUE THREAD

**Issue by sunxiaozhi** [6dylan6/jdpro#673]
邮箱经常收到 京东已接收你的订单邮件，但是去查看订单里没有，有风险吗？

**Comment by 6dylan6** [comment]
@sunxiaozhi 心真大，被偷了还不知道呢，你用金融看账单能看到，电脑版回收站能看到被删的订单，赶紧改密码

**Comment by sunxiaozhi** [comment]
问题是 金融账单和被删订单都没有记录

**Comment by 6dylan6** [comment]
@sunxiaozhi 那就没有被偷，不知道了，收件地址有没有清空或者有其他莫名地址

**Comment by sunxiaozhi** [comment]
> @sunxiaozhi 那就没有被偷，不知道了，收件地址有没有清空或者有其他莫名地址

这个倒也没有，我就是挺奇怪的

**Comment by 6dylan6** [comment]
@sunxiaozhi 那也许谁的号绑定到你邮箱了

**Comment by sunxiaozhi** [comment]
> @sunxiaozhi 那也许谁的号绑定到你邮箱了

是之前的手机号绑定的邮箱，问题是这个号之前注销了 那应该和脚本没关系

**Comment by sunxiaozhi** [comment]
是之前的手机号绑定的邮箱，问题是这个号之前注销了 那应该和脚本没关系

**Comment by 6dylan6** [comment]
@sunxiaozhi 汗，和我库没关系，啥破事首先锤库，老背锅侠了，被偷的殊不知用了啥乱七八糟的东西！
