### ISSUE TITLE
获取不到互助码

### ISSUE THREAD

**Issue by ztoofar** [6dylan6/jdpro#678]
![image](https://user-images.githubusercontent.com/45729738/234321901-87ccfe73-0126-48a1-baca-c071d9b2e642.png)
![image](https://user-images.githubusercontent.com/45729738/234322096-134fdf3d-2236-421f-80a4-3f2783ebd1ab.png)
农场日志有互助码,但是获取不到

**Comment by 6dylan6** [comment]
@ztoofar 更新再试试

**Comment by ztoofar** [comment]
> @ztoofar 更新再试试

还是不行啊，我重新跑了一遍拉库任务。还是你说的更新是要怎么操作？

**Comment by 6dylan6** [comment]
@ztoofar 拉库，在运行获取互助码，什么版本青龙

**Comment by ztoofar** [comment]
> @ztoofar 拉库，在运行获取互助码，什么版本青龙

版本2.15.12，镜像是debian版的

**Comment by 6dylan6** [comment]
@ztoofar ？怎么会有debian的镜像。那估计有些命令不支持

**Comment by ztoofar** [comment]
![Screenshot_2023-04-26-10-39-43-799_org telegram messenger](https://user-images.githubusercontent.com/45729738/234453542-41f2f8c7-5c7b-4a13-8a3e-3c24f817a08e.jpg)
就这个，有计划支持吗

**Comment by ztoofar** [comment]
> @ztoofar ？怎么会有debian的镜像。那估计有些命令不支持

![IMG_20230426_104828](https://user-images.githubusercontent.com/45729738/234454044-f6ca9f73-80fc-48ab-9775-ffa18f3751da.jpg)
就这个，有计划支持吗

**Comment by 6dylan6** [comment]
@ztoofar 不支持，用普通版

**Comment by ztoofar** [comment]
> @ztoofar ？怎么会有debian的镜像。那估计有些命令不支持
