### ISSUE TITLE
京东牧场的助力失效了。

### ISSUE THREAD

**Issue by shaufo** [6dylan6/jdpro#68]
这是23号的记录
![01](https://github.com/6dylan6/jdpro/assets/63514384/8ef9b797-51b6-49e3-aebe-0d5d56a32952)
这是24号的记录
![02](https://github.com/6dylan6/jdpro/assets/63514384/b6738806-bccd-4f1d-aa0e-4bd625ff2c97)
这是25号的记录
![03](https://github.com/6dylan6/jdpro/assets/63514384/33fe3c3f-7e1f-4b39-b75f-75e2c75522b2)

**Comment by shaufo** [comment]
23号是正常的。昨天提示数据异常，今天就直接没有助力了。不是一个号出现问题，是在助力池里面的所有号都没有助力了。

**Comment by 6dylan6** [comment]
@shaufo 更新

**Comment by shaufo** [comment]
请问是更新青龙面板，还是拉库的命令？

**Comment by 6dylan6** [comment]
@shaufo 拉库

**Comment by shaufo** [comment]
好的，我这边试试，明天再反馈结果。

**Comment by shaufo** [comment]
已经恢复正常了
