### ISSUE TITLE
关于洗豆

### ISSUE THREAD

**Issue by winsphinx** [6dylan6/jdpro#686]
洗临期豆子时，是先将京豆转换为积分, 再将积分换回京豆, 但由于此时比如说被分完了, 这个积分就换不回来了。
建议不管京豆是否转过去, 后直接尝试积分转回。而不是京豆成功后再转积分。

**Comment by 6dylan6** [comment]
@winsphinx 你多久么更新了，早就分开两个了，一个换积分一个换豆

**Comment by winsphinx** [comment]
换豆的washbean
换积分是哪个？

**Comment by 6dylan6** [comment]
@winsphinx 搜换豆
