### ISSUE TITLE
关于京东农场的问题

### ISSUE THREAD

**Issue by benitoxu** [6dylan6/jdpro#69]
您好，谢谢您提供的脚本和劳动。
是这样子的，因为我一直有保存京东农场水滴等一次性浇水的习惯换大额红包的习惯，所以我每次都尝试着自己修改脚本，把持续浇水的部分删除，但是25号的时候，我发现农场出现问题，所以就更新了农场任务，更新完，我就不知道怎么办了，我修改脚本的持续浇水变量为false，但是不起作用，请问能教我一下如何修改，或者能提供一份删除完持续浇水的脚本吗？谢谢您

**Comment by 6dylan6** [comment]
@benitoxu export DO_TEN_WATER_AGAIN='true' 写到配置文件里

**Comment by benitoxu** [comment]
我明白了，原来在config.js这里可以添加各种配置，不好意思，打扰您，谢谢您的时间和帮助

**Comment by benitoxu** [comment]
> @benitoxu export DO_TEN_WATER_AGAIN='true' 写到配置文件里

我明白了，原来在config.js这里可以添加各种配置，不好意思，打扰您，谢谢您的时间和帮助

**Comment by somertang** [comment]
@6dylan6 您好，最近更新了东东农场的脚本，不管我有没有在config文件里面配置变量，它都每天浇了10次水后就不再浇水了，我不想攒水滴，请问有什么办法解决吗

**Comment by goodwenhao** [comment]
@somertang 还是变量存在，青龙bug，你删除了之前设置的变量不生效，需要重启

**Comment by somertang** [comment]
@goodwenhao 我这边变量已经生效了，但还是每天浇10次水后，就不浇水了，我在脚本里面打印了DO_TEN_WATER_AGAIN变量

$.msg(process.env.DO_TEN_WATER_AGAIN, 'DO_TEN_WATER_AGAIN');

==============📣系统通知📣==============
false
DO_TEN_WATER_AGAIN
开始获取配置文件

加载sendNotify，当前版本: 20230506V2

**Comment by 6dylan6** [comment]
@somertang 重启了吗

**Comment by somertang** [comment]
> @somertang 重启了吗

重启过了的

**Comment by 6dylan6** [comment]
![image](https://github.com/6dylan6/jdpro/assets/86815944/81712fdb-b0aa-470e-96a8-c83e67b82263)
你看看日志有没有提示

**Comment by somertang** [comment]
> ![image](https://user-images.githubusercontent.com/86815944/263528855-81712fdb-b0aa-470e-96a8-c83e67b82263.png) 你看看日志有没有提示

没有
<img width="529" alt="image" src="https://github.com/6dylan6/jdpro/assets/30136420/377fc932-be63-47a3-be3f-5b0763d8fedd">

**Comment by somertang** [comment]
> ![image](https://user-images.githubusercontent.com/86815944/263528855-81712fdb-b0aa-470e-96a8-c83e67b82263.png) 你看看日志有没有提示

<img width="363" alt="image" src="https://github.com/6dylan6/jdpro/assets/30136420/4bd624ed-b53b-49c2-a8cd-015f91cf5f8d">

**Comment by 6dylan6** [comment]
@somertang 所以啊，你的变量还在，仔细检查下吧。

**Comment by somertang** [comment]
> @somertang 所以啊，你的变量还在，仔细检查下吧。

好的，我检查一下，谢谢

**Comment by ySirius** [comment]
你们的农场任务没有异常嘛

**Comment by Lshen9** [comment]
有，提示运行环境异常

**Comment by 6dylan6** [comment]
@Lshen9 全部还是部分

**Comment by ysf37** [comment]
@benitoxu 请问下这个水滴可以一次攒多少哇，6000滴种一个2级是12块无门槛，理论上可以一次攒多少呢

**Comment by 6dylan6** [comment]
@ysf37 2次吧

**Comment by Lshen9** [comment]
@6dylan6 更新之后没有问题了
