### ISSUE TITLE
wskey 一直报错 ”云端地址全部失效, 请检查网络!“

### ISSUE THREAD

**Issue by winsphinx** [6dylan6/jdpro#691]
![image](https://user-images.githubusercontent.com/5674054/236384260-2f2651f2-b11b-4b62-b094-07946fd87f3b.png)

今天一直报这个错，但从源代码看了看第三个地址是可以的，不知其他人是不是也是这样。

**Comment by sydaint** [comment]
我也是这个问题，还没时间弄，怎么处理的

**Comment by wang25669** [comment]
一样问题

**Comment by otherbanana** [comment]
一样的问题

**Comment by 6dylan6** [comment]
@otherbanana 明天恢复

**Comment by echo094** [comment]
@6dylan6 [qitoqito/kedaya](https://github.com/qitoqito/kedaya)这仓库里有个本地的genToken参数生成方法，涉及到两个文件：
* parse/jd/jd_task_wskey.js 任务文件
* util/jdUrl.js 参数生成文件（加密，但等于没加）

可以考虑在远程服务不可用时回落到本地版，只要添加个接口js在python调用命令行执行并读取输出就行。

**Comment by 6dylan6** [comment]
@echo094 本地版好整，暂时么必要，这情况也出现不了几回

**Comment by loosink** [comment]
同样这个问题

**Comment by echo094** [comment]
@loosink 这个转换是Zy143L的，他在换服务器，可以看他原项目发的帖子：Zy143L/wskey#271

**Comment by 6dylan6** [comment]
@echo094 添加了个备用接口，再试试吧
