### ISSUE TITLE
种豆得豆，只第1个账号获取PLANT_BEAN_SHARECODES配置

### ISSUE THREAD

**Issue by linbailo** [6dylan6/jdpro#692]
种豆得豆，第1个账号能正常助力给出去的助力码
但是后面的助力都不获取PLANT_BEAN_SHARECODES里面的助力码配置了，只能获取到作者给的json文件里面的助力码

**Comment by linbailo** [comment]
农厂的助力倒是正常

**Comment by 6dylan6** [comment]
@linbailo 上日志看看
