### ISSUE TITLE
老大，农场助力失效了

### ISSUE THREAD

**Issue by Javebean** [6dylan6/jdpro#71]
农场助力失效了

**Comment by 6dylan6** [comment]
@Javebean 更新呀

**Comment by Javebean** [comment]
我去，体验了一下被秒回的快乐 ！ 我又检查了一下，确实更新了呀

**Comment by 6dylan6** [comment]
@Javebean 运行日志截图看看

**Comment by Javebean** [comment]
## 开始执行... 2023-08-27 11:43:52


🔔东东农场-助力, 开始!
开始获取配置文件...


====================共8个京东账号Cookie=================

============脚本执行时间：2023/08/27 11:44:02=============

>>>>>>>>>>>>>>6Dylan6 提示：任务正常运行中>>>>>>>>>>>>>>>

使用本地缓存的助力码


开始【京东账号1】1178080609_m

您提供了1个农场助力码

将要助力的好友["537919b7c900407ba6e000f26a1c2bd4"]

开始助力好友...
去助力: 537919b7c900407ba6e000f26a1c2bd4
【助力结果】: 已经助力过TA了
【助力次数还剩】2次

助力好友结束，即将开始领取额外水滴奖励


今日已邀请好友0个 / 每日邀请上限4个
接收邀请成为好友结果失败,对方已是您的好友
今日未邀请过好友

开始天天抽奖助力...

等待10秒......

不要重复助力辉LOVE林


==============📣系统通知📣==============
东东农场-助力
【京东账号1🆔】1178080609_m
【今日剩余助力👬】2次


开始【京东账号2】jd_JSwOngbVqJvL

您提供了1个农场助力码

将要助力的好友["537919b7c900407ba6e000f26a1c2bd4"]

开始助力好友...
去助力: 537919b7c900407ba6e000f26a1c2bd4
【助力结果】: 已经助力过TA了
【助力次数还剩】2次

助力好友结束，即将开始领取额外水滴奖励


今日已邀请好友0个 / 每日邀请上限4个
接收邀请成为好友结果失败,对方已是您的好友
今日未邀请过好友

开始天天抽奖助力...

等待10秒......

不要重复助力辉LOVE林


==============📣系统通知📣==============
东东农场-助力
【京东账号2🆔】jd_JSwOngbVqJvL
【今日剩余助力👬】2次


开始【京东账号3】jd_625e3281b31ca

您提供了1个农场助力码

将要助力的好友["537919b7c900407ba6e000f26a1c2bd4"]

开始助力好友...
去助力: 537919b7c900407ba6e000f26a1c2bd4
【助力结果】: 已经助力过TA了
【助力次数还剩】2次

助力好友结束，即将开始领取额外水滴奖励


今日已邀请好友0个 / 每日邀请上限4个
接收邀请成为好友结果失败,对方已是您的好友
今日未邀请过好友

开始天天抽奖助力...

等待10秒......

不要重复助力辉LOVE林


==============📣系统通知📣==============
东东农场-助力
【京东账号3🆔】jd_625e3281b31ca
【今日剩余助力👬】2次


开始【京东账号4】jd_4d2a4a1043fd6

您提供了1个农场助力码

将要助力的好友["537919b7c900407ba6e000f26a1c2bd4"]

开始助力好友...
去助力: 537919b7c900407ba6e000f26a1c2bd4
【助力结果】: 已经助力过TA了
【助力次数还剩】2次

助力好友结束，即将开始领取额外水滴奖励


今日已邀请好友0个 / 每日邀请上限4个
接收邀请成为好友结果失败,对方已是您的好友
今日未邀请过好友

开始天天抽奖助力...

等待10秒......

不要重复助力辉LOVE林


==============📣系统通知📣==============
东东农场-助力
【京东账号4🆔】jd_4d2a4a1043fd6
【今日剩余助力👬】2次


开始【京东账号5】jd_BCOTMkLCiRjV

您提供了1个农场助力码

将要助力的好友["537919b7c900407ba6e000f26a1c2bd4"]

开始助力好友...
去助力: 537919b7c900407ba6e000f26a1c2bd4
【助力结果】: 已经助力过TA了
【助力次数还剩】2次

助力好友结束，即将开始领取额外水滴奖励


今日已邀请好友0个 / 每日邀请上限4个
接收邀请成为好友结果失败,对方已是您的好友
今日未邀请过好友

开始天天抽奖助力...

等待10秒......

不要重复助力辉LOVE林


==============📣系统通知📣==============
东东农场-助力
【京东账号5🆔】jd_BCOTMkLCiRjV
【今日剩余助力👬】2次


开始【京东账号6】jd_6cc96411fe998

您提供了1个农场助力码

将要助力的好友["537919b7c900407ba6e000f26a1c2bd4"]

开始助力好友...
去助力: 537919b7c900407ba6e000f26a1c2bd4
【助力结果】: 已经助力过TA了
【助力次数还剩】2次

助力好友结束，即将开始领取额外水滴奖励


今日已邀请好友0个 / 每日邀请上限4个
接收邀请成为好友结果失败,对方已是您的好友
今日未邀请过好友

开始天天抽奖助力...

等待10秒......

不要重复助力辉LOVE林


==============📣系统通知📣==============
东东农场-助力
【京东账号6🆔】jd_6cc96411fe998
【今日剩余助力👬】2次


开始【京东账号7】jd_UdFBUuRwgSZz

您提供了1个农场助力码

将要助力的好友["537919b7c900407ba6e000f26a1c2bd4"]

开始助力好友...
去助力: 537919b7c900407ba6e000f26a1c2bd4
【助力结果】: 已经助力过TA了
【助力次数还剩】2次

助力好友结束，即将开始领取额外水滴奖励


今日已邀请好友0个 / 每日邀请上限4个
接收邀请成为好友结果失败,对方已是您的好友
今日未邀请过好友

开始天天抽奖助力...

等待10秒......

不要重复助力辉LOVE林


==============📣系统通知📣==============
东东农场-助力
【京东账号7🆔】jd_UdFBUuRwgSZz
【今日剩余助力👬】2次


开始【京东账号8】wdfsDgQuBuEEce

您提供了1个农场助力码

将要助力的好友["537919b7c900407ba6e000f26a1c2bd4"]

开始助力好友...
去助力: 537919b7c900407ba6e000f26a1c2bd4
不能为自己助力哦，跳过

助力好友结束，即将开始领取额外水滴奖励


今日已邀请好友0个 / 每日邀请上限4个
自己不能邀请自己成为好友噢

今日未邀请过好友

开始天天抽奖助力...
跳过自己


==============📣系统通知📣==============
东东农场-助力
【京东账号8🆔】wdfsDgQuBuEEce
【今日剩余助力👬】3次


🔔东东农场-助力, 结束! 🕛 162.816 秒


## 执行结束... 2023-08-27 11:46:36 耗时 164 秒

**Comment by Javebean** [comment]
但是实际没有助力成功。。

**Comment by 6dylan6** [comment]
@Javebean 不可能的。你进去看看

**Comment by Javebean** [comment]
确实没有。。。我可能号黑了。。

**Comment by 6dylan6** [comment]
@Javebean 成功了不可能没有的，要么就是助力错号了

**Comment by Javebean** [comment]
老大你看日志，执行了几次之后，每个号竟然还有剩余次数，这不就说明他没有助力成功了么

**Comment by 6dylan6** [comment]
@Javebean 你没看到助力码就一个，剩余次数助力给谁呢

**Comment by Javebean** [comment]
还真是，但是奇怪。。那个环境变量我一直没变过，FRUITSHARECODES 多个助力码用@分隔，难道是规则改了么

**Comment by 6dylan6** [comment]
@Javebean 你是不跑任务只跑助力的吗，跑完任务自动搜集助力码

**Comment by Javebean** [comment]
任务也跑的，很奇怪 ，我再检查下，解决了我会更新这个issue

**Comment by Javebean** [comment]
难道是我农场用了 conc JD_COOKIE，导致收集助力码顺序有误？
因为我发现，助力日志中那一个助力码，是最后一个jdcookie，而以前都是助力前三个的。。

**Comment by 6dylan6** [comment]
@Javebean 你并发跑的呀，那只能收到一个助力码。你还是用变量吧，我把变量加上

**Comment by Javebean** [comment]
哈哈，之前一直是串行跑，但是太慢了。我老早就改成了并发了，那现在问题应该清楚了，是并发的问题。💕

**Comment by 6dylan6** [comment]
@Javebean 几个号并发，都能正常跑？不黑ip吗

**Comment by Javebean** [comment]
8个号，不然我也不会选择并发了，

**Comment by Javebean** [comment]
ip暂时还没黑。也可能是我运气好，但是jdplus分，掉到20多分，我感觉离黑不远了

**Comment by Javebean** [comment]
更新了脚本，显示使用变量了。感谢
![image](https://github.com/6dylan6/jdpro/assets/10663914/6fcfea71-ebaf-4150-b31a-8363191a7b95)

**Comment by Smithcaige** [comment]
这个能不是好友的自动添加好友吗，如果可以的话应该如何操作呢，求教
