### ISSUE TITLE
最新版版本的关于农场的jd_sharecode.sh获取互助码，农场互助脚本不能助力第一个账号

### ISSUE THREAD

**Issue by lsq211** [6dylan6/jdpro#72]
1、格式化代码的时候可以获取到
![image](https://github.com/6dylan6/jdpro/assets/135681573/f9031471-df09-47fd-8541-b3c3f5e965a2)
2、助力的时候后面的号都不会助力的
![image](https://github.com/6dylan6/jdpro/assets/135681573/7e19ca88-53f1-4189-823d-5c03ebe5fa9c)

**Comment by lsq211** [comment]
2、助力的时候后面的号，不会再助力第一个号的助力吗
![image](https://github.com/6dylan6/jdpro/assets/135681573/31b9b7bf-602d-45b2-8a4f-d0333d86bebb)

**Comment by 6dylan6** [comment]
@lsq211 获取互助码没用了删了，是从农场任务读取助力码进行助力

**Comment by lsq211** [comment]
就是只能设置助力码，设置的话就只能读取你的助力码吧？感觉还是 jd_sharecode.sh这个好用

**Comment by lsq211** [comment]
就是只能设置助力码，没设置的话就只能读取你的助力码吧？感觉还是 jd_sharecode.sh这个好用

**Comment by 6dylan6** [comment]
@lsq211 不设置就自动从你运行农场任务里的日志获取互助码啊。和sharecode基本一样

**Comment by lsq211** [comment]
好的，谢谢。怎么删除之前使用jd_sharecode.sh设置互助码的

**Comment by 6dylan6** [comment]
@lsq211 日志管理里面删除.ShareCode目录

**Comment by wavetg** [comment]
> @lsq211 不设置就自动从你运行农场任务里的日志获取互助码啊。和sharecode基本一样

还是不能读到第一个账号的助力码，明明日志里有，就是读不到，少一个码

**Comment by 6dylan6** [comment]
@wavetg 你删掉日志下的.ShareCode目录了吗，不删还是从这读取

**Comment by wavetg** [comment]
@6dylan6 刚刚删除了，可以了十分感谢。从sharecode目录读取会少一个，既然要转变助力码获取方式，为什么不直接去掉从sharecode读取的逻辑？code.sh长期无人维护，看来要翻篇了。。

**Comment by ChenDudo** [comment]
删了sharecode，怎么第一个账户还是没有获得助力呢

**Comment by 6dylan6** [comment]
@ChenDudo 你看看运行日志，第一个助力code是哪个呀

**Comment by ChenDudo** [comment]
看了 jd_farm_help.js 的日志，第一个账号的互助列表是助力账号 2\3\4，后面的账号都会采用这个互助列表，导致2、3、4的助力满了，而账号1没有获得任何助力

**Comment by 6dylan6** [comment]
@ChenDudo 你运行新上传的任务 删除旧的助力码目录再试试

**Comment by ChenDudo** [comment]
@6dylan6 我是新的任务，助力码目录也清空了。应该是 jd_farm_help.js 脚本问题。我现在通过配置账户1的互助列表包含账号1的方式进行

**Comment by 6dylan6** [comment]
@ChenDudo 脚本测试了正常的，你清空配置管理task_before里的内容试试

**Comment by besty99** [comment]
删除助力码目录后可以了，感谢大佬
