### ISSUE TITLE
东东农场助力失败  cookiesArr is not defined

### ISSUE THREAD

**Issue by ysf37** [6dylan6/jdpro#74]
![微信图片_20230830101254](https://github.com/6dylan6/jdpro/assets/19886505/cb7b6568-0a45-4bb0-94d1-b1196872a67c)

**Comment by ysf37** [comment]
昨天都还行，今天照常拉库后运行就这样了，好像也没更新啥，大佬有时间帮忙看看

**Comment by 6dylan6** [comment]
@ysf37 更新下

**Comment by ysf37** [comment]
更新就好了，感谢大佬
&nbsp;


该邮件从移动设备发送


&nbsp;




------------------&nbsp;原始邮件&nbsp;------------------
发件人: ***@***.***&gt;; 
发送时间: 2023年8月30日(星期三) 上午10:19
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; ***@***.***&gt;; 
主题: Re: [6dylan6/jdpro] 东东农场助力失败  cookiesArr is not defined (Issue #74)





 
@ysf37 更新下

**Comment by pjcoding** [comment]
> 更新

更新还是报错

**Comment by 6dylan6** [comment]
@pjcoding 在更新
