### ISSUE TITLE
自动评价缺少jieba

### ISSUE THREAD

**Issue by tangdasan** [6dylan6/jdpro#75]
xxxxxxxxxxxx
No module named 'jieba' 
缺少jieba 模块，请执行命令安装：pip3 install jieba

在机器上已经运行
`root@instance-rt00ad62:~# pip3 install jieba
Requirement already satisfied: jieba in /usr/local/lib/python3.8/dist-packages (0.42.1)`

另外有公用互助库吗？

**Comment by 6dylan6** [comment]
是在青龙里装的么。没有互助池

**Comment by tangdasan** [comment]
> 是在青龙里装的么。没有互助池

哦，是要进容器里装，我在系统装的
