### ISSUE TITLE
农场自动种植兑换 ，提示： '活动参与异常，请通过正规渠道参与活动获得奖励哦'

### ISSUE THREAD

**Issue by lsq211** [6dylan6/jdpro#75]
![image](https://github.com/6dylan6/jdpro/assets/135681573/d78620d1-cdaa-4064-b056-593531e2c11a)

**Comment by 6dylan6** [comment]
@lsq211 更新

**Comment by ySirius** [comment]
@6dylan6 是更新库嘛？重新拉了也不行....

**Comment by 6dylan6** [comment]
@ySirius 截图日志

**Comment by ySirius** [comment]
@6dylan6 
![image](https://github.com/6dylan6/jdpro/assets/24601858/01feb9ee-aa22-42ed-869b-6d0a81c4b2a3)

**Comment by 6dylan6** [comment]
@ySirius 这是农场任务啊，你没有更新成功吧，运行修复，在更新试试

**Comment by ySirius** [comment]
@6dylan6 好的我搞一下，确实没更新成功

**Comment by ySirius** [comment]
@6dylan6 感谢 解决了。 不知道从哪个更新开始，拉库版本就一直不更新了。 全删了重新拉了一遍 解决了

**Comment by 6dylan6** [comment]
@ySirius 青龙bug
