### ISSUE TITLE
点点券抢红包失效了啊，大大帮忙修复吧

### ISSUE THREAD

**Issue by hello200xxx** [6dylan6/jdpro#76]

**Comment by hello200xxx** [comment]
以前有，在您的backup目录下面，[backUp/jd_necklace.js](https://github.com/6dylan6/jdpro/blob/82bec7201d2b8795b6887b93e15f99f7942500bc/backUp/jd_necklace.js)

**Comment by hello200xxx** [comment]
还有这个，都是常用的，希望大大修复
https://github.com/6dylan6/jdpro/blob/fa904b5bee28538937fcbb5b37422d626360b6e4/backUp/jd_redPacket.js

**Comment by 6dylan6** [comment]
目前全网还没有大佬修啊
