### ISSUE TITLE
东东农场-助力，能不能优化下和之前一样，当前助力码满了直接去除，不然最后的号还是从第一个助力码开始助力

### ISSUE THREAD

**Issue by lsq211** [6dylan6/jdpro#77]
农场助力逻辑优化
![image](https://github.com/6dylan6/jdpro/assets/135681573/853466fc-330e-4240-8862-e71fa8b2eadb)

**Comment by 6dylan6** [comment]
@lsq211 是这逻辑啊。我检查看看

**Comment by lsq211** [comment]
拉库好了
