### ISSUE TITLE
东东农场-助力，能不能新增下和之前的“车头A模式互助模板”一样的助力方式呢？

### ISSUE THREAD

**Issue by hjdyzy** [6dylan6/jdpro#78]
## 填 3 使用“车头A模式互助模板”，本套脚本内指定前 N 个账号优先助力，N 个以后账号间随机助力(随机部分账号顺序随机)。
![image](https://github.com/6dylan6/jdpro/assets/71299416/2ed70076-9307-4f66-9628-2f68d2398f8d)

**Comment by 6dylan6** [comment]
@hjdyzy 农场助力优先读变量FRUITCODES助力码，如果没设就读任务缓存的助力码，提示没有码就先运行任务。

如需车头固定其他随机，变量如下:
export recombin_ck_envs_num="1"
export recombin_ck_envs1="jd_fruit@2@5"
前5固定，按需改

**Comment by wqiklfnuyxa177** [comment]
> @hjdyzy 农场助力优先读变量FRUITCODES助力码，如果没设就读任务缓存的助力码，提示没有码就先运行任务。
> 
> 如需车头固定其他随机，变量如下: export recombin_ck_envs_num="1" export recombin_ck_envs1="jd_fruit@2@5" 前5固定，按需改

如果想要设置成原来的那 1 均等机会互助模板 呢？

**Comment by 6dylan6** [comment]
@wqiklfnuyxa177 那套弃用了

**Comment by wqiklfnuyxa177** [comment]
> 

请问现在如果要实现每天机会均等互助要怎么配置？

**Comment by hjdyzy** [comment]
> @hjdyzy农场优先读取信号FRUITCODES 驱动码，如果没有设置就读取任务队列的驱动码，提示没有码就先运行任务。
> 
> 前面车头固定其他随机，变量如下： export recombin_ck_envs_num=“1” export recombin_ck_envs1=“jd_fruit@2@5” 前5固定，依次改

你好，这个 export recombin_ck_envs_num=“1” 的意思是设置第一个账号优先助力，其他随机的意思吗?
这个 export recombin_ck_envs1=“jd_fruit@2@5” 是要手动设置所有账号的助力顺序吗？是要给每个账号都单独设置吗？

**Comment by 6dylan6** [comment]
@hjdyzy 下面哪个那个5是你要的，可以改
