### ISSUE TITLE
用电脑登录京东时候的轨迹验证一直失败，大家是怎么通过的？

### ISSUE THREAD

**Issue by chenwingsing** [6dylan6/jdpro#80]
我怀疑是京东识别到我是用电脑来画的轨迹，所以老是失败，你们都是用什么方法登进去获取cookie的？

**Comment by 6dylan6** [comment]
不要完全画到他线上，随意点，大致线图形就行。
安卓可以用alook浏览器快速抓

**Comment by lamking** [comment]
> 

感谢提供jdck工具
