### ISSUE TITLE
wsck转换：“疑似IP风控等问题 默认为失效”

### ISSUE THREAD

**Issue by xfchu1988** [6dylan6/jdpro#81]
这两天老是出现这个问题，大佬有没有解决办法？跪等！

**Comment by 6dylan6** [comment]
@xfchu1988 全都这样还是部分

**Comment by xfchu1988** [comment]
@6dylan6 多谢关注，是部分出现，而且无规律出现，同时被禁用了。但是运行ck检测时正常的，被禁用的ck手动启用后运行脚本时也是正常的。

**Comment by zhang9812** [comment]
我也是，前面几个正常，后面的全部提示“疑似IP风控等问题 默认为失效”

**Comment by 6dylan6** [comment]
@zhang9812 更新试试

**Comment by xfchu1988** [comment]
@6dylan6 更新后好了两天，今天又严重出现了，麻烦您能否继续处理一下，拜托
