### ISSUE TITLE
拉取的脚本中没有jd_indeps脚本

### ISSUE THREAD

**Issue by Constanyin** [6dylan6/jdpro#82]
3月9日在腾讯云使用
`ql repo https://js.6dygit.workers.dev/https://github.com/6dylan6/jdpro.git "jd_|jx_|jddj_" "backUp" "^jd[^_]|USER|JD|function|sendNotify"`
拉取脚本，拉到共计110条脚本
没有发现jd_indeps脚本

青龙配置文件config.sh显示： Version: v2.8.0，但是面板左上角显示v2.11.3，有点懵逼，不知道对拉取jd_indeps脚本有没有影响
使用到的青龙面板镜像拉取命令：docker pull whyour/qinglong:latest

**Comment by 6dylan6** [comment]
没影响，config.sh 里要配置，才能拉sh的，看我说明文档

**Comment by ocean521** [comment]
没看懂，小白一名，还请大佬赐教
