### ISSUE TITLE
初始化农场数据异常, 请确认此账号是否开通农场

### ISSUE THREAD

**Issue by hackgsl** [6dylan6/jdpro#82]
--------------【京东账号1】jd_MbZTxlwsWYdL---------------

初始化农场数据异常, 请确认此账号是否开通农场

==============📣系统通知📣==============
东东农场-任务
【京东账号1🆔】jd_MbZTxlwsWYdL
【数据异常】请确认此账号是否开通农场

日志里面显示这个、没有其他信息，APP上手动浇水是正常的。

**Comment by 6dylan6** [comment]
@hackgsl app看的是这个号吗
