### ISSUE TITLE
东东农场-助力

### ISSUE THREAD

**Issue by zhang9812** [6dylan6/jdpro#83]
比如有15个cookie，1，2，3号个cookie助力10次，4,5,6号cookie助力2次，如何是设置？

**Comment by zhang9812** [comment]
之前是设置export FRUITCODES=‘COOKIE1助理码1@COOKIE1助理码2@COOKIE1助理码3&COOKIE2助理码1@COOKIE2助理码2COOKIE2助理码3&……’
现在好像设置了@无效

**Comment by 6dylan6** [comment]
@zhang9812 不支持

**Comment by sunopen1979** [comment]
就是也不能把助力码设置成变量了吗？

**Comment by 6dylan6** [comment]
@sunopen1979 可以，看注释

**Comment by sunopen1979** [comment]
> @sunopen1979 可以，看注释

农场的变量设置了，好用。种豆得豆的变量就一直不知道是啥名字，试了好几种PLANT_BEAN_SHARECODES，PlantBeanShareCodes，都不对。内部互助前三个账号都是助力到自己的码就直接结束了，运行下一个账号

**Comment by 6dylan6** [comment]
@sunopen1979 种豆不能指定，是运行中搜集助力码，所以第一个么有助力目标
