### ISSUE TITLE
东东农场任务，运行环境异常

### ISSUE THREAD

**Issue by bling6** [6dylan6/jdpro#84]
初始化农场数据异常, 请登录京东 app查看农场0元水果功能是否正常,农场初始化数据: {"code":"404","message":"运行环境异常，请您从正规渠道参与活动，稍后再试哦"}

拉了库也没有新的更新诶，咋办

**Comment by 6dylan6** [comment]
@bling6 执行问题修复在拉

**Comment by bling6** [comment]
@6dylan6  该怎么执行修复，不太懂

**Comment by 6dylan6** [comment]
@bling6 有个任务，你搜修复看看

**Comment by bling6** [comment]
@6dylan6 我这没这个任务

**Comment by 6dylan6** [comment]
@bling6 那你很久没更新了，删除重新拉吧

**Comment by bling6** [comment]
已解决，感谢
