### ISSUE TITLE
资产通知怎么配置，显示开始发送通知，但是没收到通知

### ISSUE THREAD

**Issue by heyzqq** [6dylan6/jdpro#85]
资产通知是和系统设置里面的机器人通知同一个吗？

配置了企业微信机器人，登录能收到通知，但是并没有收到资产通知，需要配置环境变量吗？

```SH
# task dylanote_jdpro/jd_bean_change.js
...
开始发送通知...
通知标题: 京东资产统计

🔔京东资产统计, 结束! 🕛 23.8 秒
```

第一次用青龙，只用了这个库里提供的脚本，没用到其他的。

**Comment by tty228** [comment]
在配置文件里面填

**Comment by 6dylan6** [comment]
配置文件里不是有很多消息通知吗，钉钉，企业微信，server酱等把参数配置进去

**Comment by heyzqq** [comment]
> 配置文件里不是有很多消息通知吗，钉钉，企业微信，server 酱等把参数配置进去

好的，找到了，谢谢啦。

顺便问一句，配在这里和配在“环境变量”里效果应该是一样的吧？

**Comment by 6dylan6** [comment]
不太一样。环境变量里只配置CK。其他参数都在配置文件
