### ISSUE TITLE
❗️东东农场-任务, 错误!

### ISSUE THREAD

**Issue by shaufo** [6dylan6/jdpro#85]
![微信截图_20230907100222](https://github.com/6dylan6/jdpro/assets/63514384/eb16c8e8-23c7-4734-a267-36e2389d609e)

大佬，农场任务出错，已经重新拉库，但是问题依旧，请问该如何解决？

**Comment by 6dylan6** [comment]
@shaufo 已经提示网络连接失败了

**Comment by shaufo** [comment]
好的，重启软路由解决了。谢谢
