### ISSUE TITLE
初始化农场数据异常, 请登录京东 app查看农场0元水果功能是否正常

### ISSUE THREAD

**Issue by lengerqi** [6dylan6/jdpro#86]
库已经全删了重新拉最新的了， 其中一个号农场异常，8月24日后出现的， 但另外一个号一直正常。   异常的账号进入京东app农场活动能正常浇水啥的，这是被京东拉黑了么？只能app上操作了么？

日志如下：

============脚本执行时间：2023/9/7 10:27:13=============

>>>>>>>>>>>>>>6Dylan6 提示：任务正常运行中>>>>>>>>>>>>>>>

共2个京东账号

开始【京东账号1】jfbluesky

初始化农场数据异常, 请登录京东 app查看农场0元水果功能是否正常,农场初始化数据: {"code":"404","message":"运行环境异常，请您从正规渠道参与活动，稍后再试哦"}

==============📣系统通知📣==============
东东农场-任务
【京东账号1🆔】jfbluesky
【数据异常】请手动登录京东app查看此账号东东农场-任务是否正常
开始【京东账号2】188688_p

【京东账号2（188688_p）的东东农场-任务好友互助码】f8f6ce43a925417e94c406a6aaccfc5c

【已成功兑换水果】11次

山西水蜜桃3斤种植中...

**Comment by 6dylan6** [comment]
@lengerqi 你用的还是老的啊，最新版本有版本提示

**Comment by lengerqi** [comment]
怎么更到最新？  我任务全删了，然后用拉库命令也还是老的么？
青龙很久没升了，还是2.11.3

**Comment by 6dylan6** [comment]
@lengerqi 搜修复，执行修复任务在拉库

**Comment by lengerqi** [comment]
感谢大佬，已修复， 原来是我一直都没成功更新库过。 repo下全删了后重新拉库，现在正常了
