### ISSUE TITLE
新版wskey转换

### ISSUE THREAD

**Issue by sunopen1979** [6dylan6/jdpro#88]
【警告】s在获取token时失败，等待5秒后重试
一共11个wskey全是这个错误，隔一会也是，最多时能更新2个，token是什么？有什么办法吗？

**Comment by 6dylan6** [comment]
@sunopen1979 你用旧版正常吗?

**Comment by sunopen1979** [comment]
昨天还正常呢，我刚刚又全部从新获取了wskey，还是不行，是需要换ip吗？

**Comment by 6dylan6** [comment]
@sunopen1979 没理由啊，老版本也限制ip啊。你换老版本试试看看

**Comment by sunopen1979** [comment]
我从新拨号换ip就可以了，但是最后一个还是不行，是不是一个ip只能更新10个key啊

**Comment by 6dylan6** [comment]
@sunopen1979 不确定，你对比昨天的老版本日志看看哪个效果好就用哪个

**Comment by sunopen1979** [comment]
老版本怎么找回?

**Comment by 6dylan6** [comment]
@sunopen1979 更新我传了，本地转换是新版。另一个是老版本
