### ISSUE TITLE
京东集魔方错误

### ISSUE THREAD

**Issue by nature2608** [6dylan6/jdpro#93]
<img width="386" alt="image" src="https://user-images.githubusercontent.com/32662472/159344818-363ad7c2-5718-4788-8258-2bce515c6d46.png">
❗️京东集魔方, 错误!
TypeError: Cannot convert undefined or null to object
    at Function.keys (<anonymous>)
    at /ql/scripts/6dylan6_jdpro/jd_jmofang.js:132:40
    at processTicksAndRejections (node:internal/process/task_queues:96:5)

**Comment by 6dylan6** [comment]
活动没了
