### ISSUE TITLE
带图评价总会中断

### ISSUE THREAD

**Issue by shaufo** [6dylan6/jdpro#94]
大佬，jd的带图评价如下图，在评价几个号后就会出错。看了一下日志，只有7号和8号没有出错，但没有出错的情况下只评了10个号。求解~~
![001](https://github.com/6dylan6/jdpro/assets/63514384/2d74499d-0c43-4c8e-a1ff-8094f28411f4)
![002](https://github.com/6dylan6/jdpro/assets/63514384/f49c97c0-72c1-4e5e-9f8e-175905ee1663)

**Comment by zhang9812** [comment]
+1，我也一样，

> 当前使用内置sign
> 获取待评价数据失败
> 等待...
