### ISSUE TITLE
农场助力脚本，第一次运行就显示助力次数已用尽

### ISSUE THREAD

**Issue by HAN915** [6dylan6/jdpro#97]

**Comment by HAN915** [comment]
![image](https://github.com/6dylan6/jdpro/assets/100837367/88d8db5f-6c2e-40bd-83d6-449dc458dfdf)

**Comment by 6dylan6** [comment]
@HAN915 第一次用吗？ck怎么获取的

**Comment by HAN915** [comment]
> @HAN915 第一次用吗？ck怎么获取的

alook手机浏览器抓的

**Comment by 6dylan6** [comment]
@HAN915 那不知道了，自己找找原因 ，有上其他车没有，有乱用啥插件app
