### ISSUE TITLE
更新/ql/data/repo/6dylan6_jdpro失败，请检查网络...

### ISSUE THREAD

**Issue by Otvo** [6dylan6/jdpro#98]
<img width="496" alt="image" src="https://github.com/6dylan6/jdpro/assets/62050861/67cfad53-1783-4649-822c-cf1775c3779d">
这种情况咋办？换代理也不行

**Comment by 6dylan6** [comment]
@Otvo 执行修复任务在拉

**Comment by Otvo** [comment]
执行了，但是还是拉不了
<img width="382" alt="image" src="https://github.com/6dylan6/jdpro/assets/62050861/f5c4c737-0606-478e-86a2-8c65f9efece4">

**Comment by Otvo** [comment]
<img width="510" alt="image" src="https://github.com/6dylan6/jdpro/assets/62050861/8f832ecd-1d86-40e0-a37c-ec53f53a5224">

修复也在报错

**Comment by 6dylan6** [comment]
@Otvo 手动进去目录/ql/data/repo下面删吧

**Comment by Otvo** [comment]
<img width="503" alt="image" src="https://github.com/6dylan6/jdpro/assets/62050861/728c4423-f694-4770-bd10-30b4f2ac9abf">
<img width="784" alt="image" src="https://github.com/6dylan6/jdpro/assets/62050861/b2576305-20e9-4216-9774-fa90b855efcf">
删空了还是不行

**Comment by 6dylan6** [comment]
@Otvo 那不要用代理
