### ISSUE TITLE
wskey的代理设置

### ISSUE THREAD

**Issue by sunopen1979** [6dylan6/jdpro#99]
现在用wskey转cookie限制ip，11个号每次都限制，使用网上的代理没有内蒙的ip，用两次wskey就失效了，我就用本地有公网ip的电脑做了3个代理服务器，可是发现没办法设置成自动换代理ip，做“隧道型代理池接口”或者“拉取型代理API接口”网上还没找到教程，大神有啥办法，让我使用“wskey本地转换”时能直接设置3个代理自动换，或者哪里有做代理接口的教程告诉我也行，谢谢！@

**Comment by ni11gg** [comment]
没有代理可以自行注册，比如携趣，巨量，每日免费1000IP，完全够用
然后添加 环境变量就行了
