### ISSUE TITLE
青龙升级新版2.12后备注显示变量不生效了

### ISSUE THREAD

**Issue by Fliangui** [6dylan6/jdpro#99]
我弄的青龙自动升级了 然后环境变量和定时任务啥的都没有了 ,我重新拉库后添加了任务和变量,然后才发现以前的变量存放位置和最新版的不一样.

**Comment by Fliangui** [comment]
青龙升级到2.12后  配置文件路径从ql/config变成了 ql/data/config  .所以部分脚本失效了

**Comment by 6dylan6** [comment]
是的，新版已经目录结构变化了，升级前做好备份，或者禁用升级

**Comment by 6dylan6** [comment]
通知已经兼容新版了

**Comment by Fliangui** [comment]
> 通知已经兼容新版了
